### ISSUE TITLE
Migrate the MapStore project source code

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#1]
The source code of the [GeOrchestra MapStore project](https://github.com/geosolutions-it/MapStore2-C169) must be migrated to [this](https://github.com/georchestra/mapstore2-georchestra) repository

**Comment by MaelREBOUX** [comment]
Nice.
Dont' forget to delete the previous repo : https://github.com/geosolutions-it/MapStore2-C169  ?

**Comment by pmauduit** [comment]
the previous url is also referenced in some files:

* https://github.com/georchestra/mapstore2-georchestra/blob/master/pom.xml#L9
* https://github.com/georchestra/mapstore2-georchestra/blob/master/web/pom.xml#L12
* etc...
