### ISSUE TITLE
make sure the webapp is fully relocatable

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#103]
I know we're still in the early stages of development, but it'd be nice to ensure there are no hardcoded traces of the webapp name - if i want to deploy GeOrchestra.war as mapstore.war or carto.war, things should just work.

As of now (just an example i found while playing with it), the geostore h2 url points at `jdbc:h2:./webapps/GeOrchestra/geostore` (cf https://github.com/georchestra/mapstore2-georchestra/blob/master/web/src/main/resources/geostore-datasource-ovr.properties#L1) which wont exist if the webapp is deployed as a different name

Same thing for urls inside the webapp, there should be no `/GeOrchestra/` hardcoded :)

**Comment by tdipisa** [comment]
@landryb thank you so much for your feedback, we will check as soon as possible.

**Comment by mbarto** [comment]
@landryb currently, apart from the h2 connection string you found, there should be no problem in relocating the GeOrchestra war or renaming it (in our test environment is already named mapstore.war). I am going to check if there are any places that need to be fixed for this.

**Comment by landryb** [comment]
Yep, i'm also testing it under `/mapstore/` and it seems to work fine - it's a bit linked with #112 where we should ensure all things that can be 'custom' can be modified without recompiling the webapp..
