### ISSUE TITLE
use georchestra.datadir env variable instead of requiring a new georchestra-config property

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#104]
in #81 the database config was added, and the doc/code mentions a new `georchestra-config` property/env var to set, pointing at the `default.properties` file.

in georchestra setups, we already have a `georchestra.datadir` property/env var, which points usually at `/etc/georchestra` - and `defaults.properties` can be overriden by a per-app `.properties` file - ie if i want a db setup for all modules but mapfishapp, i will override `pgsqlHost` in `mapfishapp.properties`.

So to be in-line with what we do in georchestra, i think the best is:
* to use the existing `georchestra.datadir` property to know where the config is located, instead of having to add a new one
* to implement in the spring config the property priority setup that was done in georchestra/georchestra#2299 (and several other issues)

**Comment by landryb** [comment]
My idea for proper integration was:
* in `/etc/georchestra/mapstore/geostore.properties`, having the params that only matter to the mapstore webapp, and a commented entry for the ones that can override the ones present in `default.properties`
* have the same `geostore.properties` shipped in the webapp for 'failsafe' mode when running without a georchestra datadir in testing period.

We have the same scheme for all georchestra blocks so far.

@fvanderbiest does this look good to you ?

**Comment by landryb** [comment]
https://github.com/landryb/mapstore2-georchestra/commit/464c579e6a091ef31269260c3d709293f24456a5 allows me to load properties from `default.properties` - it would still be better usinge ${georchestra.datadir}` anyway :)

**Comment by tdipisa** [comment]
@landryb thank you so much for your feedback, we will check as soon as possible.

**Comment by landryb** [comment]
once properties are properly loaded, the database schema is created & populated with the sql from #81, putting the webapp behind the security-proxy on a testing instance works fine, and it properly reads auth from the headers sent by the SP.

Once connected as my user:
```
INFO   2019-11-21 14:38:42.405   RESTServiceImpl.extractAuthUser() - Accessing service with user breuil and role USER
```
created georchestra role MAPSTORE_ADMIN, added my user to it, logged out, logged in, also works:
```
INFO   2019-11-21 14:40:04.055   RESTServiceImpl.extractAuthUser() - Accessing service with user breuil and role ADMIN 
```

so good work on that part :)

**Comment by mbarto** [comment]
To externalize all the configuration files we also need this: https://github.com/geosolutions-it/http-proxy/issues/48
