### ISSUE TITLE
Remove background modal window is mobile

### ISSUE THREAD

**Issue by francoperversi** [georchestra/mapstore2-georchestra#107]
Trying to  remove a background from the background selector, a modal window appears in order to confirm removal. This modal window is mobile and this is not in accordance with the others modals. This issue is a problem above all in geOrchestra because when the modal goes under the geOrchestra topbar it's after impossible to move it again. In conclusion, this modal window should be impossible to move

![remove_bck gif](https://user-images.githubusercontent.com/54808782/69150763-97d94100-0ad9-11ea-896a-ac4daf512f4e.gif)

**Comment by offtherailz** [comment]
Fixed in https://github.com/geosolutions-it/MapStore2/pull/4536
