### ISSUE TITLE
Check support for latest Debian version

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#119]
As the new version of Debian use JAVA 11, the viewer need to support it.
In the README, only JAVA 8 is reported as supported.

Also npm, nodejs (10) & tomcat (9) versions need to be supported.

**Comment by tdipisa** [comment]
Dear @jusabatier please take a look at the comment [here](https://github.com/georchestra/mapstore2-georchestra/issues/61#issuecomment-546279784). Thank you.

**Comment by mbarto** [comment]
@jusabatier we will test the build under nodejs 10, we usually suggest nodejs 8, so we didn't so far

**Comment by jusabatier** [comment]
@tdipisa : Sorry I missed this issue. Maybe update the README to inform JAVA11 & Tomcat9 are supported.

@mbarto : Would be great if njs10 is supported as it's the version curently packaged in the latest debian, but if not there are a lot of simple tutos to install a selected version of it via NVM

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-debian-10

**Comment by mbarto** [comment]
@jusabatier we did a succesful test on latest debian.
We also tested NodeJS 10 and npm 6, with success, so we updated the README with this PR: https://github.com/georchestra/mapstore2-georchestra/pull/149

**Comment by jusabatier** [comment]
Great, thanks.
I close the issue.
