### ISSUE TITLE
Application Context - Parametric viewers - Advanced - Templates

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#130]
The base support to define/manage multiple parametric viewers has been defined and the administrator is now also able to configure the list of extension for the viewer. Each application context must be identified also by the following elements:

- List of available template maps

Map templates are basically pre cooked map contexts containing the map configuration (layers, backgrounds etc).

Map templates can be stored in MapStore in two formats: standard MS format (map json config) or WMC.
 
Map templates are belonging independently on the format in a dedicated MS category and they are public (see #5 for WMC samples). Information related to templates must be persisted into the DB (within the resource belonging to the dedicated backend category)

This issue involves the step n° 2, the mockup [here](https://demo.geo-solutions.it/mockups/mapstore2/geoorchestra/#/app-context/general-settings). 
In particular this issue involves the needed work to configure the backend (the UI work is part of the issue #131):

- Category creation in GeoStore 
- Creation of new GeoStore resources (sample resources) for Map templates belonging to the created category

**Comment by francoperversi** [comment]
Retest after solving comments [here](https://github.com/georchestra/mapstore2-georchestra/issues/131#issuecomment-579712620)
