### ISSUE TITLE
Application Context - Parametric viewers - Advanced UI - Templates

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#131]
A basic administration UI has been provided for the administrator to create and configure the application context identified by name and its URL.
Within the admin UI also the following settings must be available:

- Define the list of available map templates

The aim of this issue is to allow the administrator to define and manage the list of Map templates that need to be available to the final user inside the new extension that will be developed with the issue #34. 

A proper configuration flow for the administrator must be provided in the context wizard, where templates can be selected from a list. New WMC templates (or MapStore JSON map context) can be also uploaded to be persisted and inlcuded in the list leveraging on the work provided within #130 (see also #5 for some WMC samples to use for test).

Within the step 2 of the context wizard (the mockup [here](https://demo.geo-solutions.it/mockups/mapstore2/geoorchestra/#/app-context/configure-plugins)), the administrator can create the list of plugins for the final context's viewer. Within this step of the wizard the Map Template plugin (issue #34) can be selected and configured in the same way of other plugins.

For the Map Template plugin an additional configuration button allows open an admin UI to configure the list of templates to provide for this plugin to the final user in the viewer:

![georchestra_templates](https://user-images.githubusercontent.com/1280027/70527824-16f7ed00-1b4d-11ea-8469-9af69360f789.jpg)

This admin UI is what we have to develop for this issue:

![image](https://user-images.githubusercontent.com/1280027/70527856-31ca6180-1b4d-11ea-8378-76a0948da438.png)

- The template admin UI allows to browse existing templates (stored in DB) and select the ones to include in the plugin (that will be visible then to the user in the viewer). 

- It is also possible to upload new templates in both format (WMC and standart MS JSON format). For new uploaded templates a modal opens to allow the admin to specify related metadata: thumbnail, name and description like happens for other resourecs in MS.

![image](https://user-images.githubusercontent.com/1280027/70528353-4eb36480-1b4e-11ea-9b71-63bf07f88823.png)

- The list of selected Templates will be represented by a json configuration that will be used by the Map Template plugin (issue #34).

- It must be possible to also edit existing metadata of a created template: an edit icon will appear for each template card in the UI in order to allow the user to open the template properties (thumbnail, name, description) and edit them.

![template_metadata_edit](https://user-images.githubusercontent.com/1280027/72547728-77392780-388d-11ea-96ae-87e0829021af.png)

- A delete button (trash) should be provided too for each existing template item on the left

**The complete mockup is available online [here](https://demo.geo-solutions.it/mockups/mapstore2/geoorchestra/#/app-context/configure-plugins)**

**Comment by tdipisa** [comment]
@francoperversi some consideration here for testers:
the save button should not be enabled until all mandatory fields are filled or at leas a warning message should appear (@vlt1)

**Comment by francoperversi** [comment]
> @francoperversi some consideration here for testers:
> 
> * the save button should not be enabled until all mandatory fields are filled or at leas a warning message should appear, now I can save a template without uploading a context file
> * I cannot delete esisting contexts
> * It was not possible to save a Template in georchestra DEV because the DB category was missing (TEMPLATE), in that case there was an unknown waring popup in MS (related to a 404 not found response): missing category should be automatically created if missing in DB.
> 
> @vlt1

The first two points are present also in Mapstore dev, as specified in [this comment](https://github.com/geosolutions-it/MapStore2/issues/4746#issuecomment-578817463)
