### ISSUE TITLE
Create PR to version all the changes described in the doc

### ISSUE THREAD

**Issue by Gnafu** [georchestra/mapstore2-georchestra#133]
We should not impact the geOrchestra release process so create the draft pull requests for the header changes.

**Comment by mbarto** [comment]
We also need to add translations for the mapstore button label, here:

https://github.com/georchestra/georchestra/tree/master/header/src/main/resources/_header/i18n

**Comment by Gnafu** [comment]
Create a draft request for this.

**Comment by Gnafu** [comment]
Draft Pull Request for Header changes:
https://github.com/georchestra/georchestra/pull/3058

Draft Pull Request for datadir changes:
https://github.com/georchestra/datadir/pull/186

Draft Pull Request for docker changes:
https://github.com/georchestra/docker/pull/58

**Comment by fvanderbiest** [comment]
Hi @Gnafu 
I would have expected the georchestra database image to be modified too, with the addition of https://github.com/georchestra/mapstore2-georchestra/tree/master/database into https://github.com/georchestra/georchestra/tree/master/postgresql

**Comment by Gnafu** [comment]
Indeed @fvanderbiest , I'll update the PR

**Comment by Gnafu** [comment]
Done

**Comment by Gnafu** [comment]
I updated the categories to match https://github.com/georchestra/mapstore2-georchestra/blob/master/web/src/main/resources/sample_categories.xml

**Comment by catmorales** [comment]
Thanks !
