### ISSUE TITLE
Extension Manager - Base support to manage extensions

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#14]
An extension manager must be implemented to allow to administrators the possibility to manage extensions within a viewer context. The extensions need to be distributed in a compiled form.

Related to https://github.com/geosolutions-it/MapStore2/issues/4629

**Comment by mbarto** [comment]
These are the MapStore improvements needed:
 * [ ] https://github.com/geosolutions-it/MapStore2/issues/4629

**Comment by offtherailz** [comment]
Please take a look at this comment: 

https://github.com/georchestra/mapstore2-georchestra/issues/15#issuecomment-564974270

The configuration explained contains all the information requred by the config builder. 
Some of them are coming from plugins. Can you please: 
 - Integrate it with your needed configs, if needed
 - Suggest, as well as you worked on plugins, what of the information should be in framework and what in configuration.

**Comment by mbarto** [comment]
@offtherailz 

 * the configuration that should stay on the framework is the one we already have there: plugin code and runtime needed configuration (containers, reducers, epics, etc.), I don't think anything new should be introduced there
 * the remaining configuration (descriptions, icons, tree structure, etc.)  that is only useful for the various UIs (extension manager, etc.) should be separated and refer the runtime plugin by its name

**Comment by offtherailz** [comment]
I add the list ofthings to complete for this task, after https://github.com/geosolutions-it/MapStore2/pull/4630 is merged. Please @mbarto integrate if somthing is missing: 

- [ ] Extensions manage translations (I've seen a comment explains that rising everything to standard app allows to load translations but didn't find an example of it? 
- [ ] document how to build the final package (with translations...)
- [ ] Build tool missing things (see [this comment](https://github.com/geosolutions-it/MapStore2/pull/4630#discussion_r369692799)). Can you please detail @mbarto 
- [ ] Anything more? 

When this list is finalized, we can open the issues to handle missing things.
