### ISSUE TITLE
"Already existing resource" warning message in wizard

### ISSUE THREAD

**Issue by francoperversi** [georchestra/mapstore2-georchestra#141]
Creating a New Context or editing an existing one with the "Edit context" button, if you try to set the name of the context same as an already existing resource name, the warning message appears only in the last step of the wizard. In this case the warning message should appears when you click on "Next" in the first step (General Settings).

![warning_message](https://user-images.githubusercontent.com/54808782/70307864-5b605180-180a-11ea-95ba-08728f5d7725.gif)

This issue is related to https://github.com/geosolutions-it/MapStore2/issues/4615

**Comment by tdipisa** [comment]
@vlt1 there is an issue identified during test [here](https://github.com/geosolutions-it/MapStore2/issues/4615#issuecomment-575699816).
