### ISSUE TITLE
java.io.FileNotFoundException: /default.properties

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/mapstore2-georchestra#145]
Following http://docs.georchestra.geo-solutions.it/fr/latest/georchestra_integration/index.html, there are several things to report :
 *  `-XX:MaxPermSize=128m` is useless: `OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0`
 * logs are being written in the container (`/usr/local/tomcat/logs`), this should be prevented 
 * more importantly, the webapp fails to initialize with the following log:
```
ContextLoader.initWebApplicationContext() - Context initialization failed
org.springframework.beans.factory.BeanInitializationException: Could not load properties; nested exception is java.io.FileNotFoundException: /default.properties (No such file or directory)
```
Did I miss something ?

**Comment by fvanderbiest** [comment]
Got it: `-Dgeorchestra.datadir=/etc/georchestra`

but later ...
```
log4j:ERROR Could not read configuration file from URL [file:/etc/georchestra/mapstore/log4j.properties].
08/01/2020 12:00:09 java.io.FileNotFoundException: /etc/georchestra/mapstore/log4j.properties (No such file or directory)
```

**Comment by fvanderbiest** [comment]
May I suggest you PR against https://github.com/georchestra/datadir/ to provide sensible defaults (http://docs.georchestra.geo-solutions.it/fr/latest/configuration/) ?

**Comment by tdipisa** [comment]
@fvanderbiest yes sure, @mbarto will proceed soon providing a PR to georchestra/datadir

**Comment by mbarto** [comment]
@fvanderbiest is there a preferred location for logs? Do you know where the other georchestra application store their log files?

**Comment by landryb** [comment]
the default datadir configs store them in `/tmp/webapp.log` (cf https://github.com/georchestra/datadir/blob/19.04/console/log4j/log4j.properties#L24) since that's a directory where tomcat/jetty user can write, so maybe default to` /tmp/mapstore.log` ? I know here i use `/srv/log` but that's a local customization

**Comment by mbarto** [comment]
@fvanderbiest @landryb I prepared a PR with documentation fixes for JAVA_OPTS: https://github.com/georchestra/mapstore2-georchestra/pull/148

**Comment by mbarto** [comment]
@fvanderbiest @landryb and another one for the datadir: https://github.com/georchestra/datadir/pull/182
