### ISSUE TITLE
Application Context Plugin Review

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#155]
A list of things to review comes from #22:

- [x] It is possible to insert the plugin `Map Details` that allows to see map details but it is actually impossible to add details for contexts. If we don't want to improve application contexts adding details to them, we should remove the possibility to add this plugin

>> **@offtherailz**: Now is not possible, but in future we will be able to open maps in context, therefore this is possible. You can do it, for the moment, in the URL, putting the map id in the URL. [example](https://dev.mapstore2.geo-solutions.it/mapstore/#/context/all-plugins/11745). 

>> **@tdipisa**: for geOrchestra we don't need that plugin for the moment, so it can be hidden in the list for geOrchestra. Leave it as it is in MapStore.

- [x] The `Query panel` plugin should probably be hidden from plugin list, and should be enabled by default when others plugins that use the Query panel are added (like Attribute Table, layer filter, Widgets). There's probably a problem related to `Query panel` plugin because sometimes it enables adding the `List of Layers` plugin and sometimes does not). Moreover I can add this plugin alone also if it depends from other plugins.

>>**@offtherailz**: Sure, It is listed because it is configurable.

- [x] `Style Editor` plugin what is it for? Seems that nothing change adding or not this plugin (if this plugin serves to create new styles it doesn't work). Moreover this plugin can be added alone, also if it probably depends from TOC and from layer settings

- [x] `Widgets` plugin should depends from `List of Layers` plugin, but I can actually add it alone. If you add both `Widgets` plugin and `List of Layers` plugin, the widgets button is not present in toc selecting a layer

- [x] The `Download data` from attribute table plugin can be added alone, but should be related to `Attribute Table` plugin 

- [x] Morover was noticed that in step 3 of the wizard (Configure Map), clicking on `Reload Map` button, the modal window that opens is draggable vertically (why?) and the X button is in lowercase. If I click outside the window, it closes.

- [x] The show metadata option should be disabled by default, so the related button in TOC toolbar does not appears (the button is automatically enabled when you ad a layer from a CSW source)

- [x] If I add undo/redo plugins nothing appears in the viewer: buttons are not present in nav toolbar. Only adding the expander plugin these are available. We should at least set up a dependency in configuration and make the expander plugin hidden to be automatically added when needed.

- [x] The AutoMapUpdate plugin can be excluded from the list I think 

- [x] If I add just one plugin related to the MS nav toolbar (i.e. zoom to the max extent) when I click on the map the toolbar move on the left

![image](https://user-images.githubusercontent.com/1280027/73273590-88b2f580-41e4-11ea-9e5e-d4b5a7a53c7d.png)

- [x] I think the home button plugin can be excluded from the georchestra configuration (geOrchestra only)

- [x] If I embed a context in an Iframe the geOrchestra header must not appear.

- [x] after creating a context without the Identify plugin enabled, if I click on the map the marker appears: it should appears only if the identify tool has been activated for that context.

- [x] If I add the TOC with the attribute table enabled, the attribute table is not available in the viewer's context. The same for Layer Settings (geOrchestra only)

- [x] When I add the 'About plugin' also the Burger menu is automatically added but finally the about is not present in the context (geOrchestra only). It was decided to remove about plugin from geOrchestra since About plugin actually reports information about MapStore

![image](https://user-images.githubusercontent.com/1280027/73282292-a20e6e80-41f1-11ea-8c94-c8588b406ea3.png)

- [x] Contexts with read permissions to everyone are not accessible (HTTP 404). Related to https://github.com/geosolutions-it/geostore/issues/202 

- [x] The **User Extensions** plugin must be hidden in this step of the wizard and must be automatically included as soon as the administrator has set up an extension for it to appear in the Extensions Library to be activated by the end user.

- [x] In "Version" plugin the description is "Show Mapstore Version in settings window" but in Georchestra the version showed is the Georchestra one: we should generalize the description

- [x] Adding Map Templates, Burger Menu is not added together

- [x] Adding "Save" plugin, the Burger Menu is added together but after the save option is not present in the Menu

- [x] Is not necessary to keep both Save and Save as plugins, Was decided to keep only Save plugin.

**Comment by offtherailz** [comment]
Please take into account to add This point
- [ ] Add a flag to allow userSelection in the context-creator that make the button "make user selection..." visible. (Also make sure that sub-plugins For TOC and Widget hasUserSelection = false)

**Comment by francoperversi** [comment]
@vlt1 
When I add the 'About plugin' also the Burger menu is automatically added but finally the about is not present in the context (geOrchestra only)
This issue is still there

**Comment by vlt1** [comment]
'About plugin' is a product plugin and not a single product plugin is included in georchestra, probably on purpose. And in any case the info displayed in About plugin will be MapStore specific, not about georchestra.
