### ISSUE TITLE
Improve Plugin configuration in Application Contexts

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#161]
We can further improve the configuration tier of plugins inside the application context wizard (step 2) by including the "overrides" property and not only "cfg" as it is now.

**Comment by vlt1** [comment]
How should it work, exactly? A separate button just for overrides? Some other way?

**Comment by tdipisa** [comment]
@vlt1 we should be able to configure both overrides and cfg properties in the text area that we have. @offtherailz do you have some concern about that ?

**Comment by offtherailz** [comment]
we should change the editor root, this way
{
    "cfg": { } // defaultConfiguration,
   "other configurations like overrides.
}

**Comment by vlt1** [comment]
localConfig currently contains the "override" property on some plugins, that are currently being merged into the resulting config of plugins in context creator. After the changes are introduced this will no longer be the case. Should these "override" properties in localConfig copied over to corresponding "defaultOverride" properties in pluginsConfig?

**Comment by offtherailz** [comment]
Is it possible to replace it only if present, otherwise use the localConfig's one?
