### ISSUE TITLE
Adding a WMTS in a map projected in EPSG 3948

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#163]
Tested on : https://georchestra.geo-solutions.it/mapstore/#/
Account : testadmin
Date : 12/02/2020

As user, on mapstore i  changed the map projection to EPSG3 948, i added from our public IDS (which serve 3857,3948 and 2154 datas):
* a WMS layer --> OK
* a WMTS layer --> NOK
![image](https://user-images.githubusercontent.com/4659829/74345214-07478f80-4dae-11ea-8d7c-e137123f1433.png)

Error message :
 ```
<ExceptionText>describedomains is not implemented</ExceptionText>
```
When i changed newly, the map projection to 3857, WMTS layer is displayed

**Comment by landryb** [comment]
Cf #108, which should be fixed by geosolutions-it/MapStore2#4810

**Comment by landryb** [comment]
err, maybe the describedomains bit isnt fixed by the latter

**Comment by tdipisa** [comment]
Dear @catmorales you are right, we are just testing it and we have found a small bug. Supported CRSs are correctly identified by MapStore but we need to provide a small fix for the WMTS in MapStore to properly refresh the layer in map if not default MapStore CRSs are selected.

**Comment by mbarto** [comment]
Blocked by https://github.com/geosolutions-it/MapStore2/pull/4923

**Comment by mbarto** [comment]
Waiting for https://github.com/geosolutions-it/MapStore2/pull/4939 merge

**Comment by mbarto** [comment]
@catmorales should be fixed now
