### ISSUE TITLE
Loading plugin in a Context 

### ISSUE THREAD

**Issue by ElenaGallo** [georchestra/mapstore2-georchestra#166]
## Description

In MapStore:
Uploading this [plugin](https://github.com/geosolutions-it/MapStore2/files/4193806/plugin.zip) in a context, is visible only if opens the context for the second time 

In geOrchestra:
En error appears if you try to upload the plugin

## How to reproduce

In MapStore:
-  Open new context
-  Insert a Tilte
- Click on Add an extencion to Mapstore
- D&d the zip file
- Add Zoom in, Expender and My plugins on the list of available plugins
- Save
- Open the context
- Closed the context
- Open again 

In geOrchstra:
-  Open new context
-  Insert a Tilte
- Click on Add an extencion to Mapstore
- D&d the zip file

*Expected Result*

In MapStore:
 The My plugin is present opening the context for the first time
![plugin](https://user-images.githubusercontent.com/56537133/74360540-898f7e00-4dc5-11ea-93af-41557c88fe1e.JPG)

In geOrchstra:
Is possible upload the plugin

*Current Result*

In MapStore:
The My plugin is visible on the context only if the context is opens for the second time

In geOrchstra:
Uploading the plugin an error 400 appears 
`Caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.eclipse.jetty.http.BadMessageException: 400: Unable to parse form content`
- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

Related to  [https://github.com/geosolutions-it/MapStore2/issues/4629](https://github.com/geosolutions-it/MapStore2/issues/4629)

**Comment by mbarto** [comment]
Waiting for https://github.com/geosolutions-it/MapStore2/pull/4951 merge

**Comment by offtherailz** [comment]
I moved this in progress just to remember that it may need an update of imports (StandardApp and so on).

**Comment by ElenaGallo** [comment]
@mbarto on geOrchestra, it is not yet possible to upload the plugin because the validation request to the origin server did not take place (Error 404: cache-control: no-cache).

**Comment by mbarto** [comment]
@ElenaGallo should be fixed now, please test

**Comment by ElenaGallo** [comment]
@mbarto  it is now possible to load the plugin but by opening the context with the plugin inside a red page appears.

**Comment by ElenaGallo** [comment]
The plugin to use on is [myplugin.zip](https://github.com/georchestra/mapstore2-georchestra/files/4294010/myplugin.zip)
