### ISSUE TITLE
Configuration Questions

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#169]
there are several conflicting/confusing things wrt the config, right now in the war there's two https://github.com/georchestra/mapstore2-georchestra/blob/master/web/src/main/resources/geostore.properties and https://github.com/georchestra/mapstore2-georchestra/blob/master/docker/geostore-datasource-ovr.properties files, some in `mapstore/datadir/mapstore` in the war, some under `mapstore/WEB-INF/classes/` but that doesnt match what's been pulled into the datadir repo (https://github.com/georchestra/datadir/blob/master/mapstore/geostore.properties).

And on top of it, they seem to override each other wrt db connection:
```
[13/02 13:07] landry@demo.thruxton:/etc/georchestra $grep -v \# mapstore/geostore.properties |grep -v ^$
pgsqlHost=localhost
pgsqlPort=5432
pgsqlDatabase=georchestra
pgsqlUser=georchestra
pgsqlPassword=georchestra
ldapHost=localhost
ldapPort=389
ldapScheme=ldap
ldapBaseDn=dc=georchestra,dc=org
ldapAdminDn=cn=admin,dc=georchestra,dc=org
ldapAdminPassword=secret
ldapUsersRdn=ou=users
ldapRolesRdn=ou=roles
ldapOrgsRdn=ou=orgs
[13/02 13:07] landry@demo.thruxton:/etc/georchestra $cat mapstore/geostore-datasource-ovr.properties
geostoreDataSource.driverClassName=org.postgresql.Driver
geostoreDataSource.url=jdbc:postgresql://localhost:5432/georchestra
geostoreDataSource.username=georchestra
geostoreDataSource.password=georchestra
geostoreVendorAdapter.databasePlatform=org.hibernate.dialect.PostgreSQLDialect
geostoreEntityManagerFactory.jpaPropertyMap[hibernate.hbm2ddl.auto]=validate
geostoreEntityManagerFactory.jpaPropertyMap[hibernate.default_schema]=geostore
geostoreVendorAdapter.generateDdl=true
geostoreVendorAdapter.showSql=false
```
as for all the ldap bits (and psql bits), they're already defined in georchestra's https://github.com/georchestra/datadir/blob/master/default.properties#L69 so if you want to allow override in `geostore.properties` they have to be commented out by default like its done for example in https://github.com/georchestra/datadir/blob/master/cas/cas.properties#L27 - and the code reading them has to read first what's in `default.properties` and then eventually override the settings with what's found in `geostore.properties`.

All that to say that maybe some of the .properties files could be dropped from the war so we only have a single source of truth, and that has to match what's in the georchestra datadir repo (dont hesitate to do PRs there, we'll merge them!)

**Comment by mbarto** [comment]
Hi @landryb, thx for the feedback. I will try to simplify the stuff a little bit. In general, mapstore has its own (default) internal configurations and the possibility for external overrides. The georchestra datadir is an implementation of the override mechanism, so some duplication will always remain, but I understand that it could be simplified a bit.

**Comment by landryb** [comment]
reopening, @catmorales will add more feedback on the way config should be fixed/documented..

**Comment by landryb** [comment]
dunno if #195 will address all our interrogations (there's not much comments in the PR about what it actually changes/does), but we're still a bit confused about the config :)

**Comment by landryb** [comment]
one thing that is sure is that georchestra/datadir repository (in https://github.com/georchestra/datadir/tree/master/mapstore) lacks mapstore/localConfig.json which should be the default config to be amended/modified by an administrator. Right now it's not obvious where it is read from...

maybe the mapstore folder in the datadir repo should be updated after #193 & #195 ?

**Comment by catmorales** [comment]
Yes i agree, because in the standard installation (with docker) i don't see this file (localConfig.json) :
```
/data/georchestra_datadir/mapstore$ ls -lh
total 16K
-rw-r--r-- 1 sftp nogroup  112 Jan 16 10:58 geostore.properties
-rw-r--r-- 1 sftp nogroup  394 Jan 16 10:58 log4j.properties
drwxr-xr-x 2 sftp nogroup 4.0K Jan 16 10:58 printing
-rw-r--r-- 1 sftp nogroup 2.0K Jan 16 10:58 proxy.properties

```

**Comment by landryb** [comment]
a sample file is available in https://github.com/georchestra/mapstore2-georchestra/blob/master/localConfig.json but not in the war/image, so it should be in the datadir repo and the docker image ?

**Comment by mbarto** [comment]
@landryb @catmorales the reason why we didn't put localConfig.json (yet) in the datadir repository is because it changes very frequently during development, so it's a bit of work to have it synchronized. I will commit the current version anyway. When the file is not in the datadir, the one inside the application folder is used (this is common for most of the mapstore configuration files, to have a fallback to an internal application file)

**Comment by catmorales** [comment]
>we didn't put localConfig.json (yet)

Ok thank you for the information . We're very eager to test on ours infrastructures ;)

**Comment by mbarto** [comment]
@catmorales I did a PR to add the missing file: https://github.com/georchestra/datadir/pull/184

**Comment by landryb** [comment]
i'm pretty sure it's already documented somewhere in mapstore2 doc, but also to clear things up:
- what is the purpose of config.json vs localConfig.json
- same thing for new.json vs config.json

those 3 files were modified in #82, but its unclear to me if they should also be in the datadir as sample configs or not...

also, some bits should be taken from `default.properties`, ie at least the occurences of 'georchestra.geo-solutions.it'.. which is the `domainName` key in `default.properties`.

**Comment by mbarto** [comment]
@landryb 
 * localConfig.json is the unified mapstore configuration file for the frontend application (it does not contain a map configuration, but everything else that can be configured, such as available translations, default plugins configuration, etc.)
 * config.json is a static map configuration file that is used by the mapviewer when a map id is not specified in the url (for example when you load the georchestra mapstore viewer this map configuration is used)
 * new.json is another static map configuration that works as a template for the "New map" functionality

**Comment by landryb** [comment]
thanks - it's much clearer now. 

After actually looking more, i see:
- localConfig.json is documented in https://mapstore.readthedocs.io/en/latest/developer-guide/local-config/ (though there is one occurence of `localConfig.js`, maybe an oversight ?)

- `new.json` is documented in https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/
- but i only found the doc for `config.json` in https://github.com/geosolutions-it/MapStore2/blob/master/docs/developer-guide/application-tutorial.md - isnt linked in the public doc ? in the code, it is self-documented in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/jsapi/MapStore2.js#L27 but that wasnt so obvious..

anyway, we're getting better at understanding how to work with mapstore, and i really like it :)

**Comment by mbarto** [comment]
@landryb thanks for the feedbacks. I did a small PR in MapStore to add the missing things:

https://github.com/geosolutions-it/MapStore2/pull/5024

**Comment by tdipisa** [comment]
Many thanks @landryb

**Comment by catmorales** [comment]
Thank you all of you. With this information i will try to configure our test instance.

**Comment by tdipisa** [comment]
@catmorales do you need this issue still open?

**Comment by catmorales** [comment]
I think,  i  will have more questions about configuration  where can we discuss about it ?

**Comment by tdipisa** [comment]
@catmorales, as you prefer, we can continue using this issue for that.

**Comment by sigrmed** [comment]
@tdipisa great !

**Comment by sigrmed** [comment]
i've done some modifications in the configuration: (dataidir geostore in /etc/georchestra/
 i added specifics : 
* new.json, config
* localConfig.json
* config.json
I don't see modifications in the front, if i understood the config.json must be used on the standard mapstore viewer but i see the same as usual.

Question : is it necessary to restart the docker container after modification in this files ?

**Comment by sigrmed** [comment]
I restarted the container and it's the same . Do exist a cache to clean ?

**Comment by mbarto** [comment]
@sigrmed config.json and new.json are currently not externalized (not read from the datadir, only from the webapp folder), so copying them there will have no effect.
Only localConfig.json can be loaded from the datadir is at the moment.

**Comment by sigrmed** [comment]
AHH  OK thank you very much for your answer.
 I will waiting more so for the integration in our platform.

**Comment by catmorales** [comment]
Another question.
In the localconfig.json, i'd like to customize the background layers.
I readed the https://mapstore.readthedocs.io/en/latest/developer-guide/local-config/ but i don't see nothing about " providers" and "source"
Example :
 ```
{
                    "type": "tileprovider",
                    "title": "OpenTopoMap",
                    "provider": "OpenTopoMap",
                    "name": "OpenTopoMap",
                    "source": "OpenTopoMap",
                    "group": "background"
                  },
```
What is the use of these and where are they defined ?

**Comment by landryb** [comment]
from what i understood last i looked at the code the available ones are all defined in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/ConfigProvider.js

**Comment by landryb** [comment]
oops, badclick, didnt want to close. sigh.

**Comment by landryb** [comment]
there's some user-level documentation in https://github.com/geosolutions-it/MapStore2/blob/master/docs/user-guide/background.md which is available in the user guide at https://mapstore.readthedocs.io/en/latest/user-guide/background/ - but that's not the 'documentation for site admins' :)

**Comment by offtherailz** [comment]
Hi @landryb The documentation is a little implicit in that point, I opened this issue to improve it. https://github.com/geosolutions-it/MapStore2/issues/5055

About background configuration: 
In MapStore every map has it's own background list saved within the map. So you can configure **initial background list** by editing the new.json layers (that are the initial layers of a map without context) or edit the backgrounds in the map section of the context configuration wizard, via UI, to configure the backgrounds of a specific context. 

How to configure background layers in new.json is explained here (depending on the type) 
https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/#layer-types

**Comment by tdipisa** [comment]
@catmorales 
we have today improved the [georchestra documentation](https://docs.georchestra.geo-solutions.it/en/latest/configuration/index.html) with more information on how to configure the MS data directory

**Comment by catmorales** [comment]
> Only localConfig.json can be loaded from the datadir is at the moment.
 
Therefore, for the moment, it is not easy for me to customize map's configuration  because we use the latest docker image of mapstore for georchestra and i have no access to the container which is managed by camptocamp.

Can you tell me when it will be planned to externalize in georchestra's datadir the 2 configuration files new.json and config.json ?

**Comment by tdipisa** [comment]
@catmorales 
I've opened this issue [here](https://github.com/georchestra/mapstore2-georchestra/issues/221). As I told you in the status meeting today, we will take care of this after the other pending issues that we are working on.

**Comment by catmorales** [comment]
Yes thank you, it's very important for us to have the ability to customize our platforms.

**Comment by tdipisa** [comment]
@catmorale, we can close this issue, right? If needed a new one can be opened I think.

**Comment by catmorales** [comment]
yes sure !
