### ISSUE TITLE
Extension Manager - Extension upload UI

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#17]
The MapStore UI needs to provide an utility that allows the administrator the possibility to upload an extension package. 
- A simple UI must be provided with the possibility to select a local archive (the extension package) and provide feedbacks during the upload process: a spinner inform the user that the upload is in progress. Evaluate the possibility to have a progress bar to check the state of the upload process
- Only one extension package at time can be uploaded

**Comment by ElenaGallo** [comment]
@mbarto trying to upload this [zip file](https://github.com/georchestra/mapstore2-georchestra/files/4298201/plugin.-.no.file.zip), without the JScript file, no modal window appears to inform about the missing file and is added to the list of available plugins

**Comment by tdipisa** [comment]
@mbarto I've also opened the issue #197 for a review of the UI then we have already opened #150 that need to be completed to have a fully working installation tool.

**Comment by ElenaGallo** [comment]
@mbarto the plugin does not contain all the translation file available on MS but no modal window appears to inform about the missing file and is added to the list of available plugins causing an error on MS :
`https://dev.mapstore2.geo-solutions.it/mapstore/dist/extensions/My/translations/data.en-US.json`

**Comment by tdipisa** [comment]
In my opinion we should make MS more resilient: if a translation is missing simply MS will ingnore it.

From @mbarto [here](https://github.com/geosolutions-it/MapStore2/issues/5047#issuecomment-603692868)
>@tdipisa I would fix this one by making the translations loader more resilient, when you have multiple translations locations (main, project, extensions) it should block only if the translations is missing in the first location, the other ones should be optional.
I would reopen this issue to provide this fix, or open a new one, as you prefer

**Comment by mbarto** [comment]
- [x] translations loader more resilient, https://github.com/geosolutions-it/MapStore2/pull/5120
