### ISSUE TITLE
can't edit existing context with firefox

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#170]
on latest master with firefox 71.0, no issue creating a new context, but trying to edit an existing context (url shows https://georchestra.geo-solutions.it/mapstore/#/admin/context-creator/133)  just shows a blank area below the georchestra header - no msgs in browser console. From what i can see it works in chrome.

**Comment by landryb** [comment]
actually, same thing with chrome 79, still on the provided demo logged in as testadmin - so not a local issue. clicking the edit button on the map list loads then shows a  blank area.

**Comment by tdipisa** [comment]
Hi @landryb, I have Chrome **80.0.3987.100** and Firefox **73.0** and the context editing works fine for me. Can you please specify the extact step to reproduce the issue that you have identified by speficying also a sample of existing context in our dev iinstance?

**Comment by landryb** [comment]
firefox 73.0 on OpenBSD
* go to https://georchestra.geo-solutions.it/mapstore/,
* click login
* login as testadmin/testadmin
* get redirected to https://georchestra.geo-solutions.it/mapstore/#/
* append /admin/ to the url to get to the context list
* click on any context 'edit' icon -> white area below the georchestra header
* urlbar shows  'https://georchestra.geo-solutions.it/mapstore/#/admin/context-creator/133'.

same thing with a new empty firefox profile, same thing on my own install of master, and my reports from yesterday were with chrome 79 & ffx 71 on windows 7.

If i try on my install, no hit is generated on the server so it seems something client-side.

**Comment by tdipisa** [comment]
Hi @landryb I'm sorry but honeslty I cannot replicate this issue even cleaning the browser cache, my browsers are all updated. I will ask developers for further checks and let's see. Thank you.

**Comment by landryb** [comment]
two of my colleagues on linux & windows 10 reproduce the issue on georchestra.geo-solutions.it, with firefox 72. With chrome 79 on linux it works, with chrome 79 on OpenBSD it doesnt. Is there something in the libs you use that check os/browser too aggressively wrt graphic capabilities or so ?

**Comment by tdipisa** [comment]
@landryb thank you, we will check asap

**Comment by catmorales** [comment]
I have the same problem as well o on the site of geosolutions demo as on the integrated site in our test georchestra. 
With chrome (Version 80.0.3987.132 (Build officiel) (64 bits)) and firefox (60.7.0esr (32 bits)).
I don't know if it's a track, but i tested both sites in french ...

**Comment by catmorales** [comment]
It's much better ! 
Did you apply some corrections ?

**Comment by tdipisa** [comment]
@catmorales we didn't anything different until now, we didn't apply fixes. Is that working for you now? 

@landryb 
>Is there something in the libs you use that check os/browser too aggressively wrt graphic capabilities or so ?

I don't think so but I've increased the priority of this issue and I've asked @offtherailz for a check.
He will report back asap.

**Comment by catmorales** [comment]
>Is that working for you now?

It's very strange because it was working in the afternoon and now i cant't modify nothing. 
Can we have a problem using testadmin for all the users ?

**Comment by landryb** [comment]
i havent been able to pinpoint the environment or behaviour that triggered this issue, be it browser or os or cache or locale.. and its really hard to debug since we have no message in the browser console.

**Comment by offtherailz** [comment]
The issue was due to a combination of the final slash inserted "/admin/" and a relative path added when clicking on edit. I added a fix (will be deployed in minutes) that should solve the problem

**Comment by landryb** [comment]
i suppose it was fixed by c1d4df9 which updated the submodule to pull 
geosolutions-it/MapStore2#5000 ? @ElenaGallo can you please put the reference to the fix when you close issues ?

**Comment by landryb** [comment]
can confirm that the issue is fixed here with firefox 75.0beta after updating.
