### ISSUE TITLE
Adding a layer it doesn't appears on the TOC

### ISSUE THREAD

**Issue by francoperversi** [georchestra/mapstore2-georchestra#173]
Uploading the following wmc template from the Template configuration in step 2 of context configuration process, the layer inside appears in the map but it doesn't appear on the TOC:
[public-ortho2017.zip](https://github.com/georchestra/mapstore2-georchestra/files/4219605/public-ortho2017.zip)

**Step to reproduce:**
* Open georchestra
* Login as admin
* Administration > Mapstore
* New context
* Insert name and title and click on next
* Add all the plugins 
* Templates configurations > add all the templates (be sure there's the public-ortho2017) > close
* Click on next, and save
* Find the just created context and open it
* Burger menu > Map templates
* Change map template with public-ortho2017
* Open the TOC 
* Verify that the layer is in the map but the TOC is empty

**Comment by vlt1** [comment]
The layer is not visible in TOC because it's a background, as it has isBaseLayer property set to true.

**Comment by francoperversi** [comment]
This is not an issue, closing
