### ISSUE TITLE
The position of the wizard close button should be changed. 

### ISSUE THREAD

**Issue by gitcontributor** [georchestra/mapstore2-georchestra#184]
The position of the wizard close button should be changed. A new Close button in the bottom right toolbar should be included, once clicked the same functionalities of the existing close button on top left corner of the wizard must be maintained:
![image.png](https://images.zenhubusercontent.com/5e4aa9dd9830f67cd4bd0b90/604f7b27-0cb8-4ddf-b216-b0a26aee94cc)

**Comment by offtherailz** [comment]
We have to update the localConfig.json in the application and on the server in order to merge use the updates coming from 171 (path to back location).
