### ISSUE TITLE
If no background is present, you can not add it

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#187]
Related to:

https://github.com/geosolutions-it/MapStore2/issues/4866

**Comment by ElenaGallo** [comment]
On geOrchestra the empty background added by default is not visible below certain levels, as follows:
![wmctemplate](https://user-images.githubusercontent.com/56537133/78146493-7f3b4900-7432-11ea-8a48-e3dade23b9a6.JPG)
is this an issue?

**Comment by tdipisa** [comment]
@ElenaGallo you message is not clear, please clarify it with some steps to reproduce if needed.
