### ISSUE TITLE
Application Context - Parametric viewers - Advanced - Plugins

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#20]
The base support to define/manage multiple parametric viewers has been defined. Each application context must be identified also by the following elements:

1 - List of extensions that can be activated by the administartor within the viewers: this represents the set of MS plugins that must be present in the final context's viewer and ready for the use, something like now happens in MS through localConfig

2 - List of available extensions that can be activated by the user: these extensions will not directly available in the viewer, but can be activated on the fly by the final user of the context (they will appear in the Extension Library tool, see #39) 

The configurations related to the viewer parameters in the above list changes between different application contexts and need to be properly managed, these means that the lists of extensions of activated/available extensions (point 1 and 2 above) need to be persisted in the context configuration. 

This issue involve the step n° 2, the mockup [here](https://demo.geo-solutions.it/mockups/mapstore2/geoorchestra/#/app-context/general-settings). 

Whithin this issue only the support needed for the MS code base must be implemented, that mainly means the management of the base configuration model of the context (See the format in #15 ). The UI part will be part of #22.

**Comment by offtherailz** [comment]
Current context should be saved like this:
```
{
plugins: {
   desktop: [...] // all the plugins (not selectable by the user)
}
},
userPlugins: // list of plugins that can be enabled by the user [ 
{
   "name": "BackgroundSelector", 
   "activeByDefault": true // this inidcates that the plugin should be added on startup or not
}, ...
templates: [{id: 1, /* other options of the template */}, {id: 2}] // list of available template
```
NOTE: `activeByDefault` is not present in the mock-up. We should add a checkbox in the UI, when the plugin is checked as user plugin.
Original functionality in mapsfish allows to enable by default some of them before the user selects, so this have to be ported in mapstore
