### ISSUE TITLE
[ geosolutions - demo] sharing the current map

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#201]
The link created with the share tool of the map don't include all the layers in the TOC. 
Example:
Context : https://georchestra.geo-solutions.it/mapstore/#/context/testcm3_
* i added to the current map , a map template choosen in the catalog map template "Aire de jeux Rennes" 
* I zoomed  in the "Parc du Thabor"
![image](https://user-images.githubusercontent.com/4659829/76308796-d898d800-62cb-11ea-883c-0d8a60908678.png)
 
* i shared the map and the link is created only with the basemap on the global area of the map.

**Comment by tdipisa** [comment]
@catmorales as I told you during the meeting today in MS you can share saved maps. Therefore if you open a context and you add additional contents (layers) in it, you need to save the map to share these new content: the possibility to save user maps within a context will be available soon.
