### ISSUE TITLE
[geosolutions -demo] plugins description is not visible

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#208]
Some plugins have a long description  which is not visible on the plugin manager interface and it's not posible to read the entire text.
Example:
![image](https://user-images.githubusercontent.com/4659829/77937178-407f8480-72b4-11ea-99e2-e07f5583d0e5.png)

**Comment by tdipisa** [comment]
@catmorales yes, you are right. We can show a tooltip with a complete description in it when the mouse hover over the plugin description. Is it ok for you?

**Comment by catmorales** [comment]
yes,
