### ISSUE TITLE
wmts interoperability with french national ogc services

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#213]
Trying wmts services from https://geoservices.ign.fr/documentation/geoservices/wmts.html (ex https://wxs.ign.fr/choisirgeoportail/geoportail/wmts which is freely available) - mapstore can load the service getcapabilities, but adding a layer to the map (in firefox 75) triggers a bad assertion in openlayers:
```
Object { code: 17, name: "AssertionError", message: "Assertion failed. See https://openlayers.org/en/v5.3.0/doc/errors/#17 for details.", stack: "" }
GeOrchestra.js:211:75317
Object { code: 17, name: "AssertionError", message: "Assertion failed. See https://openlayers.org/en/v5.3.0/doc/errors/#17 for details.", stack: "" }
```

and the viewer displays a huge red bad looking smiley :(

![image](https://user-images.githubusercontent.com/3421760/78347048-27baeb80-75a0-11ea-9aac-f508d3a1295f.png)

with no way to get out of it. Of course tested on the https://georchestra.geo-solutions.it/mapstore/#/ testing platform.

yet another WMTS interoperability problem ? the same WMTS works in mapfishapp.

**Comment by tdipisa** [comment]
Hi @landryb 

>Trying wmts services from https://geoservices.ign.fr/documentation/geoservices/wmts.html (ex https://wxs.ign.fr/choisirgeoportail/geoportail/wmts which is freely available) - mapstore can load the service getcapabilities, but adding a layer to the map (in firefox 75) triggers a bad assertion in openlayers:

You are right, we will investigate it asap on why this error occurs

>and the viewer displays a huge red bad looking smiley :(
with no way to get out of it. Of course tested on the https://georchestra.geo-solutions.it/mapstore/#/ testing platform.

We have recently improved this in MS master, it will be available also for geOrchestra MS soon:

![image](https://user-images.githubusercontent.com/1280027/78352735-23470080-75a9-11ea-8a22-c12d5cde414c.png)

**Comment by landryb** [comment]
retested with updated mapstore copy as of current master, still happens - there's a better 'mapstore js crash' window at least :)

**Comment by tdipisa** [comment]
@landryb I know. It is in blocked for now since we have prioritized planned activities first. We will take care of this later next days as part of the MS activities before releasing the new version.

**Comment by landryb** [comment]
Updated my local war from the artifact generated from https://github.com/georchestra/mapstore2-georchestra/actions/runs/140625631, and loading WMTS layers from https://wxs.ign.fr/choisirgeoportail/geoportail/wmts now works - thanks!

**Comment by jusabatier** [comment]
Still not work with EPSG:2154 projected map : 

"Le système de coordonnées géographiques de la carte n'est pas supporté par ce service"

**Comment by tdipisa** [comment]
@jusabatier can you please open a new issue reporting the problem and referencing also this issue? We will check then as soon as possible.
