### ISSUE TITLE
Authentication problem in georchestra dev instance

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#214]
If you try to login to the DEV geOrchestra instance the web application remains blocked.

https://georchestra.geo-solutions.it

**Comment by Gnafu** [comment]
@tdipisa please check if the issue is solved now.
The ldap service was "unhealthy" so I restarted it and then I was able to login.
The logs did not have any useful information.

**Comment by tdipisa** [comment]
It works now, thank you.
