### ISSUE TITLE
[geosolutions-demo] Impossible to create a map template without background layer

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#215]
User case :
I want to create several thematic template maps to be made available to users in an application context. 
e.g.: tree template map, game template map to be added in the list of map templates of the green spaces application.
To create them, I go to the main map of mapstore and I add the wms layers that interest me then I export the map in mapstore format. 
But i can't delete all the map backgrounds.

The consequence will be that the user will add x times the same backgrounds. It's not convenient. How should we proceed ?

**Comment by MaelREBOUX** [comment]
In a more general way we sometimes need to work without a background layer.
yesterday I needed to check datas alone and I could not find a way to disable or delete backgroud layer in my map.

Is it possible ?

**Comment by tdipisa** [comment]
@catmorales @MaelREBOUX 
The background selector allows you to remove the background layers from the map, therefore you can remove the un-needed backgrounds for the tamplate before exporting the map.

At least one background is needed for the map, we have anyway the **empty background** that you ca use if you don't need any special background for your map.

![georchestra_bg](https://user-images.githubusercontent.com/1280027/78771233-26b6ff00-7990-11ea-8c61-08f1a9597c80.jpg)

**Comment by catmorales** [comment]
Thank you @tdipisa , i think it could be the solution but I didn't see it in our configuration, i will check it

**Comment by tdipisa** [comment]
@catmorales we can close this issue now, right ?

**Comment by catmorales** [comment]
Yes, Ok i will try to integrate it in our SDI. If i have a problem i 'll reopen it
