### ISSUE TITLE
plugins.StyleEditor is SLD format including SE ?

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#217]
Hello.

Here : https://mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.StyleEditor
I read `supported formats, could be one of [ 'sld' ] or [ 'sld', 'css' ]`

Here we are using Style Encoding (SE) not SLD.

Should I unterstand that "sld' allowed format include SE format ? Meaning XML…

**Comment by tdipisa** [comment]
Hi @MaelREBOUX 
you mean **Symbology** Encoding, right?

>Here we are using Style Encoding (SE) not SLD.

What this means? How are you using it precisely? I know that you are using GeoServer so I suppose you are using SE in some way there, right?

>Should I unterstand that "sld' allowed format include SE format ? Meaning XML…

GeoServer supports (with some limitations) SLD 1.1 / SE 1.1 (i.e. styles exported from QGIS), [here ](https://docs.geoserver.org/latest/en/user/styling/qgis/index.html) is the official documentation.

As I explained this morning, the Style Editor in MapStore works on top of the GeoServer REST APIs and supports both CSS and SLD 1.0 formats for styles. Therefore, the mime type used by MapStore for his REST requests is: **application/vnd.ogc.sld+xml**.

However, as described by the GeoServer REST APIs documentation [here](https://docs.geoserver.org/stable/en/user/rest/api/styles.html#styles-format), SLD 1.1 / SE 1.1 requires a different mime type that is **application/vnd.ogc.se+xml**.

Saying that, the SLD 1.1 / SE 1.1 for styles is not widely used in GeoServer and we didn't receive feedbaks about a possible use of it,therefore the Style Editor in MapStore completelly supports SLD 1.0.

**Comment by MaelREBOUX** [comment]
> you mean Symbology Encoding, right?

Oups !
ahem... Yes !

We mainly used SE here.
See : https://github.com/sigrennesmetropole/geoserver_sld
example : https://github.com/sigrennesmetropole/geoserver_sld/blob/master/urba_docs_plui/plui_ebc.sld

If I understand : it should not work for us. I'll test next week.

**Comment by MaelREBOUX** [comment]
> I'll test next week.

In facts : I tested it this morning : it works. I'll confirm next week.

**Comment by MaelREBOUX** [comment]
I confirm that using Symbology Encoding styles works.

PUT method to GeoServer with header `Content-type:application/vnd.ogc.sld+xml` works fine.
