### ISSUE TITLE
Application Context - Parametric viewers - Advanced UI - Plugins

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#22]
A basic administration UI has been provided for the administrator to create and configure the application context that is now identified by its name and its URL.

Within the admin UI (context wizard) also the following settings must be available:

- Implement the UI to configure the list of activated extensions (the context viewer configuration)
- Implement the UI to configure the additional extensions that can be activated on the fly by the user using the viewer 

This involve the UI implementation of #20 and it is related to the step n° 2 of the mockup [here](https://demo.geo-solutions.it/mockups/mapstore2/geoorchestra/#/app-context/general-settings). 

The mockup specifies how the above settings need to be managed by the administrator:

1 - The administrator can choose which extension must be present in the viewer simply moving the related plugin item from the list on the left (available plugins ready to be activated and configured) to the list on the right (activated and configured plugins)

2 - For each item moved in the right list, the administrator can establish if the related extension must be already activated or only present in the extension library (see #39): the administrator can do that simply clicking on a specific button present in the plugin item, if clicked the extension will be only available to the final user in the Extension library tool, ready to be activated on the fly. The mockup illustrates this.

3 - There will be also the possibility to configure each extension managed within this context wizard step: the administrator should have the possibility to interact with a text area to specify the plugin configuration to override the default one (this detail has been illustrated in the mockup). Each extension moved in the right list can be configured (the plugin configuration specified here by the administrator will override the default one).

**The edited JSON must be validated: the admin cannot move forward to the step 3 if there are validation error.** Validation errors should be notified in some way within the text area to properly identify and fix them.

4 - For each plugin card in the right list an additional icon must be included with a link to the online[ plugin's documentation](https://mapstore.geo-solutions.it/mapstore/docs/api/plugins) (the link is specified in configuration) where the user can see the available configuration options:

![info_doc_plugin](https://user-images.githubusercontent.com/1280027/70816823-9ba66d80-1dd0-11ea-8a72-29d6fb84cb5d.jpg)

**This additional button is not included in the mockup.**

5 - Each plugin configuration specified in the step 2 of the wizard must be stored within  the context configuration using the configuration model chosen in #20.  

### Other useful information:
We must consider to have a way to choose the viewer map type here (OL/Leaflet/Cesium), it could be accomplished with a Map item always activated and so presnt in the right list by default where the admin can manage the map plugin configuration (@mbarto @offtherailz what is your opinion?)

### Note:
This issue should also consider the following problem, identified in [here](https://github.com/geosolutions-it/MapStore2/issues/4566#issuecomment-561233926):
- [x] Opening the share tool from burger menu in contexts, the `Show TOC` option is still present

**Comment by ElenaGallo** [comment]
@vlt1 @offtherailz The **open documentation** button (point 4 of the list above) is not aveilable now on geOrchstra. 
![issue22](https://user-images.githubusercontent.com/56537133/72255409-f10baf80-3606-11ea-936c-128eec5efa0f.JPG)

**Comment by francoperversi** [comment]
@vlt1 can we move this issue on test column? Did you solved it or is the fix still in progress?

**Comment by tdipisa** [comment]
@vlt1 please take a look at the comment [here](https://github.com/geosolutions-it/MapStore2/issues/4774).

**Comment by tdipisa** [comment]
Closed in favor of https://github.com/georchestra/mapstore2-georchestra/issues/155.
