### ISSUE TITLE
Cookies : details leads to an empty popin (error 500)

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#222]
Hello,

When loading MapStore2, user is invited to make a choice about cookies.

![image](https://user-images.githubusercontent.com/6370443/80489840-bd0f8c80-8960-11ea-82c6-743e9ecadaac.png)

but, actually, when clicking on "more details" it leadds to a blank popin which seems to get data from 
https://georchestra.geo-solutions.it/mapstore/translations/fragments/cookie/cookieDetails-fr-FR.html
This url returns Error 500.

I don't know which string is to be used in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/translations/data.fr-FR.json  ?

**Comment by mbarto** [comment]
@MaelREBOUX a bug of the deploy procedure, the popup html is not copied to the right place when the georchestra war is created

**Comment by tdipisa** [comment]
Closed with #223
