### ISSUE TITLE
Cookies : Discard choice leads to Google Search page

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#223]
Hello,

When loading MapStore2, user is invited to make a choice about cookies.

![image](https://user-images.githubusercontent.com/6370443/80490515-c1887500-8961-11ea-84f5-ae77052e4bf5.png)

When clicking on "Quitter" / "Discard" one is redirected to the Google Search page.

@catmorales @landryb @jusabatier
Which website would be better ? www.georchestra.org ? Qwant ?

**Comment by landryb** [comment]
definitely not google search. I'd say redirect to a configurable url, which site admins would configure to point to their rgpd page (i suppose that's the link for 'more details') or the sdi homepage....

**Comment by mbarto** [comment]
@MaelREBOUX @landryb well, it looks like the default configuration for the cookies plugin is a little bit  weird. The url is configurable using a property of the plugin itself, so we should be able to change the default georchestra configuration to something of your choice.

**Comment by MaelREBOUX** [comment]
> it looks like the default configuration for the cookies plugin is a little bit weird

Yes : I found https://github.com/geosolutions-it/MapStore2/blob/master/web/client/translations/data.fr-FR.json#L139-143 and https://github.com/geosolutions-it/MapStore2/blob/master/web/client/translations/data.fr-FR.json#L252-L255
It seems duplicated.

I think we need 2 new options in the config file to point to specific website :
* More info -> a web page  in https://docs.georchestra.geo-solutions.it/en/latest/mapstore/index.html
* Discard -> by default the SDI homepage
