### ISSUE TITLE
[3D] DEM for the testing platform

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#225]
Hi @tdipisa 

Below an url to download a GeoTIFF pyramid made with our DEM 2 m version.
https://public.sig.rennesmetropole.fr/ressources/donnees/referentiels/altitude/mnt/mnt_0200_cc48_pyramid.zip

I could put it in a GeoServer 2.12 with the DDS 2.14 plugin.
It is correctly serve by GeoServer as WMS by I have no solution to make further test today.

Poke me if you want me to publish it on the test platform after you install the data on the server.

**Comment by landryb** [comment]
and if you want more DEM to test with, there's a bunch for our region/cities here: ftp://opendata.craig.fr/opendata/mnt/ (metadatas on https://ids.craig.fr/geocat/srv/fre/catalog.search#/search?facet.q=inspireThemeURI%2Fhttp%253A%252F%252Frdfdata.eionet.europa.eu%252Finspirethemes%252Fthemes%252F10%26keyword%2FOpen%2520Data&resultType=details&sortBy=relevance&fast=index&_content_type=json&from=1&to=20)
