### ISSUE TITLE
[ Installation ] Database missing entry

### ISSUE THREAD

**Issue by pierrejego** [georchestra/mapstore2-georchestra#226]
Hello,
I tried to install Mapstore2, everything seemed to be ok during install, but when I tried to create a new context via mapstore/#/admin, I got an error. ( Sorry I did not saved it)

I solved it by adding  

`insert into geostore.gs_category (id, name) values (5, 'CONTEXT');` 
in to https://github.com/georchestra/mapstore2-georchestra/blob/master/database/002_create_schema_postgres.sql#L209

**Comment by catmorales** [comment]
@tdipisa could you confirm  and correct the documentation ?

**Comment by catmorales** [comment]
In our database we have 
"1"	"MAP"
"2"	"THUMBNAIL"
"3"	"DETAILS"
"4"	"DASHBOARD"
"5"	"GEOSTORY"
"6"	"CONTEXT"

**Comment by catmorales** [comment]
I can't store map templates. Is it the same problem ?

**Comment by landryb** [comment]
from my understanding of the code, those should come from https://github.com/geosolutions-it/MapStore2/blob/master/project/standard/templates/web/src/main/resources/sample_categories.xml (or https://github.com/georchestra/mapstore2-georchestra/blob/master/web/src/main/resources/sample_categories.xml in the 'georchestra project'), pointed at  by `geostoreInitializer.categoryListInitFile`

i think i saw a similar issue when upgrading a mapstore war with a database previously populated from an older mapstore war...

**Comment by landryb** [comment]
`context` was added in https://github.com/georchestra/mapstore2-georchestra/commit/28d17d9c3939e7911bd1c417ec7e3c1a69fc01a3

**Comment by mbarto** [comment]
@landryb that's correct, actually the database is not automatically migrated when some basic stuff (like categories) are added

**Comment by landryb** [comment]
technically, properly handling databases migrations is imo an issue, no ? unless the schema/values never change, but who knows..

**Comment by tdipisa** [comment]
@landryb, migration rules from one MS version to another are usually described in the dev giude [here](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20200100-to-20200200). Therefore migrations steps are always documented before a new MS release, this means that we know what reported in this issue about thes CONTEXT category, and we will update the DEV guide accordingly before releasing MS v2020.02.00. Under a milestone, during ongoing developments, situations situations like the one reported in this issue can happen. Let me know if we can close the issue, then.

**Comment by landryb** [comment]
great, fine with me as long as it's properly documented :) just sad to see its not automagic via hibernate, but im definitely no java expert so i dunno how much work it would be.
