### ISSUE TITLE
[Datadir] Allow to override default.properties values in geostore.properties

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#229]
In the Georchestra's Datadir, the logic is to get shared configuration from the root default.properties
For example database connexion infos (url, user, password, ...) or ldap (ip, port, scheme, user, ...).

For other Georchestra's application, it is possible to uncomment some of them in the application's properties file.

For example for sec-proxy : https://github.com/georchestra/datadir/blob/master/security-proxy/security-proxy.properties

If I uncomment and set line 21, I can set a different user specifically for sec-proxy : 

> pgsqlUser=secproxy

It will override the psqlUser defined in default.properties.
If it still commented, the default.properties value will be used.

Is it possible to allow the same logic for Mapstore ?

**Comment by landryb** [comment]
agreed, it would be definitely better to align the behaviour with other georchestra modules.

**Comment by mbarto** [comment]
@jusabatier @landryb not sure it is easy to implement, actually the behaviour is that there are application defaults that you can override in georchestra default.properties, while you are asking for the opposite (this is done to allow an application to start also when a datadir is not used).

In your scenario the properties in https://github.com/georchestra/datadir/blob/master/mapstore/geostore.properties should have priority over those in default.properties.

**Comment by jusabatier** [comment]
If properties defined in <module>.properties, use it, else use the ones from default.properties

**Comment by fvanderbiest** [comment]
> this is done to allow an application to start also when a datadir is not used

With geOrchestra, we assume all applications are configured with a "datadir". It is required.

**Comment by tdipisa** [comment]
@jusabatier @fvanderbiest, I've assigned this issue to @mbarto for a quick check next week to see what we can do.

**Comment by mbarto** [comment]
@jusabatier @fvanderbiest I did a quick check and you can already use the geostore.properties file to override default.properties settings with mapstore specific ones.

https://github.com/georchestra/datadir/blob/master/mapstore/geostore.properties

**Comment by jusabatier** [comment]
So is it possible to add comments like in others georchestra's modules ?
https://github.com/georchestra/datadir/blob/master/security-proxy/security-proxy.properties

In order to inform that those properties are configurable at this level.

**Comment by fvanderbiest** [comment]
> So is it possible to add comments like in others georchestra's modules ?

Good point Julien !

**Comment by catmorales** [comment]
Yes i agree with Julien . It is not easy to understand how to use config files without comments.

**Comment by tdipisa** [comment]
@mbarto, can you please add the required comments to the geostory.properties files as required here. I would also to include some new line in the doc [here](https://docs.georchestra.geo-solutions.it/en/latest/configuration/index.html)
