### ISSUE TITLE
[Geosolutions-demo] background layer by default in an application context

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#235]
In the application context https://georchestra.geo-solutions.it/mapstore/#/context/Contexts_and_maps, I set a default background different from openlayers (pvci) and after saving the context, the default background is always openlayers.

Is it a regression or a side effect of the application of user sessions ?

**Comment by tdipisa** [comment]
Dear @catmorales, as you can see in the screenshot below I'm able to see the correct background layer:

![image](https://user-images.githubusercontent.com/1280027/82332145-54f31a00-99e5-11ea-9ed8-4534a53adb77.png)

The point here is that in this context the User Session plugin has been activated. This means that if you have started a session on that context before modifying it (setting up the new background), you have to open the option menu and click on "reset the user session" to clean up the session itself and align the client to what present in the modified context.

**Comment by catmorales** [comment]
Ok thank you !

**Comment by catmorales** [comment]
Ok,  i created another context without "User Session Plugin"  : https://georchestra.geo-solutions.it/mapstore/#/context/cat_test_iframe

I created specific background layer in the map.
When i used it, it's ok.
When i reopened the application context in administrator mode to modify it , the default map is loaded not the customized map .

**Comment by tdipisa** [comment]
@catmorales inside the application context wizard I can see the same map:

![image](https://user-images.githubusercontent.com/1280027/82446628-4836fa80-9aa7-11ea-846b-85095503a7b1.png)

I didn't understand the problem, I'm sorry.

**Comment by catmorales** [comment]
Strange , i'm using chrome, il will try with firefox.
but when i edit the application context (the last one) in the wizard 
![image](https://user-images.githubusercontent.com/4659829/82448730-6f42fb80-9aaa-11ea-9fd9-743fd1cee8f3.png)
i see:
![image](https://user-images.githubusercontent.com/4659829/82448847-97325f00-9aaa-11ea-8b8e-e700a8fe5510.png)

**Comment by catmorales** [comment]
I'm logged with cmorales account.

**Comment by tdipisa** [comment]
@catmorales the local storage is not involved here, you haven't enabled the user session plugin for that context: have you done it previously?
Anyway, as you know, the application context wizard is an administrative tool, therefore the user session feature is not used inside the app context wizard step number 2 (it is only for end users if the plugin is enabled).

**Comment by catmorales** [comment]
Issue is when i 'm using cmorales account, with testadmin, there is no problem.  The issue is  that i created the application context as cmorales . So i don't understand.
The rôle of cmorales are 
![image](https://user-images.githubusercontent.com/4659829/82475391-b93cd900-9acc-11ea-9731-6fe552910fcc.png)

**Comment by tdipisa** [comment]
@catmorales, user roles are not involved in this problem. Can you share with me your credentials to do a check?

**Comment by catmorales** [comment]
>Can you share with me your credentials via mail to do a check?

i did it

**Comment by tdipisa** [comment]
Hi @catmorales, I'm logged in with your account and I've checked what you reported for the context: https://georchestra.geo-solutions.it/mapstore/#/context/cat_test_iframe

In the image below is what I'm able to see in the app context wizard:

![context_cmorales](https://user-images.githubusercontent.com/1280027/82811650-8c544180-9e91-11ea-94e4-f352fd35cc16.png)

Here below, instead, is what I see in view mode:

![contexr_cmorales_2](https://user-images.githubusercontent.com/1280027/82811680-a0983e80-9e91-11ea-9854-4f79011e2008.png)

One question: did you previously enable the User Session plugin for this context?

I'm just trying to figure out what happened your side, but there's nothing strange here as far as I can see.
Can you please open the chrome dev tool and do a screenshot of the Application section by selecting the Local Storage of the demo instance first? Something like this:

![image](https://user-images.githubusercontent.com/1280027/82811927-2fa55680-9e92-11ea-958c-cdabac609414.png)

**Comment by catmorales** [comment]
Ok i just tested it.
loggued as cmorales
In view mode it's ok (like you)
In the app context wizard it-s not OK and i have 
![image](https://user-images.githubusercontent.com/4659829/82815899-6c754b80-9e9a-11ea-8438-e3cde244801d.png)

**Comment by catmorales** [comment]
>One question: did you previously enable the User Session plugin for this context?

No i did a new application context without this plugin.

**Comment by catmorales** [comment]
But i can try a new one if it's necessary.

**Comment by tdipisa** [comment]
> But i can try a new one if it's necessary.

No, it isn't necessary

Can you please send me also a screenshot of your app context wizard of this context? Thank you

**Comment by catmorales** [comment]
![image](https://user-images.githubusercontent.com/4659829/82817097-a6475180-9e9c-11ea-87dd-a274880f7e42.png)

![image](https://user-images.githubusercontent.com/4659829/82817153-c70fa700-9e9c-11ea-99bb-0405b173510f.png)

**Comment by tdipisa** [comment]
I think this may depends by something dirty in your local storage, during past weeks we did a lot of updates on the demo instance and therefore something can be inconsistent. Anyway BEFORE cleaning up entirely your local storage please, can you delete only the following? 

![image](https://user-images.githubusercontent.com/1280027/82818652-5453fb00-9e9f-11ea-9d8a-0c8b815e8372.png)

It should not be there since the user session plugin is not enabled for the default context (I don't have it indeed in my local storage), but it was enabled some time ago. Let see if the problem is generated by this entry in local storage.

**Comment by catmorales** [comment]
I did not reproduce this problem. It was certainly related to the state of my browser at a time t. Thank you !
