### ISSUE TITLE
[portail-test RM] Impossible to upload a map template into an application context

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#239]
**IDS :** https://portail-test.sig.rennesmetropole.fr
**map template :** 
[espace_plante.zip](https://github.com/georchestra/mapstore2-georchestra/files/4694059/espace_plante.zip)
**Connected as :** administrator with mapstore _admin role
**Browser:** Firefox Quantum 68.8.0esr (32 bits), same problem with Chrome Version 83.0.4103.61 (Build officiel) (64 bits)
**Last update of the docker image "latest"** : 25 May 2020 17:36

When i want to upload a map template (map.json created with layers from the geoserver of portail-test) , i have an errror :
![image](https://user-images.githubusercontent.com/4659829/83113566-21408000-a0c8-11ea-92bc-5a15ead7729a.png)
In the browser's console  i have a 404 error
URL : https://portail-test.sig.rennesmetropole.fr/mapstore/rest/geostore/resources/

```
<!DOCTYPE html>
<!--TODO: set appropriate lang-->
<!--TODO: favicon-->
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Erreur 404</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href='/_static/bootstrap_3.0.0/css/bootstrap.min.css' rel="stylesheet" />
</head>

<body>
	

<c:choose>
    <c:when test='true'>
    <div id="go_head">
        <iframe src="/header/" style="width:100%;height:90px;border:none;overflow:none;" scrolling="no"></iframe>
    </div>
    </c:when>
</c:choose>

	<div class="container">
		<div class="page-header">
			<h1>Erreur 404</h1>
		</div>
		<p class="lead">Ressource introuvable.</p>
	</div>
</body>
</html>
```

In chrome console : 
`JAXBException occurred : Invalid UTF-8 middle byte 0x70 (at char #1581, byte #-1). Invalid UTF-8 middle byte 0x70 (at char #1581, byte #-1). `

**Comment by catmorales** [comment]
There is also 404 errors on:
* https://portail-test.sig.rennesmetropole.fr/mapstore/rest/config/load/extensions.json
* https://portail-test.sig.rennesmetropole.fr/mapstore/dist/themes/react-draft-wysiwyg.css.map

**Comment by tdipisa** [comment]
@catmorales the TEMPLATE category was missing backend side, I added it. Can you try again? It seems to me that your test instance is not yet updated to the latest one anyway: did you update it recently?

**Comment by catmorales** [comment]
yes the docker image was updated on  may 25th.

**Comment by catmorales** [comment]
We have to update it , i presume ...

**Comment by tdipisa** [comment]
@catmorales you should be anyway able to upload templates now, did you test it after my last feedback?

**Comment by catmorales** [comment]
Yes, it works ! Thank you !
Where did you add the TEMPLATE category ?

**Comment by tdipisa** [comment]
@catmorales it was missing in the DB

**Comment by catmorales** [comment]
POur éviter de nombreux teickets , Il faudrait peut être ajouter les catégories manquantes ici : https://github.com/georchestra/mapstore2-georchestra/blob/master/database/002_create_schema_postgres.sql#L206-L209

car de mon côté j'en ai beaucoup plus

**Comment by catmorales** [comment]
Sorry, in english ;) 
In order to avoid many issues you may need to add the missing categories in https://github.com/georchestra/mapstore2-georchestra/blob/master/database/002_create_schema_postgres.sql#L206-L209

**Comment by tdipisa** [comment]
@catmorales, yes we have to do that. We did Ms side at the moment.

**Comment by tdipisa** [comment]
hi @catmorales missing categories have been also committed [here](https://github.com/georchestra/mapstore2-georchestra/commit/709c10020b3ab842983f58f0caed02ffc989a0dc)

**Comment by landryb** [comment]
> hi @catmorales missing categories have been also committed [here](https://github.com/georchestra/mapstore2-georchestra/commit/709c10020b3ab842983f58f0caed02ffc989a0dc). Let me know if we can close this issue.

From my experience in georchestra and other projects (and i'm not the only one, cf #226 and this particular issue), unless you make it very explicit/loud in the logfiles, more cryptic issues like this will always happen everytime a new value is added to this table and not everyone has upgraded their database schema (last i upgraded my test instance, after fiddling 10mn with it, i just dropped the schema and its content and recreated it, because for some reason the sql scripts were failling and i didnt look further) - some people use different workflows, some use the docker thing, some ansible, some run the scripts manually, there are different copies of the script to update in various repos, etc - in the end it's error prone and fragile.

Instead, can we please get something (hibernate or smth else) that autopopulates this table based on a list of enums in the java code ? This way, this problem is solved once and for all..

**Comment by tdipisa** [comment]
This kind of things require migrations script while updating from a version of MapStore to another. We are just releasing the new MS version and [migration guidelines](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20200100-to-20200200) have been properly updated (as I also mentioned in [this comment](https://github.com/georchestra/mapstore2-georchestra/issues/226#issuecomment-627803539)).

**Comment by landryb** [comment]
sure migration notes are a solution ( and i see there are some, great ! hadnt seen them before, and i guess ppl using mapstore within georchestra wont necessarly thinkstraight away to look at *mapstore migration guidelines*.. unless we point at them from the *georchestra release notes*, poke @fvanderbiest), but those days there are tools to handle database table/column/records creation :)

**Comment by catmorales** [comment]
Hello Thank you Tobia, I saw https://github.com/georchestra/mapstore2-georchestra/commit/709c10020b3ab842983f58f0caed02ffc989a0dc

But i think it's not full . 
In my instance i see CONTEXT and GEOSTORY too.
![image](https://user-images.githubusercontent.com/4659829/84240068-bea2a780-aafd-11ea-8812-506bef74087a.png)

If it's possible to

**Comment by catmorales** [comment]
I think the proposal of @landryb could be an interesting evolution ...

**Comment by tdipisa** [comment]
@catmorales @landryb yes of course, I think it could be an interesting evolution to automate that process, but nothing that we can do in a short term. Usually that kind of contents in DB doesn't change frequently (more or less every 3-4 major releases). I will open anyway an issue in MS to keep track of this.

**Comment by offtherailz** [comment]
Added the sample_categories using with this commit  0ca02c2

**Comment by offtherailz** [comment]
with this commit 65e9cfa41f07081df483ea52f92c55e5819ae4e1 I also added the missing categories in db script. Moving this issue in test

**Comment by Gaetanbrl** [comment]
After deploy last master version ([with new doc](https://georchestra-mapstore-offtherailz.readthedocs.io/))  , i get this error (seems same) when i try to save a new map context :

![image](https://user-images.githubusercontent.com/16317988/101187792-18bb9a00-3655-11eb-95b1-a8d2d0dc32ec.png)

The `gs_category` table from postgresSQL seems to be OK - as expected by this  commit (https://github.com/georchestra/mapstore2-georchestra/commit/65e9cfa41f07081df483ea52f92c55e5819ae4e1): 

![image](https://user-images.githubusercontent.com/16317988/101187931-4ef91980-3655-11eb-9b5a-3dfa601d4fb3.png)

Did I miss something  ?

Thanks

**Comment by tdipisa** [comment]
@Gaetanbrl it is probably a matter of configuration since the request is performed to:
https://georchestra.example.org

**Comment by Gaetanbrl** [comment]
> @Gaetanbrl it is probably a matter of configuration since the request is performed to:
> https://georchestra.example.org

Indeed, this is m'y local domain name because MS was deployed locally (virtual machine) and tested from Host (georchestra.example.org is set in the Windows Host file to call VM ip address).

Where is supposed to be this missing ressource path ? Into webapp ? Thanks.

**Comment by Gaetanbrl** [comment]
@tdipisa issue #303 fix that. Thanks.
