### ISSUE TITLE
Add new.json to the "config" datadir

### ISSUE THREAD

**Issue by Gnafu** [georchestra/mapstore2-georchestra#240]
See comment: https://github.com/georchestra/datadir/pull/186#issuecomment-631461042

@tdipisa should I go ahead with this? 

After the PR, the master branch when ahead (https://github.com/georchestra/datadir/tree/master/mapstore) so I need to rebase the PR.

**Comment by Gnafu** [comment]
Adding a custom new.json file (or a custom config.json) file in the datadir produced no effect.
Editing the files in the webapp folder worked.

It looks like we cannot simply add files on the datadir to override new.json or config.json

**Comment by tdipisa** [comment]
@Gnafu I think we can proceed with this, I've just asked @offtherailz to do a check on our Dev env before.

**Comment by Gnafu** [comment]
Done, both PR are updated:
https://github.com/georchestra/docker/pull/58

https://github.com/georchestra/datadir/pull/186
