### ISSUE TITLE
ESRI rest webservice

### ISSUE THREAD

**Issue by vfabry** [georchestra/mapstore2-georchestra#241]
Is-it possible load ESRI rest webservice in mapstore-georchestra ?
For instance this one : https://sig.hautsdefrance.fr/rest/transports_sraddet/MapServer/

Vincent (Géo2France)

**Comment by landryb** [comment]
dont think so, as ESRI rest is non-standard, non-OGC..

https://mapstore2.readthedocs.io/en/user_docs/developer-guide/maps-configuration/ lists the possible service types.

Imo it should be the other way round, ESRI server/endpoint providing OGC-compliant services..

**Comment by landryb** [comment]
https://groups.google.com/forum/#!searchin/mapstore-users/esri$20rest|sort:date/mapstore-users/Yqmc47i82fg/bsSrbXziAQAJ has some details.

**Comment by vfabry** [comment]
Thanks Landry.
