### ISSUE TITLE
Unable to zoom on layer

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#242]
I've installed an instance from the master branch.

When adding a layer from our catalog, I can't zoom on it.
The button is disables and I have a message saying : 

> CRS EPSG:2154 Non pris en charge pour le zoom sur la couche

Same problem trying on https://georchestra.geo-solutions.it/mapstore/#/ with a layer from Geobretagne.

Have you a solution for this problem ?

**Comment by tdipisa** [comment]
@jusabatier thank you for this, we will have a look to get back to you as soon as possible.

**Comment by jusabatier** [comment]
Yes, and I try to load layer with name "Périmètres des 12 quartiers de la Ville de Rennes"

And I also get the button to zomm on layer disabled and an error message : 

> CRS EPSG:3948) Non pris en charge pour le zoom sur la couche

**Comment by tdipisa** [comment]
Dear @jusabatier please take a look at this comment [here](https://github.com/geosolutions-it/MapStore2/pull/5736#pullrequestreview-464952512) (the first three points).
We have provided a small fix but, according to our investigation, is seems that there is something wrong in the catalog service too.

**Comment by MaelREBOUX** [comment]
Wow : I never noticed that answer from GeoNetwork :

```xml
      <ows:BoundingBox crs="urn:ogc:def:crs:::RGF93 / CC48 (EPSG:3948)">
        <ows:LowerCorner>-1.46558 47.93192</ows:LowerCorner>
        <ows:UpperCorner>-1.96327 48.30684</ows:UpperCorner>
      </ows:BoundingBox>
```

**From my point of view it is a bug of GN** because it seems that the xml fragment is produced by aggregation of :
- declaration of the CRS (/MD_Metadata/referenceSystemInfo/MD_ReferenceSystem/referenceSystemIdentifier/RS_Identifier/code/CharacterString). Here : "RGF93 / CC48 (EPSG:3948)" in conformity with legal french recommendations for INSPIRE
- the bbox coordinates exppressed in EPSG:4326 as told in the ISO-19115 specification (to verify)


For reminder, this is the row data for the extent :

```xml
      <gmd:extent>
        <gmd:EX_Extent>
          <gmd:geographicElement>
            <gmd:EX_GeographicBoundingBox>
              <gmd:westBoundLongitude>
                <gco:Decimal>-1.96327</gco:Decimal>
              </gmd:westBoundLongitude>
              <gmd:eastBoundLongitude>
                <gco:Decimal>-1.46558</gco:Decimal>
              </gmd:eastBoundLongitude>
              <gmd:southBoundLatitude>
                <gco:Decimal>47.93192</gco:Decimal>
              </gmd:southBoundLatitude>
              <gmd:northBoundLatitude>
                <gco:Decimal>48.30684</gco:Decimal>
              </gmd:northBoundLatitude>
            </gmd:EX_GeographicBoundingBox>
          </gmd:geographicElement>
        </gmd:EX_Extent>
      </gmd:extent>
```
