### ISSUE TITLE
3D Plugin

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#248]
This issue collects all the activities involved for the implementation of the 3D MS's plugin for geOrchestra.

- [x] **Enable 3D plugin:** inclusion of the 3D plugin in geOrchestra MS project

- [x]  **3D plugin config:** ability to configure the 3D plugin inside the application context wizard including the configuration properties to configure the DEM layers as terrain model directly inside the plugin instead of in the localConfig

- [x]  **Ability to configure one DEM layer:** publishing data for terrain model in GeoServer is allowed using the DDS/BIL format. MapStore supports it as terrain model (the documentation [here](https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/#special-case-the-elevation-layer)) but it is needed to improve the current configuration tier espacially to make it available in the app context wizard

- [x]  **Ability to switch in 3D mode:** ability to switch in 3D mode (if the 3D plugin has been enabled by the administrator for the app context) having the DEM layer available in the Cesium map as terrain model

**Comment by tdipisa** [comment]
@catmorales do you have a DEM layer that we can start configuring in our DEV for the 3D plugin (3rd point in the description)?

**Comment by landryb** [comment]
you can use all the DEMs you want from https://drive.opendata.craig.fr/s/opendata?path=mnt/

**Comment by landryb** [comment]
fwiw i've tried the 3d plugin on https://mapstore2.geo-solutions.it/mapstore/#/viewer/cesium/4093 and it crashes quite often/quickly ( i have webgl & all working though) :
```
Error in epic "getFeatureInfoOnFeatureInfoClick". Original error: TypeError: s.latlng is undefined
    buildRequest https://mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js?60921e742f121f0b4793:2
    M https://mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js?60921e742f121f0b4793:2
    h https://mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js?60921e742f121f0b4793:2
    _tryNext https://mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js?60921e742f121f0b4793:2
    _next https://mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js?60921e742f121f0b4793:2
    next https://mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js?60921e742f121f0b4793:2
    _subscribe https://mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js?60921e742f121f0b4793:2
    _trySubscribe https://mapstore2.geo-solutions.it/mapstore/dist/mapstore2.js?60921e742f121f0b4793:2
mapstore2.js:2:4558420
```
is it a known issue ?

originally i wanted to have a look at the dds/bil usage, and from what i saw before mapstore crashed, all the getmap requests were done using the PNG format and not the binary/bil format.. in what case the latter is used ?

i will probably give a shot at enabling bil output in mapserver, as all our DEMs are in mapserver.

**Comment by tdipisa** [comment]
@landryb 

>Error in epic "getFeatureInfoOnFeatureInfoClick".

A similar error has already been fixed in the latest version, there is still an issue while the Identify tool is enabled in **Hover** mode: we are working on this for the next minor release.

>originally i wanted to have a look at the dds/bil usage, and from what i saw before mapstore crashed, all the getmap requests were done using the PNG format and not the binary/bil format.. in what case the latter is used ?

As you can see in [this documentation](https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/#special-case-the-elevation-layer), there is the possibility to configure in MS an elevation layer using the BIL format: if that configuration is available, MS perform WMS requests using that format to show the elevation value in 2D inside the mouse position tool:

![2021_01_22_11_24_13_](https://user-images.githubusercontent.com/1280027/105479573-e74e6a80-5ca4-11eb-9721-5cb78aeb32cd.png)

and also the extrusion in 3D mode:

![2021_01_22_11_26_14_](https://user-images.githubusercontent.com/1280027/105479597-ef0e0f00-5ca4-11eb-81db-bb8e8947cd62.png)

**Comment by landryb** [comment]
> @landryb
> 
> > Error in epic "getFeatureInfoOnFeatureInfoClick".
> 
> A similar error has already been fixed in the latest version, there is still an issue while the Identify tool is enabled in **Hover** mode: we are working on this for the next minor release.

ok, however on the viewer i tested on the demo site (which i guess might be up to date ?), identify tool was in click mode. the crashes went away when i disabled the identify tool.
> 
> > originally i wanted to have a look at the dds/bil usage, and from what i saw before mapstore crashed, all the getmap requests were done using the PNG format and not the binary/bil format.. in what case the latter is used ?
> 
> As you can see in [this documentation](https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/#special-case-the-elevation-layer), there is the possibility to configure in MS an elevation layer using the BIL format: if that configuration is available, MS perform WMS requests using that format to show the elevation value in 2D inside the mouse position tool:
> 
> ![2021_01_22_11_24_13_](https://user-images.githubusercontent.com/1280027/105479573-e74e6a80-5ca4-11eb-9721-5cb78aeb32cd.png)
> 
> and also the extrusion in 3D mode:
> 
> ![2021_01_22_11_26_14_](https://user-images.githubusercontent.com/1280027/105479597-ef0e0f00-5ca4-11eb-81db-bb8e8947cd62.png)

is there a demo map/context available with those elevation layers ? so that i can look at the requests done in bil format, and try to reproduce/have the same data returned by mapserver.. i thought https://mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/2723 was supposed to show elevation data but its a wms time layer...

**Comment by tdipisa** [comment]
@landryb 

>ok, however on the viewer i tested on the demo site (which i guess might be up to date ?), identify tool was in click mode. the crashes went away when i disabled the identify tool.

As I wrote you we are working on the issue you notified here :)

>is there a demo map/context available with those elevation layers ?

No, it isn't a default configuration, therefore it is not available in our MS deploy. I will configure it next week in a context of the georchestra DEV instance
