### ISSUE TITLE
Multilingualism - Review of the basic franch translations files

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#25]
The existing french translation file need to be reviewed to check for potential typos or wrong text.

**Comment by tdipisa** [comment]
@MaelREBOUX as I mentioned during the yesterday meeting I would like you to review the [MapStore french translation file](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/translations/data.fr-FR). Please, let me know if it is possible.

**Comment by MaelREBOUX** [comment]
Sure it is. I Need to find time to do that but for 15/11/2019 it should be done.

**Comment by catmorales** [comment]
@tdipisa,  I see that @MaelREBOUX is not free, i can allow some time next week to do it. How do you want we proceed ? Editing https://github.com/geosolutions-it/MapStore2/blob/master/web/client/translations/data.fr-FR ?

I had a look on it, quickly and it seems good but I need to take more time to check all.

**Comment by tdipisa** [comment]
@catmorales, I don't know if you are familiar with Github, in that case you can do a pull request to the MS master branch with your revision on that translation file. If you prefer you can also download the file, do your revision on it and then send me the file, in that case I will take care on merging it in MS master.

**Comment by catmorales** [comment]
Hello Tobia !
Where is the french translation file ? The link above is broken.

**Comment by tdipisa** [comment]
Hi @catmorales, yes the file name has been changed when we fixed when we fixed the geOrchestra issue related to translations: the correct URL is now the following:

https://github.com/geosolutions-it/MapStore2/blob/master/web/client/translations/data.fr-FR.json

**Comment by catmorales** [comment]
We just  forked mapstore 2 into our repository  https://github.com/sigrennesmetropole, we will check data.fr-FR.json and do a pull request next week probably.

**Comment by MaelREBOUX** [comment]
work still in progress...

**Comment by MaelREBOUX** [comment]
Question to @tdipisa or @mbarto 

How to know, from my webbrowser, which string is used to display this :

![image](https://user-images.githubusercontent.com/6370443/81694826-1b109980-9462-11ea-82ba-566bfcc223db.png)

I found the **changedSettingsAlert** string but here "Fermer" and "Enregistrer" are not suitable.
Is there specifics strings for this 2 buttons or are they generic ?

**Comment by tdipisa** [comment]
https://github.com/geosolutions-it/MapStore2/blob/e27b8692443bb4af541ff823b2698d5dd4e114d8/web/client/translations/data.fr-FR.json#L86

That is related to: 

https://github.com/geosolutions-it/MapStore2/blob/e27b8692443bb4af541ff823b2698d5dd4e114d8/web/client/translations/data.en-US.json#L86

These  buttons are usually generic but probably there could be some translations about that for certain components.

Do you still need help with this?

**Comment by MaelREBOUX** [comment]
> These buttons are usually generic but probably there could be some translations about that for certain components.

Ok I'll create a specific issue.
Thanks
