### ISSUE TITLE
National WMTS with EPSG:2154 error

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#250]
Some problems have already been resolved for https://github.com/georchestra/mapstore2-georchestra/issues/213

But WMTS still not work with EPSG:2154 projected map :
"Le système de coordonnées géographiques de la carte n'est pas supporté par ce service"

Moreover, default backgrounds (OSM & OTM) are disabled in background selector with EPSG:2154. 
We have a disabled cursor when hover them. 
Tried with OSM as default starting background work well, but if I change, can't reselect it after.

**Comment by vlt1** [comment]
@jusabatier Are you sure that the layer that you are adding supports EPSG:2154? For WMTS the layer must have correctly set TileMatrixSetLink for each desired TileMatrixSet. One of the referenced TileMatrixSets must support your desired EPSG:2154 projection. I've looked through layers from [https://wxs.ign.fr/choisirgeoportail/geoportail/wmts](https://wxs.ign.fr/choisirgeoportail/geoportail/wmts) and they seem to have TileMatrixSetLink set only for EPSG:3857. @offtherailz @tdipisa please confirm.

**Comment by jusabatier** [comment]
Yes I'm sure my WMTS layers at https://opendata.agglo-lepuyenvelay.fr/geowebcache/service/wmts because I actually use them for mapfishapp which is in EPSG:2154.

Moreover, https://wxs.ign.fr/choisirgeoportail/geoportail/wmts also provide layers in Lambert 93 : https://geoservices.ign.fr/documentation/donnees-ressources-wmts.html#ressources-servies-en-wmts-en-projection-l%C3%A9gale-lambert-93

**Comment by vlt1** [comment]
@jusabatier I've just tried with [https://georchestra.geo-solutions.it/mapstore/](https://georchestra.geo-solutions.it/mapstore/) layers at [https://opendata.agglo-lepuyenvelay.fr/geowebcache/service/wmts](https://opendata.agglo-lepuyenvelay.fr/geowebcache/service/wmts) and they seem to work fine. Also, I tried layers from the second link you provided and that service ([https://wxs.ign.fr/CLEF/geoportail/wmts](https://wxs.ign.fr/CLEF/geoportail/wmts)) fails GetCapabilities request with 400 Bad Request and in response sends an exception message: "Key does not exist or has expired". Not sure what is wrong here but nevertheless, the problem that you described still does not occur.

**Comment by jusabatier** [comment]
In the link https://wxs.ign.fr/CLEF/geoportail/wmts you have to replace CLEF with a user key.

It appears that there is no WMTS with EPSG:2154 support provided with a public/demo key ("choisirgeoportail"/"pratique").

I sent a mail to IGN for asking about this.

**Comment by jusabatier** [comment]
Can you give me the referer you need for your dev/test platform ?

For example it's opendata.agglo-lepuyenvelay.fr/* for my platform.

**Comment by tdipisa** [comment]
@jusabatier our dev/test platform is deployed under

**Comment by jusabatier** [comment]
You can use this key for testing on your platform : 

https://wxs.ign.fr/jhak6dgrrqhcgd10ddyy61jn/geoportail/wmts

It provide access to a WMTS layer in EPSG:2154 for your domain.

**Comment by vlt1** [comment]
@jusabatier just used the link for the catalog you provided, layers from GetCapabilities request there exhibit the same problem I explained earlier: TileMatrixSetLink is present only for "PM" TileMatrixSet which corresponds to EPSG:3857.

**Comment by jusabatier** [comment]
I just upgrade my local mapstore to last version, and EPSG:2154 WMTS layers available at : 

https://wxs.ign.fr/jhak6dgrrqhcgd10ddyy61jn/geoportail/wmts

Seems to work well on Firefox & Chromium.

I have a problem with Brave : it replace the referer with "https://wxs.ign.fr/", but it look like it's related to Brave, not Mapstore.

As it seems to work well, I close this issue.
