### ISSUE TITLE
Encoding characters issues

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#253]
I noticed that weeks ago but it is going on threw the versions.

We have misencoded characters in several places and even in the map JSON file.

![capture_249](https://user-images.githubusercontent.com/6370443/86469890-9d1e8f80-bd3a-11ea-897a-dd5c8fa0e2a7.png)

![capture_250](https://user-images.githubusercontent.com/6370443/86469896-a0b21680-bd3a-11ea-993b-ad70db4c610a.png)

![capture_265](https://user-images.githubusercontent.com/6370443/86469956-b9bac780-bd3a-11ea-9191-10c797dd5c8f.png)

![capture_266](https://user-images.githubusercontent.com/6370443/86470149-1ddd8b80-bd3b-11ea-8caf-14b1b4301181.png)

**Comment by landryb** [comment]
probably LANG in the env for the corresponding tomcat/jetty to set UTF-8 ?

**Comment by tdipisa** [comment]
@landryb probably. We will check it asap. Thank you for reporting this @MaelREBOUX.

**Comment by MaelREBOUX** [comment]
> probably LANG in the env for the corresponding tomcat/jetty to set UTF-8 ?

ping @catmorales  and / or @fvanderbiest  ?

**Comment by MaelREBOUX** [comment]
Hum : I meet these encoding pbs both on our test portal and on the https://georchestra.geo-solutions.it

**Comment by landryb** [comment]
FWIW im seeing the issue too and afaict LANG is set to fr-FR.UTF8 via systemd unit environment, unless systemd is playing games behind my back. Tried adding `-Dfile.encoding=UTF-8` to JAVA_OPTS didnt help either.

**Comment by tdipisa** [comment]
@offtherailz we have to consider also what reported by @landryb in #281. Thank you.

**Comment by landryb** [comment]
i think i've said it earlier in a different issue but will repeat myself.. can we please have at least a link to the issue in geosolutions-it/MapStore2/ project or the commit fixing it ? I suppose its the Mapstore update that fixes it, but that is just a wild guess..

this is very annoying from a project tracking viewpoint..

**Comment by landryb** [comment]
after looking at the submodule update, my guess is on geosolutions-it/MapStore2#6064

**Comment by tdipisa** [comment]
Hi @landryb. is that one. We forgot to put a comment also here.

**Comment by landryb** [comment]
can confirm that it works fine with the war taken from https://github.com/georchestra/mapstore2-georchestra/actions/runs/343751494, a service entry with a title containing accentued letters is properly displayed, as for the 'français' placeholder in a layer title translation. Thanks !
