### ISSUE TITLE
Catalogue : Search by CSW : no preview

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#256]
The little preview image is not functionnal.

![image](https://user-images.githubusercontent.com/6370443/87157668-de74e900-c2be-11ea-9cdb-11378bed73f9.png)

Don't know why because the url return by CSW is good.

```
<dc:URI protocol="image/png">http://public.sig.rennesmetropole.fr/ressources/catalogue/apercus/espub_dech_v_broyage.png</dc:URI>
```

But the HTML code send to the browser is :

```
/mapstore/dist/MapStore2/web/client/components/catalog/img/default.jpg
```

Seems that MapStore miss to treat it.

**Comment by tdipisa** [comment]
@vlt1 we can use the following endpoint to check and reproduce what reported in the issue description:

https://public.sig.rennesmetropole.fr/geonetwork/srv/eng/csw

![image](https://user-images.githubusercontent.com/1280027/97852410-fe5d6c00-1cf6-11eb-88da-b1b7d6c6d0b6.png)

**Comment by tdipisa** [comment]
Tested on [dev](https://georchestra.geo-solutions.it/mapstore/#/context/espacesvertsderennes) with:
https://public.sig.rennesmetropole.fr/geonetwork/srv/eng/csw
and it works now.
