### ISSUE TITLE
List layers : miss a button to read the metadata (cf 3.2.3.6)

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#259]
When selecting a layer in the list of the layers we have any link to :
- read the metadata main parts
- go back to the CSW catalog (ie GeoNetwork)

![image](https://user-images.githubusercontent.com/6370443/87161414-c902bd80-c2c4-11ea-8e33-607e7b7591c9.png)

I propose to add a "MD" button here 

![image](https://user-images.githubusercontent.com/6370443/87161467-dddf5100-c2c4-11ea-993e-17db584ec8d0.png)

**From my point of view : it is not conform to the 3.2.3.6 point of the CCTP**

[1] 	Depuis la liste des couches (TOC), une action sur une de ses couches doit pouvoir afficher une fenêtre avec le contenu suivant :
●	titre
●	résumé
●	aperçu
●	but
●	généalogie
●	date de création
●	date de révision
●	lien vers le catalogue pour accéder à la fiche détaillée
[2] 	Cette extension interroge le catalogue de données paramétré par l'administrateur en lui fournissant l'url xml issue des capacités du serveur de données géographiques qui fournit la couche.

What is your opinion @catmorales  ?

**Comment by tdipisa** [comment]
@MaelREBOUX, did you configure the tool to be present in the TOC toolbar? As you can see in [this](https://georchestra.geo-solutions.it/mapstore/#/context/espacesvertsderennes) sample of context, the Layer Metadata tool is there.

![image](https://user-images.githubusercontent.com/1280027/87167746-b9d43d80-c2cd-11ea-9f5c-207be7bd2b1c.png)

The Layer Metadata tool for this context is configured in the App context wizard as reported below in the image

![2020_07_10_16_53_06_GeOrchestra](https://user-images.githubusercontent.com/1280027/87167856-e8eaaf00-c2cd-11ea-9f4b-ebb9ed8de40e.png)

The related plugin documentation can be reached from the wizard itself and it is available [here](https://mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.TOC), as part of the TOC plugin documentation.

**Comment by catmorales** [comment]
>@MaelREBOUX, did you configure the tool to be present in the TOC toolbar? As you can see in this sample of context, the Layer Metadata tool is there.

I think we did not do it.
I'll configure it .

**Comment by tdipisa** [comment]
@catmorales I think this can be closed , right?

**Comment by landryb** [comment]
fwiw, i've tested it on our pre-production instance and it works for me. Some properties are weirdly listed in the left part of the table though

![image](https://user-images.githubusercontent.com/3421760/94238714-09132d00-ff11-11ea-9802-f5a842f4d7fe.png)

**Comment by landryb** [comment]
(i mean, it works, those are minor cosmetic details)

**Comment by catmorales** [comment]
>@catmorales I think this can be closed , right?

I'm sorry but i can't test now because of the migration of our test instance of geOrchestra. Next week it will be possible.

**Comment by tdipisa** [comment]
@catmorales do you have some feedback for this?

**Comment by tdipisa** [comment]
@catmorales, for us it is working as expected. Can we close this issue?

**Comment by MaelREBOUX** [comment]
Sorry for be late.

All is fine.
