### ISSUE TITLE
Problem with context's plugins list

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#263]
Since I build the master branch and deploy it, I notice that everytime I edit a context, the plugin list is bugued : 

![image](https://user-images.githubusercontent.com/8310116/91024981-fe573680-e5f8-11ea-86cb-1b9f18e59585.png)

In the console logs, i have an error : 

> Failed to load resource: the server responded with a status of 404 () -> /mapstore/rest/config/load/extensions.json

Refresh the page make it work again, but the problem is back everytime we reopen the context for edition.

**Comment by catmorales** [comment]
Hello ! i confirm , i had the same problem on the last image deployed on portail-test.

**Comment by tdipisa** [comment]
@catmorales you notified me this problem on Jul 22 by email. If you remember I tried on your portail-test without being able to replicate the problem, then you wrote me that you were on a bad tag of the docker image. Is it still the case? We can obviously check it asap if needed.

**Comment by catmorales** [comment]
I encountered this problem again and again in July and August.

Just now, I just tried again on portail-test :
* with Mozilla Firefox Quantum 68.11.0esr --> OK
* with Chrome Version 84.0.4147.135 (Official Build) (64 bits) --> OK

Gold, 
On 27 /08/2020 I redeployed the last mapstore image and yesterday **I deleted the localConfig.json file from the datadir of my geOrchestra instance** (so it is the one from the webapp that is the authentic one, if I understood correctly).
This seems to have solved the problem and others (print plugin,...). The localConfig.json file I was using in the datadir was not up to date (see Mauro's explanations at the webinar).

@jusabatier , could you try to delete  localConfig.json from your /etc/georchestra/mapstore ?

**Comment by catmorales** [comment]
>on a bad tag of the docker image

it was an error...

**Comment by catmorales** [comment]
Currently our georchestra datadir contains only the following files :

![image](https://user-images.githubusercontent.com/4659829/92007350-1c820c80-ed46-11ea-8a5b-9e34c1ead6d3.png)

**Comment by jusabatier** [comment]
Re-compiling and redeploying this morning seems to solve the problem.

I'm a bit confusing with the delete of localConfig.json as we define some options like proxy, API keys, catalogs, etc.. in it.
The localConfig.json not seems related to this issue, but I think it's actually difficult to follow evolution of this file.

**Comment by catmorales** [comment]
>but I think it's actually difficult to follow evolution of this file

Yes i agree.
@tdipisa As I said above I deleted the configLocal.json file from georchestra's datadir on the portal-test instance so I assume it uses the default settings present in the docker mapstore image.
 However, the parameters I made there (notably the catalog settings to the wmts services of the standalone geowebcache) are still present in the interface.
Of course, I emptied the browser cache, cookies, ... and restarted the docker image.
Is there a cache in mapstore?

**Comment by offtherailz** [comment]
@jusabatier the list of plugins you see is the one of the tutorial. 
It looks similar to a bug that has been solved during development, so probably your update could have fix the issue. 
I tried to browse a lot the contexts and I wasn't able to replicate the problem. If you replicate this problem again, please report in detail all the passages to reproduce it.

@catmorales the catalog list is stored also in `config.json` (the start-up map, as it is saved and can be saved in all maps). So you may have this configuration left in `config.json` file (in the app or in data dir), please take a look.

Moreover, the catalogs could be saved if you have the user session plugin active  in your context, but if you clean up the browser's cache, the user session should be cleaned with it.

**Comment by catmorales** [comment]
Thank you so much @offtherailz ! 
I saw at the end of config.json :)
```
"catalogServices":{
      "services":{
         "local":{
            "url":"/geonetwork/srv/fre/csw",
            "type":"csw",
            "title":"le catalogue local",
            "autoload":true
         },
         "localgs":{
            "url":"/geoserver/ows",
            "type":"wms",
            "title":"le geoserver local",
            "autoload":true
         },
         "localgwc":{
            "url":"/geowebcache/service/wmts",
            "type":"wmts",
            "title":"le geowebcache local",
            "autoload":true

....
```
I understand better now.

**Comment by jusabatier** [comment]
I close this issue and open one related with config files.
