### ISSUE TITLE
Impossible to add MapTemplate plugin  to localConfig.json

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#264]
This issue has been notified to @tdipisa and generate an issue on https://github.com/geosolutions-it/MapStore2/issues/5564.
I had it here just for memory because it's important for our use of mapstore.

**Comment by catmorales** [comment]
Could you please, list here all the plugins that can't be loaded in localConfig.json ?

**Comment by landryb** [comment]
i think the mapstore2 submodule should be updated to benefit from the merge of geosolutions-it/MapStore2#5711 @offtherailz  - maybe that should fix the issue for @catmorales ?

**Comment by tdipisa** [comment]
@offtherailz now, after the latest upadate, we should be able to enable the MapTemplate plugin in the default context of geOrchestra, you can proceed please. Please check to enable also Save and MapCatalog tools in the default context.

**Comment by offtherailz** [comment]
I'm going to the enable the **MapCatalog**, **Save** and **SaveAs** plugins by default (save, save as is present only for logged user, not logged user can anyway export/import their map using files).
About the **MapTemplate**, you need to configure it manually after you uploaded some templates, to set the list of allowed templates for the default map. (as you do for other contexts using the user interface, but this needs to be configured manually, at the moment).

To do this you need to do something like this in the` localConfig.json --> plugins --> desktop:`
```
{
              "name": "MapTemplates",
              "cfg":{
                "allowedTemplates": [{"id": 678}]
              }
            },
```
`allowedTemplates` array contains the list of allowed templates. 
To get the list of available IDs to put in this configuration (that you uploaded in using the context UI) you need to login as admin on your geOrchestra instance and open the following URL of the rest interface (replace `https://georchestra.geo-solutions.it/` with your own instance).

https://georchestra.geo-solutions.it/mapstore/rest/geostore/extjs/search/category/TEMPLATE/***/thumbnail,details,featured?start=0&limit=10000&includeAttributes=true

The result will return the list of templates, with the related titles.

**Comment by catmorales** [comment]
OK thank you @offtherailz  ! I'll try to configure it Asap !

**Comment by catmorales** [comment]
I have to update the docker image before i presume ? Is the docker image "latest" up to date ?

**Comment by offtherailz** [comment]
Yes, @catmorales, it is the 'latest'

**Comment by catmorales** [comment]
>The result will return the list of templates, with the related titles.

Yeahh !! it's operationnal !
![image](https://user-images.githubusercontent.com/4659829/93907978-5a979e00-fcfe-11ea-8794-87371fad2d4c.png)

 Thank you @offtherailz . 
We can close this issue
