### ISSUE TITLE
WMTS base layers can't be printed 

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#265]
For testing you can use https://georchestra.geo-solutions.it/mapstore/#/context/RM_demo_public/3308
![image](https://user-images.githubusercontent.com/4659829/91199508-4318c580-e6fe-11ea-8522-1a587fd1f988.png)

Connected to https://github.com/geosolutions-it/MapStore2/issues/5292

**Comment by landryb** [comment]
@offtherailz is it planned to update the Mapstore2 submodule here to include geosolutions-it/Mapstore2#5953 ?

**Comment by offtherailz** [comment]
Yes, we applied some more improvements on print WMTS/TMS, we are going to update the sub-module as well as we have finished our internal tests on them

**Comment by landryb** [comment]
Tested working fine on master, tried with a WMTS layer (https://osm.geobretagne.fr/gwc01/service/wmts?layer=osm:bing) is correctly present in the exported PDF. Great !
