### ISSUE TITLE
Context edition bug (map)

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#267]
I upgraded mapstore from master this morning and redeploy it.

Now I have a bug when editing an existing context, when I click on next to go to the map step, i get : 

![image](https://user-images.githubusercontent.com/8310116/92095671-3d923e00-edd6-11ea-8ce0-a9bff5a1ccce.png)

In console I have : 

> TypeError: can't redefine non-configurable property "default"
>     node_modules terrestris/base-util/dist/Logger.js/o<@https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     node_modules terrestris/base-util/dist/Logger.js/i<@https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     node_modules terrestris/base-util/dist/Logger.js@https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     o https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     node_modules terrestris/ol-util/dist/MapUtil/MapUtil.js@https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     o https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     js https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:92
>     o https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     js https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     o https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     jsx https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     o https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     js https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     o https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     o https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     exports https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     f https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     value https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:1
>     bi https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     Aa https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     Ls https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     tl https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     $s https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     zs https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     Bo https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     unstable_runWithPriority https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:287
>     No https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     Bo https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     Uo https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     Ys https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
>     _n https://geoportail.lepuyenvelay.fr/mapstore/dist/GeOrchestra.js?726d7702819791ef7664:218
> GeOrchestra.js:218:75317

**Comment by jusabatier** [comment]
I still have the same error always we try to load a map and it make mapstore unusable.

**Comment by tdipisa** [comment]
@jusabatier thank you for reporting this. Anyway, for the moment the mapstore2-georchestra project is still using the latest stable branch of MS as you can see. We still have to update/test it to latest updates provided in MS after the release we did in June on this repo. We will keep you informed as soon as it is done, we will have to update it soon.

**Comment by jusabatier** [comment]
Ok thanks, maybe it can be usefull to have a stable branch/release ?

So we can revert to it when master branch is broken.

**Comment by jusabatier** [comment]
@tdipisa I realise you mentioned a release in June, do you have a war of this release ?

If yes, can you send me this war or some functional one by mail ? 
Actually we can't use mapstore because of the bug I mentioned upper and it's very embarrassing.

**Comment by tdipisa** [comment]
Hi @jusabatier why you need the MS war file for geOrchestra? You should build this MS project that, as you can see is already using to the MS stable branch of 3 months ago.

![image](https://user-images.githubusercontent.com/1280027/92460109-db677d80-f1c7-11ea-9c84-0073363cd4f3.png)

**Comment by tdipisa** [comment]
> Ok thanks, maybe it can be usefull to have a stable branch/release ?
> 
> So we can revert to it when master branch is broken.

Sure, I will discuss with the team to provide that.

**Comment by jusabatier** [comment]
Don't know why but using the war from : https://github.com/georchestra/mapstore2-georchestra/actions/runs/204017907
It work well.

But when I clone and compile from master, I get the error mentioned in this issue with the generated war.
It's strange because nothing seems to have change last month in the repo...

**Comment by tdipisa** [comment]
@jusabatier I put an high priotity pin to this issue. We will check it asap.

**Comment by landryb** [comment]
from my understanding #269 should fix it, can you confirm that @offtherailz ?

generally speaking it would be nice to always cross-reference issues from pull requests & commits to ease general bugfix tracking.. that's what you seem to do in mapstore2, that's what we do in georchestra (poke @fvanderbiest - and in my experience lots of other opensource projects do that, not only on github..) and that really really helps ;)

**Comment by tdipisa** [comment]
>from my understanding #269 should fix it, can you confirm that @offtherailz ?

@landryb yest it should fix it, we were waiting for the jenkins build. @offtherailz will follow up on this with further feedback today, just after a final check.

>generally speaking it would be nice to always cross-reference issues from pull requests & commits to ease general bugfix tracking.. that's what you seem to do in mapstore2, that's what we do in georchestra (poke @fvanderbiest - and in my experience lots of other opensource projects do that, not only on github..) and that really really helps ;)

We usually do that also for this project, we usually use Zenhub functionalities integrated with Github to connect PR to related issues. Usually we also put the number of the issue in the PR description, but probably @offtherailz forgot do do that in this case.

**Comment by offtherailz** [comment]
Yes exactly. There is an issue with `@terrestris` nested dependencies and typescript that changed, so "some" of the builds for a certain moment "may" fail. I said "some" and "may" because we noticed it happens only in certain environments, but we didn't identified the exact condition that causes this. 

We were able to replicate it by copying the exact set of dependencies ("node_modules" directory) downloaded during the build from the environment that fails to a local one and provided a fix.
In the case of geOrchestra we didn't find an environment to replicate the problem (our local instances and jenkins builds are correct). This means that we are not able to directly verify if this fix solves the problem of this issue, but the error is the same of other projects.

_So please @jusabatier , could you let us know, getting the latest master, if this fixes the issue, to confirm that we solved the problem ?_

Thank you very much.

**Comment by jusabatier** [comment]
I confirm that it solve the problem.
