### ISSUE TITLE
Config files documentation

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#268]
Is it possible to have some full examples of configuration for config.json and new.json ?

Actually the default files only show how to set layers, but it look like we have a lot more config available (catalogs, servers, ...)

What can we configure in new.json and config.json ? 

As @catmorales  suggest in https://github.com/georchestra/mapstore2-georchestra/issues/263 to delete the localConfig.json from datadir, what allow to use the default and up-to-date one. But is it possible to override only some specific values from it like CORS url, API keys, available catalogs ?

**Comment by catmorales** [comment]
I suggest having complete and commented  examples of the configuration files listed in the  webinar.
They can come from the configuration of the demo platform (without password)  and be stored on a specific subdirectory .

What do you think?

Cofiguration files listed in the webinar:

Backend (Read Only) :
<datadir>/default.properties
<datadir>/mapstore/geostore.properties
<datadir>/mapstore/proxy.properties
<datadir>/mapstore/log4j.properties
<datadir>/mapstore/printing/*

Frontend (R/O)
<datadir>/mapstore/localConfig.json
<datadir>/mapstore/config.json
<datadir>/mapstore/new.json
<datadir>/mapstore/pluginsConfig.json

Frontend (R/W) --> other volume
<dynamic>/pluginsConfig.json.patch
<dynamic>/extensions.json
<dynamic>/dist/plugin/plugin.js
<dynamic>/dist/plugin/.../it-IT.json
<dynamic>/dist/plugin/.../en-US.json
<dynamic>/dist/plugin/.../fr-FR.json

**Comment by offtherailz** [comment]
Hi, 
we updated the documentation about the [configuration section ](url)on MapStore during this week. The information you are looking for are all in the MapStore documentation, but with a different organization (MapStore doesn't have/need the data-dir)
Let's see if it is enough or if you need to duplicate this information in your documentation. Anyway most of the information are here, so I link them to this issue, to keep track of them

**I updated this section about all configurations for back-end or front end:** 
https://mapstore.readthedocs.io/en/latest/developer-guide/configuration-files/
**Here about data dir and custom configuration (your use case) and patch files**:
https://mapstore.readthedocs.io/en/latest/developer-guide/externalized-configuration/
**extensions and plugin...**
https://mapstore.readthedocs.io/en/latest/developer-guide/extensions/#distributing-your-extension-as-an-uploadable-module
**... with linked the format of index.json, that is the same forpluginsConfig.json**
https://mapstore.readthedocs.io/en/latest/developer-guide/context-editor-config/

**Comment by tdipisa** [comment]
@catmorales we can put a dedicated configuration section in your read the doc by including all needed references to the MapStore online doc with further info if needed.

**Comment by landryb** [comment]
https://github.com/geosolutions-it/MapStore2/blob/master/docs/developer-guide/local-config.md has some commented out values. Not sure if relevant..

**Comment by landryb** [comment]
> Hi,
> we updated the documentation about the [configuration section ](url)on MapStore during this week. The information you are looking for are all in the MapStore documentation, but with a different organization (MapStore doesn't have/need the data-dir)
> Let's see if it is enough or if you need to duplicate this information in your documentation. Anyway most of the information are here, so I link them to this issue, to keep track of them
> 
> **I updated this section about all configurations for back-end or front end:**
> https://mapstore.readthedocs.io/en/latest/developer-guide/configuration-files/
> **Here about data dir and custom configuration (your use case) and patch files**:
> https://mapstore.readthedocs.io/en/latest/developer-guide/externalized-configuration/
> **extensions and plugin...**
> https://mapstore.readthedocs.io/en/latest/developer-guide/extensions/#distributing-your-extension-as-an-uploadable-module
> **... with linked the format of index.json, that is the same for pluginsConfig.json**
> https://mapstore.readthedocs.io/en/latest/developer-guide/context-editor-config/

After having a look, that really looks *better* than what we had before ! Maybe this list of urls/pointers should be on https://docs.georchestra.geo-solutions.it/en/latest/mapstore/index.html ? remember that ppl will want a single point of entry for the various docs.. clearly separating mapstore-specific config and mapstore-integration-in-georchestra-specific config..

**Comment by catmorales** [comment]
Sorry i forgot to add the last part 
5- Plugins configuration 
An explanation where to add the plugin configuration (in the plugin into the context manager) and the link to https://mapstore.geo-solutions.it/mapstore/docs/api/plugins

**Comment by catmorales** [comment]
i updated https://github.com/georchestra/mapstore2-georchestra/issues/268#issuecomment-692803321

**Comment by landryb** [comment]
as for 'the link to download them' i think it should mention that `config.json`, `new.json`, `localConfig.json` and `pluginsConfig.json` are all shipped in the root of the WAR (like most other georchestra modules), with their content matching the version of the webapp.

It is only a problem because we want those default files in the georchestra datadir repo for discoverability (cf georchestra/datadir#186) and over time commits will happen to those files in mapstore2-georchestra repo, without being merged back to the datadir repo. That's part of the integration work.....

**Comment by lpasquali** [comment]
it looks like more understandable, thanks

**Comment by tdipisa** [comment]
The reviewed doc is available online here:
http://docs.georchestra.geo-solutions.it/en/latest/

**Comment by tdipisa** [comment]
@catmorales did you check the last changes we provided in the documentation?

**Comment by tdipisa** [comment]
@catmorales do you have some updates? Can we close this issue?

**Comment by catmorales** [comment]
yes you can close it. thank you.
