### ISSUE TITLE
Layer List (TOC) - TOC state support

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#27]
A Table Of Contents can be provided inside a viewer in order to manage map layers. The TOC is considered as an extension and for this reason can be loaded/activated within a viewer in the same way of other extensions.

Within this issue, we need to take into account that some plugins are connected to the TOC, therefore they need to be properly managed: all extensions connected to the TOC are well organized in the UI within the same UI block/card (see the image below) so they can be identified.

![image](https://user-images.githubusercontent.com/1280027/71104574-4eedd880-21bc-11ea-9e62-fa83f82da718.png)

Once the administrator add the TOC to the list of enabled plugins, all sub-plugins are enabled too:

![image](https://user-images.githubusercontent.com/1280027/71104880-d0de0180-21bc-11ea-999e-3ff04e1ddbea.png)

The administrator can configure sub-plugins in the same way of the other extensions (see #22) or exclude some of them through a checkbox (in that case the extension will not be included and the related button in the TOC toolbar not present).

![image](https://user-images.githubusercontent.com/1280027/71105166-582b7500-21bd-11ea-8953-72b22be57d59.png)

**Comment by francoperversi** [comment]
Some problems noticed about this issue are reported in the comments of [this issue](https://github.com/geosolutions-it/MapStore2/issues/4774). Closing
