### ISSUE TITLE
Final review of the RtD documentation

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#275]
A final review of the read the doc online documentation must be provided to keep it aligned with the current state of the art.

These sections need to be reviewed too:

- [x] https://georchestra-mapstore-offtherailz.readthedocs.io/en/configuration_doc/developer/georchestra_integration/index.html#mapstore-integration-in-georchestra

- [x] https://georchestra-mapstore-offtherailz.readthedocs.io/en/configuration_doc/developer/user_session/index.html

**Comment by tdipisa** [comment]
As soon as PRs reported in issue https://github.com/georchestra/mapstore2-georchestra/issues/278 are merged, we will proceed with a final review of the whole documentation.

**Comment by tdipisa** [comment]
The reviewed doc is available online here:
http://docs.georchestra.geo-solutions.it/en/latest/

**Comment by tdipisa** [comment]
@catmorales did you check the last changes we provided in the documentation?

**Comment by catmorales** [comment]
I saw quickly but i didn't have time to check it really.
I will schedule a time for this.

**Comment by tdipisa** [comment]
@catmorales do you have some updates? Can we close this issue?

**Comment by MaelREBOUX** [comment]
poke @jusabatier @landryb  ?

**Comment by landryb** [comment]
since now its deployed here in dev, preprod & prod i figured out over time what was needed bit by bit. A better review would be from someone new to mapstore deployment to see if its clear enough...@fvanderbiest ?

i've had a quick look and most of the sections correctly point at the right mapstore doc when its not different from the standalone mapstore. As for the doc itself, this looks fine to me.

**Comment by Gaetanbrl** [comment]
> A better review would be from someone new to mapstore deployment to see if its clear enough

After a new MapStore deployment, we get some troubles with database and datadir config (see reference above).

Concerning the doc :

- It could be more clear to distinct docker install and "no docker" install (e.g [Setup Database part](https://georchestra-mapstore-offtherailz.readthedocs.io/en/configuration_doc/developer/georchestra_integration/index.html#setup-database)).

- More instructions about database could be nice (e.g : command to create schema, grant, ...).

- Ambiguity between doc instructions and datadir
[Setup Database part](https://georchestra-mapstore-offtherailz.readthedocs.io/en/configuration_doc/developer/georchestra_integration/index.html#setup-database) contain a  "geostore" schema name but datadir contain "mapstore" or others DB infos (to adapt indeed). 
But when we follow the doc about `config/mapstore/geostore-datasource-ovr.properties` file, we don't know if we need to replace default datadir file by this doc file.


For the reste, it's more clear (e.g header setup), thanks for this work !

**Comment by tdipisa** [comment]
@Gaetanbrl you are using a wrong documentation link. The correct one is this:
https://docs.georchestra.geo-solutions.it/en/latest/index.html

Please let me know if this is enough to help you.

**Comment by Gaetanbrl** [comment]
Thanks @tdipisa, seems better.
