### ISSUE TITLE
default schema name for mapstore ddl should be changed in "mapstore"

### ISSUE THREAD

**Issue by lpasquali** [georchestra/mapstore2-georchestra#277]
hello,
the default schena name "geostore" should be changed into "mapstore" for the sql scripts below:
https://github.com/georchestra/mapstore2-georchestra/tree/master/database

because of this requested change commited here:
https://github.com/georchestra/datadir/commit/9ba3bac9bea7dfd6d3c899ee93aeaf6a049f058a

**Comment by tdipisa** [comment]
closed in favor of #273
