### ISSUE TITLE
Pending PRs to close

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#278]
This issue summarize all pending PRs to close:

- [x] 1 Still to do a PR to fix [this line](https://github.com/georchestra/datadir/blob/docker-master/mapstore/geostore.properties#L3)

- [x] 2 After the above point, pending backport PRs as per comment [here](https://github.com/georchestra/datadir/pull/186#issuecomment-697336185)

- [x] 3 Changes documented in the georchestra documentation for the Header application [here](https://docs.georchestra.geo-solutions.it/en/latest/georchestra_integration/index.html#update-header-application-index-to-link-to-mapstore) must be provided [here](https://github.com/georchestra/georchestra/blob/master/header/src/main/webapp/WEB-INF/jsp/index.jsp). 
Then commit the mapstore SQL script for the DB schema [here](https://github.com/georchestra/georchestra/tree/master/postgresql). Pending PR for both [here](https://github.com/georchestra/georchestra/pull/3058)

- [x] 4 PR to mapstore2-georchestra as per [this comment](https://github.com/georchestra/docker/pull/58#discussion_r493335942) (to check if geosolutions can do that)

- [x] 5 Update and close the PR for the docker stack [here](https://github.com/georchestra/docker/pull/58)

**Comment by landryb** [comment]
there was georchestra/georchestra#3058

**Comment by tdipisa** [comment]
@landryb it seems to be missing in the version we are using for our DEV. Probably we will have to backport it.

**Comment by landryb** [comment]
yes it's missing since it was never merged, as still in draft state.. but that could be a starting point :)

**Comment by tdipisa** [comment]
@landryb I'm sorry 
I didn't notice the draft mode, looking into it.

**Comment by lpasquali** [comment]
all the needed modifications for header were provided here by @Gnafu in this PR: https://github.com/georchestra/georchestra/pull/3058
I just fixed a typo (and fixed the database name for the sql script, that is another subject)

**Comment by lpasquali** [comment]
This requested PR done https://github.com/georchestra/datadir/pull/194

**Comment by lpasquali** [comment]
@fvanderbiest  for your comment [here](https://github.com/georchestra/docker/pull/58#discussion_r493335942) this branch was created: https://github.com/georchestra/mapstore2-georchestra/tree/workflow_docker_build

**Comment by lpasquali** [comment]
made PR with same code for 20.0.x https://github.com/georchestra/datadir/pull/195

**Comment by lpasquali** [comment]
@tdipisa I added a number for each task:

1) made PR https://github.com/georchestra/datadir/pull/194
2) made PR https://github.com/georchestra/datadir/pull/195
2) made PR https://github.com/georchestra/datadir/pull/196
2) made PR https://github.com/georchestra/datadir/pull/197
3) waiting for this to be merged: https://github.com/georchestra/georchestra/pull/3058
4) working on this
5) asked for fixing last conflicts to @fvanderbiest  as I do not have permissions to see what is conflicting (from what I see I think some past commits may have docker/config/files from datadir).

**Comment by lpasquali** [comment]
fixed workflow for docker image, but credentials are needed to push the image: 
https://github.com/georchestra/mapstore2-georchestra/runs/1158835723?check_suite_focus=true

**Comment by lpasquali** [comment]
@fvanderbiest @landryb @tdipisa 
all PRs have been made
https://github.com/georchestra/datadir/pull/195
https://github.com/georchestra/datadir/pull/196
https://github.com/georchestra/datadir/pull/197

**Comment by fvanderbiest** [comment]
Thanks a bunch !
Minor comments to be addressed in the datadir PRs.

**Comment by lpasquali** [comment]
> Thanks a bunch !
> Minor comments to be addressed in the datadir PRs.

minor fixes done! thanks for reviewing my work.

**Comment by lpasquali** [comment]
this PR was unmergeable so closed: https://github.com/georchestra/docker/pull/58
this one is the replacing one: https://github.com/georchestra/docker/pull/69

**Comment by MaelREBOUX** [comment]
Thank you all for the work.
