### ISSUE TITLE
encoding issues in accentued strings

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#281]
Dunno if its a middleware (ie tomcat, docker, nginx, sec-proxy) issue or a mapstore issue, but something i've seen on our production system and on https://georchestra.geo-solutions.it/mapstore/#/ too

- go into a layergroup properties
- the placeholder for the 'french' translation shows 'français' (which comes from https://github.com/georchestra/mapstore2-georchestra/blob/master/localConfig.json#L221) but it is displayed wrong, as on the screenshot below:
![image](https://user-images.githubusercontent.com/3421760/94782004-ec706c80-03ca-11eb-96f4-853d82f36549.png)

i'm seeing the same thing for catalog titles, where the localConfig.json file is correctly detected as UTF-8 in my datadir, and looking at the filewith hexdump it *is* UTF-8.

![image](https://user-images.githubusercontent.com/3421760/94782419-79b3c100-03cb-11eb-909c-cfe350047198.png)

**Comment by landryb** [comment]
comparing with mapfishapp where the same kind of thing works, it seems `Content-Type` header for json is `application/json;charset=utf-8`,while for mapstore when `localConfig.json` or `data.fr-FR.json` is fetched the `Content-Type` header only has `application/json`.

**Comment by landryb** [comment]
testing the plain mapstore2 demo on https://mapstore2.geo-solutions.it/mapstore looks fine, and `Content-Type` is only `application/json` there, so something related to the fact that mapstore is a iframe under georchestra header ?

afaict both (plain mapstore, and mapstore within georchestra) seem to have the correct HTML meta headers:
```
  <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
```

**Comment by landryb** [comment]
bah, same issue as #253 it seems.

**Comment by tdipisa** [comment]
@landryb thank you for this. It seems the same of what reported in the issue #253 that is in **Ready**. I'm going to close this issue in favor of #253 and referring this issue there.
