### ISSUE TITLE
Incorrect war name in the georchestra/mapstore image 

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/mapstore2-georchestra#282]
The image currently exposes http://localhost:8080/MapStore-master/ rather than http://localhost:8080/mapstore/, as expected by the [security-proxy rules](https://github.com/georchestra/datadir/blob/a795bacecd9b6785832c0b3326a5d0b42a9491ae/security-proxy/targets-mapping.properties#L10)

**Comment by tdipisa** [comment]
@fvanderbiest thank you for reporting this. We will check asap.

**Comment by lpasquali** [comment]
hello @fvanderbiest,

I forced the war to be copied as "mapstore.war" inside the tomcat, this will assure that the URI is always the same in the uncompressed war deployed in tomcat. 
See the related PR above.

**Comment by fvanderbiest** [comment]
Thanks !
