### ISSUE TITLE
update/amend page title & project name in spinner ?

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#287]
While discussing bits of #2, some members of the PSC felt that having just *geOrchestra* in the page title (the `<title>` HTML5 value) & the title used in the loading spinner (shown when loading the page) felt 'wrong'/weird.

The mapstore2 integration in georchestra provides a new viewer, maybe we should underline the fact that it's *the viewer component of georchestra* and not *georchestra* itself. Naming of georchestra components is important, cf georchestra/georchestra#123 ;)

thoughts @fphg @fvanderbiest @pmauduit @MaelREBOUX ?

**Comment by tdipisa** [comment]
Having a long string in the loading spinner doesn't make sense in my opinion and it isn't suggested anyway: it can be simply "Loading" at this point. Changing the window title I don't think it is a problem, let us know the definitive text you want for this.

**Comment by landryb** [comment]
Sure, 'Loading' alone is fine in the spinner. Waiting for others to weight in on what name should be used in the window title ... we need some 'identity' here.

**Comment by tdipisa** [comment]
We will proceed with the two point below:

- Changing the default window title from "GeOrchestra" to "geOrchestra Viewer"
- Changing the loading spinner text from "Loading geOrchestra" to "Loading"

**Comment by landryb** [comment]
definitely ok ! I suppose both strings are under translation anyway ?

**Comment by landryb** [comment]
tested on master, looks better - thanks !
