### ISSUE TITLE
[Map template] impossible to add a new map template into an application context

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#293]
When adding a new map template in an application context, it is impossible to enter the name, image and description of the map template : impossible to enter anything in the form.
We deployed the latest image of mapstore (updated 13 days ago), we didn't have this issue before.
Only the json file can be loaded in this window.
Is this related to #291 ?

You can reproduce this issue on https:// portail-test.sig.rennesmetropole.fr with any application context

**Comment by tdipisa** [comment]
@catmorales it is an issue we currently have also on MS master branch, the one this project is using now. Therefore it is probably a regression. Before updating the the master branch of this repo to the MS master one, we have anyway created a[ stable branch here](https://github.com/georchestra/mapstore2-georchestra/tree/1.0.x) that is using the Ms stable branch.

**Comment by catmorales** [comment]
Ah OK, so do you have a docker image including the stable branch we can use instead of the [latest image](https://hub.docker.com/r/geosolutionsit/mapstore2-georchestra/tags) ?

**Comment by tdipisa** [comment]
@catmorales there isn't a docker image for the stable branch. We have created that stable branch just to freeze the previous status: new updates/fixes we did for VSR are on master branch anyway. I will check tomorrow if we can quickly fix this in MS master.

**Comment by tdipisa** [comment]
@catmorales an issue has been opened MS side for this. We will proceed with a fix tomorrow.

**Comment by tdipisa** [comment]
@catmorales we have provided a fix MS side, the PR is still in pending review. I will keep you updated as soon as we merge it and we update the MS revision here.

**Comment by landryb** [comment]
can confirm the problem here too, i can send a map template but all fields are inactive, will see if i can find time to build a war to test the PR.

**Comment by catmorales** [comment]
Thank you all. for your feedback.
@tdipisa as soon as you give me the go-ahead, I will redeploy the latest  docker image in portail-test.

**Comment by landryb** [comment]
can confirm that this is fixed by #296, at least in my basic testing.

**Comment by tdipisa** [comment]
@catmorales the MS revision has been  updated with the fix.

**Comment by tdipisa** [comment]
Thank you @landryb for testing this. It is working on our DEV too. @catmorales I'm looking forward to hearing your feedback before closing the issue.

**Comment by catmorales** [comment]
@tdipisa  did you update the docker image "latest "?

**Comment by tdipisa** [comment]
@catmorales yes, our image is automatically updated by jenkins. Also your should be updated by the github workflow automatically.

**Comment by catmorales** [comment]
OK thank you, il will check so

**Comment by catmorales** [comment]
It's ok for me too :) you can close this issue. Thank you all ! :)
