### ISSUE TITLE
Add Layer From Data Catalog - Catalog extension

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#30]
This extension must provide to the user the possibility to add layers to the TOC. Below the list of catalogs type that need to be supported:

- WFS
- WMS
- WMTS
- TMS
- GeoJSON (to clarify)

Below the needed functionalities for this tool:

- The viewer administrator can define the list of available catalogs in backoffice via configuration
- A free text search field must be provided to the user to search within the selected catalog
- The results must be listed and each of them identified by name, description and preview (thumbnail)
- Each layer belonging to the result list can be individually added to the TOC to be visible in map

**Comment by MaelREBOUX** [comment]
As said in point 3.2.2.2 and discuss yesterday we need to find layers in this kind of catalogs :
- CSW
- WMS / WFS / WMTS (getCapabilities)
- open data catalogs
- direct GeoJSON url

# open data catalogs
For open data catalogs we meet these usecases :

## OpenDataSoft catalogs

API documentation :
https://help.opendatasoft.com/apis/ods-search-v1/#dataset-catalog-apis

these request gets the 100 first dataset wich contains geo datas
https://data.rennesmetropole.fr/api/datasets/1.0/search?rows=100&features=geo
at the beginning, the nhits value gives the number of all datasets

get a dataset infos :
https://data.rennesmetropole.fr/api/datasets/1.0/circonscriptions-legislatives-communes/

get a dataset in GeoJSON
https://data.rennesmetropole.fr/explore/dataset/circonscriptions-legislatives-communes/download/?format=geojson


## CKAN catalogs

API documentation
https://docs.ckan.org/en/2.8/api/legacy-api.html


# direct JSON url

For example in this map http://umap.openstreetmap.fr/fr/map/rennes-metropole-alyce-localisation-des-prestation_198872#  we have 7 layers

if we put this url  http://umap.openstreetmap.fr/fr/datalayer/600032/  somewhere we would be able to load it into our map



Note : I don't kow how to manage / how to find TMS layers. For my opinion this could be retrieve from ISO19139 metadata if a TMS onLineResource is declared and only declared in a metadata. For us WMTS is prior to others. Have suggestions ?

**Comment by tdipisa** [comment]
@MaelREBOUX the support for CKAN and OpenDataSoft catalogs is not part of the requirements as far as I saw. WMS and WMTS are already available in MapStore as supported catalog types; WFS and TMS need to be implemented instead. The requirements report in addition GeoJSON, that is a different thing than supporting CKAN and OpenDataSoft catalogs. However, current MapStore functionalities can be obviously improved within this issue to allow importing featurtes in GeoJSON formats from a remote URL in addition to a local file (as it is now).

Can you please provide a TMS catalog of interest for you that we can use as a sample for the development of the involved Catalog tool improvements?

**Comment by offtherailz** [comment]
@MaelREBOUX do you have TMS of your interest to link, for testing purpose. Thank you

**Comment by landryb** [comment]
you can test with https://osm.geobretagne.fr/gwc01/service/tms/1.0.0 or http://tiles.craig.fr/ortho/tms/1.0.0/

**Comment by offtherailz** [comment]
Ok, thank you very much

**Comment by landryb** [comment]
dunno for osm.geobretagne.fr but for tiles.craig.fr i can add it to leaflet with a `zoomOffset` and an inverted y axis:
```
var bg2 = L.tileLayer('https://tiles.craig.fr/ortho/tms/1.0.0/ortho_2016/webmercator/{z}/{x}/{-y}.jpeg', {zoomOffset: -1})

**Comment by catmorales** [comment]
Another examples can be used with https://public.sig.rennesmetropole.fr/geowebcache/service/tms/1.0.0

**Comment by offtherailz** [comment]
thank you for the other examples. They will be very useful for testing
