### ISSUE TITLE
DB Schema seems to be not correctly init from datadir info

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#303]
After a new mapstore deployment, we get some troubles to prepare database and datadir config.
To do this, i follow [this doc](https://georchestra-mapstore-offtherailz.readthedocs.io/en/configuration_doc/developer/georchestra_integration/index.html#mapstore-integration-in-georchestra) (link with #275).

Branch : master

- **Mapstore can't create tables : hibernate_sequence does not exists**

We have to create and grant the sequence manually into postgresql database  (schema mapstore): 

```
CREATE SEQUENCE mapstore.hibernate_sequence;
GRANT USAGE, SELECT ON SEQUENCE mapstore.hibernate_sequence to georchestra;
```

Is it possible to insert this step into doc with schema / grant instructions ?

- **Hibernate - Options from `geostore-datasource-ovr.properties` file was not take into account**

This line seems to contain no variable to get the correct value from `geostore-datasource-ovr.properties` :

https://github.com/georchestra/mapstore2-georchestra/blob/c66356d4ab671e2d2a57d31adfdea55d7bb4fcef/web/src/main/resources/applicationContext.xml#L149

We have to replace `validate` by `update` into `applicationContext.xml` to create tables on webapp deploy.

To do that we replace this line :

https://github.com/georchestra/datadir/blob/4330e6ea2c63e2026fab4f65c082831108074c5b/mapstore/geostore-datasource-ovr.properties#L7

...by 

`<entry key="hibernate.hbm2ddl.auto" value="update" /> 
`

And restart tomcat.

What is the difference between `config/mapstore/geostore.properties` and `config/mapstore/geostore-datasource-ovr.properties` ?

**Comment by tdipisa** [comment]
@Gaetanbrl you are using a wrong documentation link. The correct one is this:
https://docs.georchestra.geo-solutions.it/en/latest/index.html

Please let me know if this is enough to help you.

**Comment by Gaetanbrl** [comment]
Thanks @tdipisa I close.
