### ISSUE TITLE
webpack5 - MIME type error with default SampleExtension

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#305]
According to PR #304, after update my mapstore2-georchestra (local instance) i try to import the default SampleExtension plugin imported (zip) into datadir /dist folder.

But i can't use it with context and i get MIME Type error.

**Steps to reproduce :**

1. Clone [MapstoreExtension sample](https://github.com/geosolutions-it/MapStoreExtension)
2. Create ZIP (follow README) without change any files / configs
2. With MapStore2-georchestra app, create context and upload SampleExtension.zip 
    SampleExtension folder is now available in my datadir `/etc/georchestra/mapstore/dist/extensions/SampleExtension`
3. Plugins list display SampleExtension correctly
4. Select this plugin with identifier, zoom-in, zoom-out plugins
5. Finalize context
6. Open context >> Can't visualize all plugins
7. Open browser console :
```
Refused to execute script from 'https://georchestra.example.org/mapstore/rest/config/loadasset/dist/extensions/SampleExtension/index.js' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.

```

**Comment by tdipisa** [comment]
@Gaetanbrl We have already identified this and we are workign on it now.

**Comment by offtherailz** [comment]
Work on MapStore  to fix this problem is tracked by this issue https://github.com/geosolutions-it/MapStore2/issues/632
Going to port it in the project with the new version in pom today.

**Comment by Gaetanbrl** [comment]
@offtherailz work is already in progress ?

After update mapstore2-georchestra, MapStore2 submodule, replace Tomcat war, and reproduce steps describes on top, i get the same errors : 

![image](https://user-images.githubusercontent.com/16317988/103520838-1462e680-4e78-11eb-8527-8539e713a66c.png)

**Comment by offtherailz** [comment]
Hi @Gaetanbrl . 
The issue has been solved and it is working on our test server. 
See this context https://georchestra.geo-solutions.it/mapstore/#/context/sample_extension
![image](https://user-images.githubusercontent.com/1279510/103872709-0f4ba480-50cf-11eb-90cf-8cd3a99d4d6c.png)
If you are sure about the update, it could be a server side issue. 
It is running in docker image or do you have some custom installation?

**Comment by Gaetanbrl** [comment]
Hi @offtherailz ,

> It is running in docker image or do you have some custom installation?

It's a simple install from georchesta ([ansible install](https://github.com/georchestra/ansible)) and georchestra-mapstore install from [main doc](https://github.com/georchestra/mapstore2-georchestra ) without docker.

I get this error when i save the new context with context creator. 

Then, the extension is visible into datadir (`/etc/georchestra/mapstore/dist/extensions/SampleExtension`) and context is available but empty without extension when i open it.

**Comment by Gaetanbrl** [comment]
> If you are sure about the update, your problem could be a server side issue.

I get no tomcat logs error about that (/srv/logs/mapstore.log).
I will update again to be sur (maybe reinstall again next ...).

**Comment by offtherailz** [comment]
I just updated georchestra with latest fixes and improvements from the stable branch. 
This PR also increases the version of the back-end, so it should download again a new jar for the part that implement the fix. 
You could try to build this latest version, to make sure to have the latest version (and exclude any issue with caches from maven repo or similar, just to make sure).

**Comment by Gaetanbrl** [comment]
> You could try to build this latest version, to make sure to have the latest version

Fixed after totally clear local github repo and build new .war from #309.

Thanks ! I close this issue.

![image](https://user-images.githubusercontent.com/16317988/103886415-c3562b00-50e1-11eb-94c7-03d14dac6177.png)
