### ISSUE TITLE
Impossible to reduce the window after enlarging the identify  tool

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#306]
**URL** [https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Geojardins/](https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/Geojardins/)
**Browser** : Google chromeVersion 87.0.4280.88 (Build officiel) (64 bits), Firefox 78.3.0esr (32 bits
**Issue**
* open the TOC
* select the Gestion DJB/SitesEV layer
* click on the map into an entity of this layer --> the html freemarker identify box open --> it's OK
![image](https://user-images.githubusercontent.com/4659829/102622822-dceaff00-4141-11eb-98b4-0737294a480c.png)

* click on the  "<" of the identify tool enlarge the box as expected but the ">" is not operational and  it is impossible to go back to the previous dimension and the window is blocked 

![image](https://user-images.githubusercontent.com/4659829/102623260-84683180-4142-11eb-96ff-f0502dbeaf1c.png)

**Comment by tdipisa** [comment]
Dear Catherine,

I saw in your instance you are using the following configuration for the Identify tool:

```
{
  "cfg": {
    "showHighlightFeatureButton": false,
    "draggable": false,
    "dock": true,
    "showFullscreen": true,
    "fluid": true,
    "viewerOptions": {
      "container": "{context.ReactSwipe}"
    }
  },
  "override": {
    "Toolbar": {
      "position": 11
    }
  }
}
```

Honestly I don't know where you found **draggable** and **dock**, these properties are not reported in the plugin documentation. In that case, for desktop, you have to remove the **fluid** option to make it working properly, this is a property, along with **showFullscreen**, generally used only for mobile.

**Comment by catmorales** [comment]
OK Thank you, it's much better !

draggable and dock,  properties are described in [mapstore api doc](https://mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.Identify) accessible from the link in the context manager

![image](https://user-images.githubusercontent.com/4659829/102640873-6fe46300-415b-11eb-8d27-9620ae2fb4ed.png)
