### ISSUE TITLE
Parameters config resolutions

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#314]
In the **config.json** and **new.json**, it is possible to configure **resolutions** to have appropriate scales in the map.
cf https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/#map-options

In mapfishapp we use the scales below  to define the levels to  use in the map :
[scales](https://github.com/georchestra/datadir/blob/master/mapfishapp/js/GEOR_custom.js#L238-L260)
The same  scales are also used in geowebcache to define the gridsets.
This scales permit a good interoperability between our platforms and allow us to quickly display the map on the levels thus defined in mapfishapp.

In Rennes Metropole we used as base layers all the WMTS we created with this gridsets and we don't use OSM.

**Questions**

1 -How should we calculate the resolutions to have the same scales as on mapfishapp? 
2- We are seeing slowness in the display of our backgrounds in WMTS with a re-calculation probably in a local tile cache for each level. 
Will putting the right resolutions for our gridsets in the map solve this problem?
3- Is it possible to modify an application context by overloading it with these new resolutions and in which plugin (map)? And how?

Otherwise, as soon as we have the new resolutions, we will have to add them in the new.jon and config.json.

**Comment by tdipisa** [comment]
Dear @catmorales 

>1 -How should we calculate the resolutions to have the same scales as on mapfishapp?

I think you can simply use them, just pay attention on the opposite sorting of the array

>2 - We are seeing slowness in the display of our backgrounds in WMTS with a re-calculation probably in a local tile cache for each level. Will putting the right resolutions for our gridsets in the map solve this problem?

It should be, yes. Usually the client resolutions should match the gridset ones in order to use cached tiles

>3- Is it possible to modify an application context by overloading it with these new resolutions and in which plugin (map)? And how?

At the moment it is not possible. Custom resolutions client side can be defined only as a global configuration in MapStore inside new.json and/or config.json. What you are mentioning it is anyway possible with some development, it could be an interesting improvement.

**Comment by catmorales** [comment]
>I think you can simply use them, just pay attention on the opposite sorting of the array

I tried it but it's not the same values. resolutions is a calculate value.
By the way, in your example the values 
```
         84666.66666666688,
          42333.33333333344,
          21166.66666666672,
          10583.33333333336,
          5291.66666666668,
          2645.83333333334,
          1322.91666666667,
          661.458333333335000,
          529.166666666668000,
          396.875000000001000,
          264.583333333334000,
          132.291666666667000,
          66.145833333333500,
          **39.687500000000100,**
          26.458333333333400,
          13.229166666666700,
          6.614583333333350,
          3.968750000000010,
          2.645833333333340,
          1.322916666666670,
          0.661458333333335
```
correspond to the scales :
![image](https://user-images.githubusercontent.com/4659829/104458892-40831380-55ac-11eb-97ce-8057d1dac55a.png)

**Comment by catmorales** [comment]
Ok I think we should use this:
denominator of the scale = resolution (m/px) /0.00028

0.00028 is the pixel size.
I will try

**Comment by catmorales** [comment]
Something is wrong. 
With the denominator scale of geOrchestra listed [here](https://github.com/georchestra/datadir/blob/master/mapfishapp/js/GEOR_custom.js#L238-L260) and a pixel size of 0.00028, i obtained the resolutions bellow and configured the new.json with it.
```
"mapOptions":{
		  "view": {
			"resolutions": [
				156543.033928041010838933296,
				78271.516964020490865223112,
				39135.758482010230882442552,
				19567.879241005122716305764,
				9783.939620502561358152896,
				4891.969810251280679076448,
				2445.984905125640339538224,
				1222.992452562820169769112,
				611.496226281410084884556,
				305.748113140704815064064,
				152.874056570352521221132,
				76.437028285176246405396,
				38.218514142588130305276,
				19.109257071294061601356,
				9.554628535647032576312,
				4.777314267823516288156,
				2.388657133911758144092,
				1.194328566955879072032,
				0.597164283477939536016,
				0.298582141738969712512,
				0.149291070869484911752,
				0.07464553543474240038,
				0.037322767717371200176
			]
		  }
      },
```

So, I expected to find the original scales, namely: 1:266, 1:533, 1:1066,...
And it is not the case cf image below.
![image](https://user-images.githubusercontent.com/4659829/104492701-4ee52580-55d4-11eb-8972-dc9de41e8d1e.png)


What is the problem ?
**Do you use a pixel size of 0.00028 in mapstore to list the scales in the viewer ?**

**Comment by fvanderbiest** [comment]
Reminds me of https://github.com/georchestra/georchestra/issues/736 ;-)

**Comment by catmorales** [comment]
Now , i could add in new.json and config.json the same scales as geowebcahe gridset because parameter "scales" has been added  : https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/#map-options

Thank you !
 
So it's works I have the same scales in both maps,  based on the gridset of geowebcache.
![scales_mapfishapp](https://user-images.githubusercontent.com/4659829/127520142-57311357-6728-43ed-9677-7c59fa9ca1fd.png)![scalesmapstore](https://user-images.githubusercontent.com/4659829/127520154-86db814d-1227-4af7-8b7c-500e54310e49.png)

**Comment by MaelREBOUX** [comment]
Good point !
