### ISSUE TITLE
Problem with identify popup

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#328]
I created a basic context : https://geoportail.lepuyenvelay.fr/mapstore/#/context/Piscines

And I tried to set in the Identify plugin's config the popup display mode : 

```
{
  "cfg": {
    "showInMapPopup": true,
    "disableCenterToMarker": true,
    "showHighlightFeatureButton": false,
    "viewerOptions": {
      "container": "{context.ReactSwipe}"
    }
  },
  "override": {
    "Toolbar": {
      "position": 11
    }
  }
}
```

And when click on a feature on the map, nothing happen, just a swipe of the right toolbar's buttons.
No popup is shown.

Is it a bug or maybe I don't understand how to set this configuration ?

**Comment by tdipisa** [comment]
Dear @jusabatier the configuration seems good to me, I will ask developers for a check as soon as possible.

**Comment by offtherailz** [comment]
This is the related issue on MapStore:
https://github.com/geosolutions-it/MapStore2/issues/6569
