### ISSUE TITLE
configuring 3d layer/elevation and endianness

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#331]
it's been discussed a bit in #248, i'm facing strange behaviour of the new 3d plugin, and it feels there's an inconsistency in the doc somewhere.

the elevation layer in geoserver config is documented here https://docs.geoserver.org/stable/en/user/community/dds/index.html#configuring-the-bil-format (notice how it says nasa worldwind expects the layer as little-endian) and there https://mapstore.readthedocs.io/en/latest/developer-guide/maps-configuration/#special-case-the-elevation-layer - the former says to configure the DEM layer in big endian mode, and application/bil16 data size so that values are encoded on two bytes.

according to https://en.wikipedia.org/wiki/Endianness, big endian mode would encode an elevation of 368m as hexadecimal value 0x0170 (eg 1 * 256 + 7 * 16) - accordingly, the same value encoded in little endian mode would be 0x7001.

I've looked at the code using the bil format in mapstore:
  * https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/cesium/BILTerrainProvider.js does the terrain rendering, and has a `postProcessArray` method apparently switching bytes. Looking on stackoverflow/internet, many cesium clients have a similar function.
  *  https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/ElevationUtils.js uses it for the elevation in `MousePosition` plugin, from what i can understand the bil data is read as a DataView js object, without any processing, in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/ElevationUtils.js#L37

Since a while, i have a DEM layer in mapserver, that i configured to provide BIL output (using https://worldwind.earth/elevation-server.html - but i havent found a way to specify endianness in mapserver) - for various reasons i ultimately would like to use this layer instead of one in geoserver.

If i configure this layer in mapstore, the elevation data shown by `MousePosition` is inconsistent, shows values between the ranges of [-32k:-16k] and [16k:32k] which dont make sense for elevation.

If i analyse the bil requests done by mapstore and look at the returned bil data with an hex editor, here's what i have:
```
0000000    0209    0209    0208    0208    0207    0207    0206    0206
0000010    0206    0206    0206    0206    0207    0207    0207    0207
0000020    0208    0208    0208    0209    0209    0209    0209    0209
0000030    020a    020a    020a    020a    020a    020b    020c    020d
```

this looks like valid big endian data (eg 0209 would be 2*256 + 9 = 521m, a valid elevation). `hexdump -d` confirms that:
```
0000000   00521   00521   00520   00520   00519   00519   00518   00518
0000010   00518   00518   00518   00518   00519   00519   00519   00519
0000020   00520   00520   00520   00521   00521   00521   00521   00521
```

Then, i configured a DEM layer in geoserver as explained by the mapstore/geoserver documentation, with a geotiff file containing raw elevation values, configured bil output as 16-bit big endian as expected.

`MousePosition` then displays valid elevation values, and i have nice 3d rendering on the cesium view. *But* if i look at the bil data sent by geoserver to mapstore with an hex editor, here's what i have:
```
00000e0    5001    5001    5001    5001    5001    5001    5001    5001
00000f0    5001    5001    5001    5001    5001    5001    5001    5001
0000100    5001    5001    5001    5001    5001    4f01    4f01    4f01
0000110    4f01    4f01    4f01    4f01    4f01    4f01    4f01    4f01
```
and `hexdump -d` shows:
```
00000e0   20481   20481   20481   20481   20481   20481   20481   20481
00000f0   20481   20481   20481   20481   20481   20481   20481   20481
0000100   20481   20481   20481   20481   20481   20225   20225   20225
0000110   20225   20225   20225   20225   20225   20225   20225   20225
```
even if geoserver is configured to serve the layer as big-endian this looks like little-endian encoded elevations (according to my understanding of endianness).

Finally, if i configure the same geoserver layer to output 16-bit bil as little endian, mapstore displays the same incoherent elevation values as with my mapserver layer, and the hexdump output looks big-endian encoded:
```
0000000    01c2    01c2    01c1    01bf    01be    01bd    01bc    01bb
0000010    01ba    01b9    01b9    01b8    01b8    01b7    01b4    01b3
0000020    01b3    01b3    01b3    01b3    01b0    01b0    01af    01ae
0000030    01ae    01ae    01ab    01ac    01ac    01ab    01ab    01ab
```
`hexdump -d` confirms this looks like valid elevation data, encoded as big endian:
```
0000000   00450   00450   00449   00447   00446   00445   00444   00443
0000010   00442   00441   00441   00440   00440   00439   00436   00435
0000020   00435   00435   00435   00435   00432   00432   00431   00430
0000030   00430   00430   00427   00428   00428   00427   00427   00427
```

so sure, i have a way to display 3d data in mapstore via geoserver, but it looks like there's some inconsistency somewhere either in geoserver or the doc. I looked at the DDS/BIL extension code and the endianness looks correctly handled from the config (per https://github.com/geoserver/geoserver/blob/master/src/community/dds/src/main/java/org/geoserver/wms/worldwind/BilMapResponse.java#L217) - all this is ... puzzling.

**Comment by landryb** [comment]
you might ask 'why insisting on using mapserver', to that i'd argue that:
- clients should be interoperables with servers, whatever the server :) that;s the beauty of OGC..
- i have lots of reference data already in mapserver
- i havent found an efficient way with geoserver to use distinct layers at distinct resolutions depending on the scale. Trying to build a layergroup with a 250m DEM stacked on top of a 75m DEM (with raster styles using max/min scaledenominator) miserably fails to display as BIL at runtime, since geoserver blows with `Cannot combine layers into BIL output` and ImagePyramid doesnt seem fit for the task either (from my understanding you generate the pyramid from a single high-res dataset).

**Comment by offtherailz** [comment]
Hi,
if you look at https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/ElevationUtils.js#L37, it is using [getInt16](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView/getInt16). `false` as second parameters tells to read **big endian**. This is consistent with the **big endian** setup of GeoServer. 

If you see wrong byte order analyzing you files, maybe there something wrong using hexdump ? I don't use it for a long time, so I have to refresh my memory.

I think the usage of hexdump depends on the endianess of the machine (little endian in our case). 
I downloaded 2 small bil files from GeoServer, configured in big-endian, containing no-data (-9999). 

Then I tried to use `-C` option
```
 -C      Canonical hex+ASCII display.  Display the input offset in hexadecimal, followed by sixteen space-separated, two column, hexadecimal bytes, followed by the same sixteen bytes in %_p format enclosed in ``|'' characters.
```
Here you can see the difference.

```
$ hexdump -C little.dat
00000000  f1 d8                                             |..|
00000002
$ hexdump  little.dat
0000000 d8f1                                   
0000002
$ hexdump -C big.dat
00000000  d8 f1                                             |..|
00000002
$ hexdump  big.dat
0000000 f1d8                                   
0000002
```

As you can see using -C show a different order of the bytes that is probably the one to convert (-9999 is no data).

also using `od` I have similar result
```
$ od -tx1 big2.dat
0000000 d8 f1
0000002
$ hexdump  -C  big2.dat 
00000000  d8 f1                                             |..|
00000002
$ hexdump <<< "hello"
0000000 6568 6c6c 0a6f                         
0000006
$ hexdump -C <<< "hello"
00000000  68 65 6c 6c 6f 0a                                 |hello.|
00000006
$ od -tx1 <<< "hello"
0000000 68 65 6c 6c 6f 0a
0000006
```

**Comment by landryb** [comment]
hah ! interesting, hadnt thought `hexdump` itself could mislead me this way... thanks for the cluebat.

i didnt know that `GetInt16` took an endianness param, and relooking at the `postProcessArray` method in `BILTerrainProvider.js` (which does among other things the byte swapping for BIL from BE to LE), maybe it would be 'simple' to make both BIL consumers support both types of endianness, with a parameter (`isLittleEndian` ? defaulting to false, as most ppl would use geoserver in BE mode) in the elevation layer config in `localConfig.json` telling it the byte endianness of the BIL data ?

The parameter would then just need to be used as is in the two `GetInt16` calls (https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/cesium/BILTerrainProvider.js#L88 and https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/ElevationUtils.js#L37), and this way i would be able to use/test my mapserver layers..

Sadly i dont grok much the React/Redux code style so unfortunately it doesnt seem an easy task for me...

**Comment by landryb** [comment]
Fwiw i had a quick go at it with mapstore rebuilt with this diff:
```
diff --git a/web/client/utils/ElevationUtils.js b/web/client/utils/ElevationUtils.js
index 31f928a9e..8574294af 100644
--- a/web/client/utils/ElevationUtils.js
+++ b/web/client/utils/ElevationUtils.js
@@ -34,7 +34,7 @@ const addErroredElevationTile = (error, coords, key) => {
 const getValueAtXY = (ncols, tile, x, y, nodata = -9999) => {
     const index = (y * ncols) + x;
     try {
-        const result = tile.dataView.getInt16(index * 2, false);
+        const result = tile.dataView.getInt16(index * 2, true);
         if (result !== nodata && result !== 32767 && result !== -32768) {
             return result;
         }
diff --git a/web/client/utils/cesium/BILTerrainProvider.js b/web/client/utils/cesium/BILTerrainProvider.js
index 220d3e5a2..8604c4a44 100644
--- a/web/client/utils/cesium/BILTerrainProvider.js
+++ b/web/client/utils/cesium/BILTerrainProvider.js
@@ -85,7 +85,7 @@ module.exports = function(Cesium) {
                                // time to switch bytes!!
                                var temp, goodCell = 0, somme = 0;
                                for (var i = 0; i < littleEndianBuffer.byteLength; i += 2) {
-                                       temp = viewerIn.getInt16(i, false)-offset;
+                                       temp = viewerIn.getInt16(i, true)-offset;
                                        if (temp > lowest && temp < highest) {
                                                viewerOut.setInt16(i, temp, true);
                                                somme += temp;

```

with that, and a DEM layer coming from mapserver (as BIL), `MousePlugin` correctly displays elevation values.

sadly the 3d view fails, clicking the 3d button tries to load the getcapabilities of the elevation layer via the proxy, and that generates a strange request for `https://ids.dev.craig.fr/mapstore/[object%20Object]https%3A%2F%2Fwms.dev.craig.fr%2Fmnt?SERVICE=WMS&REQUEST=GetCapabilities&tiled=true` (note the `[object%20Object]` ?) which returns a 400 error code from the proxy:
```
Type Rapport d'état
message Invalid URI: noSlash
description La requête envoyée par le client était syntaxiquement incorrecte.
```

on top of this, switching from 2d to 3d view (and back and forth) clearly shows that very few caching is done client side, there are **many** requests for BIL tiles sent to the server, while i would have expected those to be cached on the client, at least when the bbox doesnt change it should re-request the tiles..

**Comment by landryb** [comment]
compared with when mapstore loads the 3d layer from geoserver which is on the same domain as mapstore, the requested GetCapabilities URL is `https://ids.XXX.craig.fr/wxs/mnt/ows?SERVICE=WMS&REQUEST=GetCapabilities&tiled=true`

(diff between working vs non-working config for the elevation layer)
```
-                "url": "/wxs/mnt/ows",
+                "url": "https://wms.dev.craig.fr/mnt",

```

i suppose the `[object%20Object]` thing is supposed to be mapstore proxy ? How does one tell mapstore to *not* use its internal proxy for some known URLs ? i havent found out how to achieve that in `proxy.properties`...

**Comment by offtherailz** [comment]
I didn't look at the reason of this issue yet, but I suggest, if possible, to not use the proxy where possible.
MapStore automatically checks if the current URL in the browser is same origin with the request, and if not, it uses the proxy by default, when needed. Ajax requests performed by Cesium are ones that need the proxy (not allowed because of Same Origin Policy).

If you can use relative URL, the proxy will not be used. 

If you have some servers that has CORS headers, therefore can skip the proxy, you can add the base URL in `localConfig.json --> proxyUrl --> useCORS` to tell MapStore to avoid the proxy (or from a `localConfig.json.patch` file).

**Comment by landryb** [comment]
hah thanks, should have found this one.. well in my case i cant use relative urls since mapserver is on a different domain as mapstore, so i added the FQDNs to `useCORS` array, the proxy isnt used to fetch `GetCapabilities` anymore and elevation is directly fetched for `MousePosition` - i see a direct hit on `https://wms.dev.craig.fr/mnt?SERVICE=WMS&REQUEST=GetCapabilities&tiled=true` when switching to 3d mode but after that Cesium doesnt do any request for BIL data ?

Or you're telling me that regardless of the domain, because of Same Origin Policy Cesium *will* need to use the mapstore proxy if the DEM isnt on the same domain ? And because i had put the FQDN for mapserver in `useCORS` it refuses to query the remote server ?

**Comment by landryb** [comment]
i think i have a clue as to why no tiles are loaded .. my mapserver `GetCapabilities` doesnt have a `BoundingBox` entry with CRS:84, only EPSG:2154 (the native CRS of the data) while a 'working' geoserver layer has both:
```
<BoundingBox CRS="CRS:84" minx="2.013776386294975" miny="43.93711161870216" maxx="7.596486054187941" maxy="46.95030255544707"/>
<BoundingBox CRS="EPSG:2154" minx="624987.5" miny="6325012.5" maxx="1049987.5" maxy="6650012.5"/>
```

and the BILTerrainProvider.js code only checks for 4 known CRSs in GetCapabilities (`"CRS:84"`, `"EPSG:4326"`, `"EPSG:3857"`, `"OSGEO:41001"`).

mapserver-side, i've set `wms_bbox_extended` to true (per https://mapserver.org/ogc/wms_server.html) on the layer (so that a matching boundingbox is found by cesium), and the 3d view starts fetching DEM tiles from my mapserver, but strangely as `image/png` and not BIL. Will dig a bit further in that `GetCapabilities` parser to figure out what's wrong..

**Comment by landryb** [comment]
and i finally figured out i was wrongly using `application/bil16` as the MIMETYPE for the format in mapserver, while geoserver advertises `image/bil` (and it seems that's what BILTerrainProvider.js expects per https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/cesium/BILTerrainProvider.js#L71?) - once i've set this MIMETYPE in mapserver for my BIL OUTPUTFORMAT, mapstore successfully loads terrain data from mapserver, so it's possible ! The endianness still needs to be handled (per found in previous comments) but other than that it should work :)

**Comment by landryb** [comment]
@offtherailz in landryb/MapStore2@ee7abf775 i *tried* making elevation configurable via the `additionalLayer` section in `localConfig.json` but unfortunately this doesnt build, and i grok nothing to the whack-a-mole named npm/webpack/etc, so if you could have a look and tell me if i'm on the right track... that's branched from geosolutions-it/MapStore2@36d726705 which is the submodule in this project.

**Comment by landryb** [comment]
ah, i was mislead by npm, my commit actually builds. now to figure out if i can configure the endianess from localConfig.json..

**Comment by offtherailz** [comment]
Build issues are probably the same issue we noticed here: https://github.com/geosolutions-it/MapStore2/issues/6573

I looked at the work in progress and you seem on the right path. It is more or less the same idea I had when you told me if was possible to support little endian. I don't know what you are facing exactly, but I can tell you I noticed you didn't implemented it et on OpenLayers (trying to guess).

**Comment by landryb** [comment]
i finally have something that works for `MousePosition` - both for leaflet & openlayers modes, need to figure out what's wrong for cesium.

As for doing unit tests, i'm not that well versed in modern JS development, so i wouldnt even know how to run them..

**Comment by landryb** [comment]
@offtherailz can you have a look at geosolutions-it/MapStore2#6579 (i cant ask for review there) and eventually channel it down to this project ? that would simplify my workflow in production, as i'd like to avoid maintaining a fork :) thanks !

**Comment by offtherailz** [comment]
merged and prepared the backport. When the backport is merged and revision of geOrchestra updated, it will be available in a next update of geOrchstra.
