### ISSUE TITLE
Cannot load SampleExtension.zip

### ISSUE THREAD

**Issue by tkohr** [georchestra/mapstore2-georchestra#336]
**Issue**

When I try to load the SampleExtension.zip, the following error displays in the UI: https://github.com/geosolutions-it/MapStore2/blob/36d7267052ef03be1ac76e494413951a6096d0fd/web/client/utils/ExtensionsUtils.js#L17

![extension_error](https://user-images.githubusercontent.com/6329425/108856680-96ef6300-75ea-11eb-9e9c-abbcc2682a3e.png)

Using https://github.com/geosolutions-it/MapStore2 to load the same SampleExtension.zip works.

![extension_check](https://user-images.githubusercontent.com/6329425/108858017-ff8b0f80-75eb-11eb-9e59-e43a0eae8f4b.png)

**Steps to reproduce**

- clone https://github.com/geosolutions-it/MapStoreExtension and build SampleExtension.zip via `npm install && npm run ext:build`
- clone https://github.com/georchestra/docker and run mapstore2-georchestra within georchestra env
- login to georchestra and navigate to https://georchestra.mydomain.org/mapstore/#/admin
- create new map context and try to load SampleExtension.zip

I tried adding an empty extensions.json file, so it does not need to be created, but this doesn't help. (If I understand correctly the upload service is supposed to fill it). Am I missing any config in georchestra to make this work, or might it be a bug ?

**Comment by Gaetanbrl** [comment]
> I tried adding an empty extensions.json file,

As well, `extensions.json` file was not created by default (no docker env).
Create `extensions.json` with simple `{}` content (inside datadir for us) seems to fix this error.

> the upload service is supposed to fill it

Apparently not ?

**Comment by tkohr** [comment]
Thanks @Gaetanbrl. Did you see the same error? Indeed I actually did not leave it empty, but put `{}` into the `extensions.json` as you did (inside `/etc/georchestra/mapstore` datadir). It doesn't seem to resolve the issue on my side however.

**Comment by Gaetanbrl** [comment]
> Thanks @Gaetanbrl. Did you see the same error? Indeed I actually did not leave it empty, but put `{}` into the `extensions.json` as you did (inside `/etc/georchestra/mapstore` datadir). It doesn't seem to resolve the issue on my side however.

Have you a console error ?

**Comment by tkohr** [comment]
No, not once I have created the `extensions.json`. Before I saw a `404 Not found`.

![extension_error_log](https://user-images.githubusercontent.com/6329425/108971290-72df6080-7682-11eb-9bd3-eef1014d98b1.png)

**Comment by Gaetanbrl** [comment]
Maybe "warning" icon display a tooltip ?
The extension seems already installed ?

**Comment by tkohr** [comment]
Yes I captured the tooltip in my first screenshot (see above). It's the following error: https://github.com/geosolutions-it/MapStore2/blob/36d7267052ef03be1ac76e494413951a6096d0fd/web/client/utils/ExtensionsUtils.js#L17 I did not understand why it is triggered though.

The extension is not already installed however.

**Comment by tkohr** [comment]
I actually found out that the reason for this error was, that my georchestra/mapstore image was outdated. Sorry for the noise, I'll close the issue.
