### ISSUE TITLE
extensions files missing from datadir with classic install

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#340]
Hi,

The README for [georchestra/mapstore datadir](https://github.com/georchestra/datadir/tree/master/mapstore) repo explain : 

```
*extensions.json: dynamic registry of currently installed extensions, in JSON format
*pluginsConfig.json: dynamic registry of available plugins (both standard and extensions) for the context configurator, in JSON format
```

But none of them exists by default in the datadir.

About that, the lastest [mapstore2-georchestra doc](http://docs.georchestra.geo-solutions.it/fr/latest/configuration/application/index.html?highlight=extensions#dynamic-files) explain : 

`These files are all updated and managed by the extensions upload functionality.`

So, to be sur i reinstall all mapstore (drop & create shema, tables, build, deploy etc.) **from master branch**.

But when we create a new context we get #313 issues with 404 error : 

`GET ..mapstore/rest/config/load/extensions.json 404`

Here the /datadir/mapstore files : 

![image](https://user-images.githubusercontent.com/16317988/109940042-f11ab300-7cd1-11eb-8aea-3e0c2e02d5f0.png)

Indeed, extensions.json file and pluginsConfig missing and we get no more info from the doc.

**Comment by Gaetanbrl** [comment]
This issue is like #263.

Solution was to `Re-compiling and redeploying this morning seems to solve the problem.` but in this case this solution not workin (clean install from scratch).

**Comment by Gaetanbrl** [comment]
To fix this issue, i need to create extensions.json file with `{}` content into datadir folder.

**Comment by landryb** [comment]
there are two distinct problems:
- by default there's no need for extensions.json if you dont upload extensions via context creator, so its 'normal' that the two files are missing (hence the 404 at every mapstore initial load)
- if you upload an extension via the context creator, tomcat needs write access to the datadir (which shouldnt happen/shouldnt be the default, for security reasons) - in my case when testing cadastrapp, i pointed mapstore at an alternative dir (using `-D georchestra.extensions`) when tomcat could write, looked at the files deployed by uploading the extension, then moved them over to the regular datadir (root-owned).

**Comment by Gaetanbrl** [comment]
> by default there's no need for extensions.json if you dont upload extensions via context creator, so its 'normal' that the two files are missing

OK it's approximately the behavior i expected first (without the 404 error).

>  then moved them over to the regular datadir (root-owned)

This appear as optionnal in the doc. But i Understand ! Thanks @landryb.

**Comment by landryb** [comment]
what i understood from the doc and from testing, both work:
- keep `-Dgeorchestra.extensions` pointing at a dir where tomcat can write, and keep extensions there (separate from `georchestra.datadir`)
- or move them over to the dir pointed at by `georchestra.datadir`

**Comment by Gaetanbrl** [comment]
@landryb  i close if this is the "normal" behavior due to wrong config.

This issue can be used as addition details for next users with the same question (sur there will be) ;) 

Thanks.
