### ISSUE TITLE
Embedded map fullScreen not working

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#347]
When I use an embedded map, the fullScreen button doesn't work.
Nothing happen when clicking on it.

Also I wonder how I can add a "View larger map" button which redirect to the context in new tab like on embedded map on this page : https://www.geosolutionsgroup.com/technologies/mapstore/ ?

**Comment by tdipisa** [comment]
@jusabatier this issue has been recently solved MS side [here](https://github.com/geosolutions-it/MapStore2/issues/6652). We will update the MS revision on that repo soon

**Comment by offtherailz** [comment]
I added to default `localConfig.json` the configuration for embedded. You can port in your own (if modified) to see the "GoFull" plugin for embedded maps (no-context). that is the one responsible of the button that opens in a new tab the real map. 
**note** you need also this fix.  https://github.com/georchestra/mapstore2-georchestra/pull/356 . Both this and #356 are going to be backported.

**Comment by jusabatier** [comment]
Is there a way to add it to the pluginConfig.json ?

This way we can have it in the available plugins in the context editor.

**Comment by jusabatier** [comment]
I also tried to add your modifs to my localConfig.json, but still not have a GoFull button added to embedded maps.

I deployed the last war provided by https://github.com/georchestra/mapstore2-georchestra/actions/runs/764177974

**Comment by offtherailz** [comment]
It has been added on master (yet to be backported) https://github.com/georchestra/mapstore2-georchestra/blob/master/localConfig.json#L718 and if you use the share tool --> embedded  in a map **with no context** this is a sample result of the URL of the Iframe: https://georchestra.geo-solutions.it/mapstore/embedded.html#/3023 
As you can see the plugin is there. 

Unfortunately **GoFull** is actually included _only_ in the build of `embedded.js`, that is used when sharing maps with no context. It doesn't support (or has not been tested yet) in contexts and it is not included in the main build. 

I could be a good improvement to make it more general and make it work with contexts, but at the moment it works only in that specific use case.
