### ISSUE TITLE
Iframe not working when private connexion

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#351]
In current version of Mapstore, iFrame stuck in Loading state when localStorage is not accessible (private mode) : 

> Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
>     at Object.15124 (https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?208d11d2ba4fc5545688:2:515417)
>     at __webpack_require__ (https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?208d11d2ba4fc5545688:2:12644832)
>     at Object.60941 (https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?208d11d2ba4fc5545688:2:1784489)
>     at __webpack_require__ (https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?208d11d2ba4fc5545688:2:12644832)
>     at Object.66524 (https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?208d11d2ba4fc5545688:2:4584193)
>     at __webpack_require__ (https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?208d11d2ba4fc5545688:2:12644832)
>     at https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?208d11d2ba4fc5545688:2:12656245
>     at https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?208d11d2ba4fc5545688:2:12731051
>     at https://geoportail.lepuyenvelay.fr/mapstore/dist/geOrchestra.js?208d11d2ba4fc5545688:2:12731055

As it is the default in Brave web browser, it not work.

Look like it has been fixed with https://github.com/geosolutions-it/MapStore2/issues/6651 in Mapstore2, but it's not backported with latest stable update 3 days ago.

When will it be backported in mapstore2-georchestra ?

**Comment by tdipisa** [comment]
@jusabatier this issue has been recently solved MS side. @offtherailz will update the MS revision on that repo soon.

**Comment by tdipisa** [comment]
@offtherailz it seems the MS revision update provided with PRs #356 and #363 doesn't solve this specific issue even if the problem is fixed MS side. There is something to check also in the ms2-georchestra project.

**Comment by offtherailz** [comment]
backported on 1.2.x https://github.com/georchestra/mapstore2-georchestra/pull/371
