### ISSUE TITLE
Filtering features with URL parameters

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#352]
I'm trying to create an iframe from the default context and using actions URL parameters : 

https://geoportail.lepuyenvelay.fr/mapstore/#/?actions=[{"type":"CATALOG:ADD_LAYERS_FROM_CATALOGS","layers":["website:arrets_tad_liste_lignes","website:lignes_tad"],"sources":["gpvgs","gpvgs"]}]

This successfully add the two layers to a blank context.

Now, I want to filter displayed entities for each layer based on attribute.
For example, I want to only display entities with num_ligne=01 for both layers.

Is it possible to do this ?
It was possible to do this via CQL filters in sviewer, and if we want to replace it by mapstore, it's necessary.

**Comment by jusabatier** [comment]
@catmorales @landryb @MaelREBOUX 

Maybe we can discuss this functionnality as an evolution of mapstore2georchestra

The idea behind the project was to have a viewer that can replace all others, and the ability to load a map via URL or POST parameters is essential for iframe and communications purposes.

The actual viewer for this is sviewer which allow to parameter : 

- Map/Page title
- Center (x/y) and zoom
- Loaded background
- Visible loaded layers
- Filter loaded layers entities (via CQL)
- Query a loaded layer feature on load

Actually, I only success to setup loaded layers from a catalog via the upper example.

I think it can be a great improvement to extend the existing mapstore actions to allow the previous listed parameter via URL.
This way our datas can be integrated easily in partners websites via iFrames without having to create a ton of contexts for every specific usecases.

**Comment by jusabatier** [comment]
Look like we also have to enhance the ability to load a map via URL or POST parameters in order to allow GN integration : 

https://github.com/georchestra/georchestra/issues/3218

**Comment by landryb** [comment]
superseded by #476 ?

**Comment by jusabatier** [comment]
Yes, I close it.
