### ISSUE TITLE
customeditoroptions not applied ?

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#359]
enabling featureeditor in a context via the context editor (*not* localConfig.json), trying to configure a field to have the dropdown editor:
```
  "cfg": {
    "customEditorsOptions": {
      "rules": [
        {
          "regex": {
            "attribute": "fictif",
            "typeName": "geor:aerodrome"
          },
          "editor": "DropDownEditor",
          "editorProps": {
            "allowEmpty": true,
            "values": [
              "Oui",
              "Non",
              "NSP",
              "NC"
            ]
          }
        }
      ]
    }
  }
```
afaict there should be a dropdown when editing field value but this isnt the case. looking at the json returned by `/mapstore/rest/geostore/misc/category/name/CONTEXT/resource/name/test/data` cfg is stored/saved, but doesnt seem applied ?

i'm not 100% sure but it seems similar to geosolutions-it/MapStore2#6758 (backported in https://github.com/geosolutions-it/MapStore2/pull/6762) so a mapstore submodule update ought to fix that ?

**Comment by landryb** [comment]
i'm probably doing something wrong, but testing a build including #363 (so *with* the fixes from geosolutions-it/Mapstore2#6762) the `customEditorsOptions` configured in the context are still not applied, ie no dropdown for the given field when editing the given layer. 

@catmorales is seeing the same issue and was wondering if some config should go into `localConfig.json`, (according to https://mapstore.geo-solutions.it/mapstore/docs/api/framework#components.data.featuregrid.editors.customEditors ?) which seems wrong to me - why would one configure the valid values/constraints for all layers one will want to edit in a generic config file ? @offtherailz any hint ? is there a fullblown & clear working example somewhere ?

**Comment by landryb** [comment]
my previous testing was with the war from https://github.com/georchestra/mapstore2-georchestra/actions/runs/764177974 which included geosolutions-it/MapStore2#6758 (then this config should work?), so... either it isnt possible to configure `customEditorOptions` in a context (and only in `localConfig.json`, or the config i'm trying is syntaxically wrong. In a plugin config, what's the distinction between `cfg` and `override` ?

**Comment by tdipisa** [comment]
@landryb I will ask @offtherailz to do a quick check asap, early next week.

**Comment by sigrmed** [comment]
You can reproduce  the problem with https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/test_maj

**Comment by landryb** [comment]
i've also tried putting the `cfg` block directly in the `FeatureEditor` section in `localConfig.json` but it doesnt seem applied there either.

**Comment by landryb** [comment]
@offtherailz did you have any luck looking into this ? thanks !

**Comment by catmorales** [comment]
I updated mapstore v1.2 (docker image) thinking that your last modifications had solved this problem but no it still doesn't work. The input constraints are not applied.
Please tell us why.

**Comment by offtherailz** [comment]
Fixed  by. Waiting for revision update today. https://github.com/geosolutions-it/MapStore2/pull/6839

**Comment by landryb** [comment]
on my dev instance, testing the war produced by https://github.com/georchestra/mapstore2-georchestra/actions/runs/831669404 that includes this fix, after reloading several times my existing test context where `FeatureEditor` plugin has this config:
```
{
  "cfg": {
        "customEditorsOptions": {
      "rules": [
        {
          "regex": {
            "attribute": "avis",
            "typeName": "rtge:avis_partenaires"
          },
          "editor": "DropDownEditor",
          "editorProps": {
            "allowEmpty": true,
            "values": ["Oui", "Non", "A reporter"]
          }
        }
      ]
    }
  },
  "override": {}
}
```
it now works fine on existing context instances/childs and a newly created context instance/child. Many thanks for fixing it !

![image](https://user-images.githubusercontent.com/3421760/117948966-eef85480-b311-11eb-97f9-16c9f98b3884.png)
