### ISSUE TITLE
User Context - User session

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#36]
The user session includes:
 - the active map (the map currently visualized and its status)
 - the activated extensions
 - favourites map templates (see #34)

The session needs to be automatically persisted to be restored for a next user session.

We will save one session per application context.

An utility to reset the user context must be provided to restore the initial application context

**Comment by mbarto** [comment]
Dependencies:
 * https://github.com/geosolutions-it/MapStore2/issues/4954

**Comment by mbarto** [comment]
Blocked by https://github.com/geosolutions-it/MapStore2/pull/5032

**Comment by mbarto** [comment]
Needs this: https://github.com/geosolutions-it/MapStore2/pull/5109

**Comment by tdipisa** [comment]
@mbarto Moving it back to ready.

If I reset the user session, favourite templates and activated extensions are not reset
