### ISSUE TITLE
Need to change french strings

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#367]
After discussions last weeks we need to change some string for the french translation string.

Because of the mapfishapp backgrounf but not only. After testing on customers (and admins !) we can confirm some confusion int erms and concept. because MapStore2 is so rich.

So we need to change this strings quickly in order to upgrade the documentation before go to production in the next weeks.

- catalogue --> Ajouter une donnée
- catalogue de cartes -> catalogue d'applications
- modèles de cartes -> cartes modèles
- Enregistrer -> Enregistrer sous

I noted weeks ago qome other minor things like :

- Export -> Exporter
- Undo / Redo -> Zoom précédent / suivant

@landryb @jusabatier @LouiseBaillet @catmorales  si vous avez des trucs à demander : c'est le moment.

**Comment by MaelREBOUX** [comment]
PR submitted : https://github.com/geosolutions-it/MapStore2/pull/6845

**Comment by MaelREBOUX** [comment]
and a specific georchestra PR : https://github.com/georchestra/mapstore2-georchestra/pull/377

**Comment by MaelREBOUX** [comment]
PR mapstore core merged
awaiting merge for #377 -> poke @tdipisa ?

**Comment by tdipisa** [comment]
@MaelREBOUX I've already commented in the [MS PR](https://github.com/geosolutions-it/MapStore2/pull/6845#issuecomment-843891179). Thank you

**Comment by MaelREBOUX** [comment]
ok. check.

**Comment by tdipisa** [comment]
@MaelREBOUX we finally merged these updates in master branch and backported them in 1.2.x.

**Comment by MaelREBOUX** [comment]
I just saw the modifications on our portal. So much clear for the users now.
