### ISSUE TITLE
No tooltip on the burger menu items

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#369]
I just saw that there is tooltip on the items of the burger menu !

But : only the measure tool shows a tooltip.

![image](https://user-images.githubusercontent.com/6370443/117641046-fee32d80-b185-11eb-90bc-18744a978910.png)

![image](https://user-images.githubusercontent.com/6370443/117641182-2639fa80-b186-11eb-9828-b18b8ce1cffb.png)

Is it normal @tdipisa  ?

is it only at Rennes ?

**Comment by landryb** [comment]
same thing here.

**Comment by MaelREBOUX** [comment]
ok : same thing in english

![image](https://user-images.githubusercontent.com/6370443/117642348-76fe2300-b187-11eb-8c47-779e7d2c2e1b.png)

So impov there is a lacks of certains strings.  

The string for the Measure tool is in the componant "module" 
see : https://github.com/geosolutions-it/MapStore2/blob/master/web/client/translations/data.fr-FR.json#L730

I think it is the same thing for the "map catalog" item. There is no `tooltip` entry
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/translations/data.fr-FR.json#L2996

What is your expertise @offtherailz ?

**Comment by Gaetanbrl** [comment]
I think tootlips was not defined for others plugins.

Here, we can see the tooltip text for Measure tool : 

https://github.com/geosolutions-it/MapStore2/blob/5ebe5640c24c5ac3a784b54d82e33892529dbac6/web/client/plugins/Measure.jsx#L126

And here, no tooltip for Annotation (same for Share plugin): 

https://github.com/geosolutions-it/MapStore2/blob/5ebe5640c24c5ac3a784b54d82e33892529dbac6/web/client/plugins/Annotations.jsx#L308-L315

**Comment by Gaetanbrl** [comment]
> is it only at Rennes ?

So, ithing this concerns MapStore Core.

**Comment by MaelREBOUX** [comment]
so @Gaetanbrl we miss string and json item in each jsx file ?

And I will open an issue in the Mapstore core for this.

**Comment by Gaetanbrl** [comment]
> so @Gaetanbrl we miss string and json item in each jsx file ?

Indeed, to add a tooltip we need to :
1. add "tooltip" paramas for each plugins (e.g Measure link above)
2. add translate for each lang


**Ex. for Annotation** :

Add tooltip into `plugins/Annotations.jsx` file : 

```
        BurgerMenu: {
            name: 'annotations',
            position: 40,
            text: <Message msgId="annotationsbutton"/>,
            tooltip: "annotationComponent.tooltip",
            icon: <Glyphicon glyph="comment"/>,
            action: conditionalToggle,
            priority: 2,
            doNotHide: true
        }
```

In `data.fr-FR.json` (need to create annotation section if not exist) : 

```
        "annotationComponent": {
            "tooltip": "Réaliser des annotations"
        },
```

![tooltipAnnotation](https://user-images.githubusercontent.com/16317988/117645237-a8c4b900-b18a-11eb-9361-b4357a4b097d.gif)

**Comment by MaelREBOUX** [comment]
ok. So let's create an issue on https://github.com/geosolutions-it/MapStore2/

**Comment by tdipisa** [comment]
@MaelREBOUX the MS issue has been closed recently through [this PR](https://github.com/geosolutions-it/MapStore2/pull/7036). The update will be available in the next major release in September (v2021.02.00)
