### ISSUE TITLE
Security - Security extension

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#37]
The viewer must be integrated in the geOrchestra security tier with this extension (for this reason it can be activated/deactivated by the administrator in backoffice in the same way of other extensions)

- The authentication of an user by the geOrchestra security context that involves: Security proxy, CAS and LDAP
- The viewer only retrieves the information related to the user rights on extensions, layers and other protected information
- User rights are managed in backoffice by the administrator and are mapped to user roles

We need to implement this:
 * [x] backend authentication filter using security proxy headers
 * [x] backend authorization using user / roles data from authentication and ignoring on-db user and groups
 * [x] backend integration with LDAP to retrieve roles list
 * [x] frontend automatic login from backend authentication filter

**Comment by fvanderbiest** [comment]
This may help: https://github.com/georchestra/georchestra/blob/master/security-proxy/README.md#how-to-integrate-a-new-application-in-georchestra-

**Comment by mbarto** [comment]
We need this on the mapstore backend side:
 * https://github.com/geosolutions-it/geostore/issues/190
 * https://github.com/geosolutions-it/geostore/issues/191
