### ISSUE TITLE
Regression on map templates  from WMC

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#387]
Map template  imported from a WMC from Mapfishapp are no longer compatible with mapstore.
It is no longer possible to **display the attribute table of the layers present in these**  Map Templates. 

**URL:** https://portail-test.sig.rennesmetropole.fr/mapstore or 
https://portail.sig.rennesmetropole.fr

**Version mapstore2 :** tag v1.2.x from https://hub.docker.com/r/geosolutionsit/mapstore2-georchestra/tags?page=1&ordering=last_updated

**To reproduce the issue:**

- [ ] 1/ open mapstore
- [ ] 2/ add a map template from "cartes modèles"
- [ ] 3/ select a layer
- [ ] 4/ TOC toolbar for this layer is reduced , **it's not OK - we are expecting for a full TOC toolbar**
 ![image](https://user-images.githubusercontent.com/4659829/119966145-4dc4fb80-bfab-11eb-856a-fbb8dc3513b6.png)
- [ ] 5/ Load from Ajouter des données/Géoservices (/geoserver)  the layer "Localisation des stations de métro"
- [ ] 6/ TOC toolbar for the layer is full , **it's OK**
 ![image](https://user-images.githubusercontent.com/4659829/119966605-c3c96280-bfab-11eb-94ee-5fb447366445.png)

All our MapTemplates (46) were created from mapfishapp WMC and exported in json format before loading it  in context manager as map templates.
This problem has appeared since last week (new mapstore deployment)

**What could be the reason?** 
Can we fix this quickly as we are training users next week ?

**Comment by tdipisa** [comment]
@catmorales we will check this next week, thank you for reporting. It is not totally clear to me the problem anyway.
Can you please better explain the steps to reproduce the issue highlighting what is the expected behavior against the current one?

What do you mean for "contextual menu"?
> 4/ contextual menu for this layer is reduced
> 6/ contextuel menu for the layer is full
 
Do you mean buttons in the TOC toolbar?

**Comment by catmorales** [comment]
bq.Do you mean buttons in the TOC toolbar?

Yes it is

**Comment by catmorales** [comment]
>what is the expected behavior against the current one?

I was expecting for a complete TOC toolbar for all layers loaded from the map template.

**Comment by catmorales** [comment]
I will give you a simpler and easier to reproduce use case :

- [ ] go to mapfishapp
- [ ] load a layer 
 for example  :  stations vélos
![image](https://user-images.githubusercontent.com/4659829/120163108-6fb3bd80-c1f9-11eb-94cc-eb653eb11abe.png)
- [ ]  export the map with "save map" function in WMC format
![image](https://user-images.githubusercontent.com/4659829/120163349-b5708600-c1f9-11eb-8d24-48af1e9d0f64.png)
- [ ]  import the WMC into mapstore
- [ ] the layer has been loaded but the TOC buttons: attribute table, download, etc are disabled
![image](https://user-images.githubusercontent.com/4659829/120163925-4e070600-c1fa-11eb-9e50-385a14becfe5.png)

**Comment by offtherailz** [comment]
Hi @catmorales thank you this helps a lot to identify the problem.

**Comment by catmorales** [comment]
Another information, if it can help,  we are now on 20.1.1 version of geOrchestra 
https://github.com/georchestra/georchestra/releases/tag/20.1.1

**Comment by offtherailz** [comment]
Hi,
WMC format doesn't support any connection between WMS layers and the relative WFS service (needed to have the attribute table available). 

The map exported from mapfish app do not contain any information about it, so the imported map is not connected.

MapStore introduced the support to this adding a custom tag, but you have to insert it into the WMC manually.
Here attached in the zip file "[Stations De Comptages routiers.zip](https://github.com/georchestra/mapstore2-georchestra/files/6574973/Stations.De.Comptages.routiers.zip)" :
- `Stations De Comptages routiers.wmc`: the original WMC exported by mafish app.
- `Stations De Comptages routiers-search.wmc`: the WMC above, modified to add the link to WFS. 

The difference between the two files is only the following tag inside `Extension` tag of the layer:
```xml
<ms:search xmlns:ms="http://geo-solutions.it/mapstore/context"
          xmlns:xlink="http://www.w3.org/1999/xlink" type="wfs" xlink:type="simple" xlink:href="https://portail-test.sig.rennesmetropole.fr/geoserver/wfs"/>
```
Importing this second file, you will see that the attribute table becomes available.


From my checks this is the only way to add the attribute table to the layer. Are you sure that you where able to see the attribute layer without this procedure from a WMC exported from mapfish app? If so, do you remember in which version ?


_note about catalog: When adding layers from the from catalog, MapStore get the missing information from "DescribeLayer" service, but this is not the case of importing an existing configuration (that maybe manually modified, so querying the service in that case is incorrect)._

**Comment by catmorales** [comment]
Hi @offtherailz !!
Thank you very much !! I will try to add manually this link.

> If so, do you remember in which version ?
This  problem appears from the last version of v1.2.x from 12 days ago.
In the previous commit it was OK.
Is it possible to have an history in docker hub ?

**Comment by catmorales** [comment]
I deployed v1.2.x on 27th of may --> NOK
I deployed v1.2.x on 21th of may --> I don't know if it was OK
I deployed v1.2.x on 4th of may --> OK

We deployed a new version of geOrchestra (so geoserver is now on 2.17.5 version) on 26th of may . 
Do you think this might have something to do with the problem ?

**Comment by offtherailz** [comment]
No, I don't think that the GeoServer update can influence this.

I did a [diff](https://github.com/georchestra/mapstore2-georchestra/compare/a56ace0b5054edb295caf59e2273e31b153d4212..c4c0bb320f10b8e49147cd8ed38e030145d30ab0)  on georchstra-mapstore for the versions you gave me and I don't see any change in the code that may have removed that functionality. 

If you need it now,  you can add the attribute table to maps exported from mapfish app by adding the search links in the XML as in the example (the URL of wfs (in the example `xlink:href="https://portail-test.sig.rennesmetropole.fr/geoserver/wfs"` must be the one of the GeoServer used for that layer).

**Comment by catmorales** [comment]
OK thank you. @offtherailz

**Comment by tdipisa** [comment]
@catmorales can we close the issue?

**Comment by fvanderbiest** [comment]
> WMC format doesn't support any connection between WMS layers and the relative WFS service (needed to have the attribute table available).

With mapfishapp, we relied on WMS DescribeLayer + WFS DescribeFeatureType requests to dynamically perform this link

**Comment by offtherailz** [comment]
The same on MapStore, but only when adding data from catalog, not when importing existing maps in JSON/WMC.
The missing link in a map file should be intentional (for instance to configure a map manually and hiding the link to the attribute table)
So MapStore doesn't add information to the imported file.

**Comment by tdipisa** [comment]
@catmorales can we consider this issue closed?

**Comment by catmorales** [comment]
@tdipisa yes you can ;)
