### ISSUE TITLE
LocalStorage management in the default map

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#389]
When UserSession is enabled into localConfig.json, the map stored in localstorage override maps into  application contexts edited from the context manager.

**URL:** https://portail-test.sig.rennesmetropole.fr/mapstore 

**Version mapstore2 :** tag v1.2.x from https://hub.docker.com/r/geosolutionsit/mapstore2-georchestra/tags?page=1&ordering=last_updated

**geOrchestra v20.1.1**

**Use case :** 

- [ ]  go to https://portail-test.sig.rennesmetropole.fr/mapstore
- [ ] move the map
- [ ] add a layer from Géoservices (/geoserver)  (ex stations vélo)
![image](https://user-images.githubusercontent.com/4659829/120172675-95de5b00-c203-11eb-8ce2-e90625ad1f99.png)

- [ ] go to the context manager https://portail-test.sig.rennesmetropole.fr/mapstore/#/admin/
- [ ] open the context application "test_catherine" in editing mode
- [ ] the previous map of the contextapplication has been overwritted  by the map stored in the local storage
![image](https://user-images.githubusercontent.com/4659829/120173146-09806800-c204-11eb-95fe-5d767cfda901.png)

It is possible to clear the local storage before editing an application context but it's not very friendly.

**Comment by offtherailz** [comment]
Hi, 
Here there is a fix in pending review here on MapStore https://github.com/georchestra/mapstore2-georchestra/issues/389 , tomorrow we will test it and follow the usual procedure

**Comment by tdipisa** [comment]
@catmorales this issue is in test, @offtherailz also backported the fix on 1.2.x last week. Let us know if the problem is solved for you and we can close the issue.

**Comment by catmorales** [comment]
I have to redeploy mapstore in test. i'll do it asap.

**Comment by catmorales** [comment]
On monday morning.

**Comment by catmorales** [comment]
I have tested it,  it seems OK.
Thank you @offtherailz

**Comment by catmorales** [comment]
sorry i just saw that th etranslation of "Catalog" to "Ajouter des données" is not applied in this version.

**Comment by tdipisa** [comment]
I'm sorry @catmorales but this is a different topic and I would like to avoid mixing things. 

>Sorry i just saw that the translation of "Catalog" to "Ajouter des données" is not applied in this version.

Can you please open a different issue or maybe ask @MaelREBOUX? This is because I know he is already working on some translations

**Comment by catmorales** [comment]
ok

**Comment by MaelREBOUX** [comment]
Don't know if we have to open a new issue ?

The strings modified are in ths PR https://github.com/geosolutions-it/MapStore2/pull/6845
that has already backported previously I think ?
See : https://github.com/geosolutions-it/MapStore2/pull/6845#issuecomment-843891179
poke @offtherailz 

note : not esay for me to understand what is backported from mapstore and what is not

**Comment by MaelREBOUX** [comment]
that was done here impov : https://github.com/georchestra/mapstore2-georchestra/issues/367#issuecomment-845120060

**Comment by tdipisa** [comment]
@MaelREBOUX 
>Don't know if we have to open a new issue ?

For sure, this issue is not the right one :-)

I will ask @offtherailz to do a quick check

**Comment by offtherailz** [comment]
I think I understand. After the first review with @tdipisa, we adjusted a little the strings to make them more consistent with MapStore semantics.
This PR contained some fixes, but also reverted some changes originally done by your PR.

https://github.com/geosolutions-it/MapStore2/pull/6894

So to have these string in geOrchestra you need to put them in the translation file of geOrchstra.

I didn't mention this when I updated to latest stable MapStore.

**Comment by MaelREBOUX** [comment]
> So to have these string in geOrchestra you need to put them in the translation file of geOrchstra, as for the other overrides
> I didn't mention this when I updated to latest stable MapStore.

Not sure to understand the mecanism. We saw the corrections / enhancements and they are not present anymore.
Please @offtherailz  possible to take 5 min by phone on monday to clarify the process ? I'm free all the day.

**Comment by offtherailz** [comment]
It's ok for me.
 Anyway let me try to explain it, so you have it as a reference, for completeness:

_basically this is what happened:_

You did the PR and we accepted --> updated geOrchestra revision --> you 've seen the result

We modified the string a second time, reverting some of your changes --> updated geOrchstra revision --> the changes disappeared.

It's my fault of not advising you that we restored some of the original strings you modified on the core, after an initial acceptance.

_How to have your translations again on geOrchestra_

Now, some of the strings you send are not in MapStore, but they can be added anyway as a customization in geOrchestra. The only thing you have to do is to add them in the custom translation files of geOrchestra.

here : https://github.com/georchestra/mapstore2-georchestra/blob/master/translations/

In these files you can put all the strings you want to customize on the project, and that can not be part of MapStore. In general you should add your customization here, if they are not fixes that have a general interest on mapstore. 

For instance this line: 

https://github.com/georchestra/mapstore2-georchestra/blob/c4d5e107bd0c414191851897b56b5d91f3b00c45/translations/data.fr-FR.json#L8

customizes this string from the original project, replacing "Catalogue de cartes" with "Applications thématiques", while in MapStore the  string remains the first. 

https://github.com/geosolutions-it/MapStore2/blob/3140a7b066a46bd4eccf01d419b9c28bb84517ae/web/client/translations/data.fr-FR.json#L2753

So feel free to add the missing strings to georchstra custom translation files (https://github.com/georchestra/mapstore2-georchestra/blob/master/translations/) in a PR, and sorry again for the misunderstanding.

If you need to clarify more, please contact me via email.
