### ISSUE TITLE
Extension Library - List of available extensions

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#39]
This extension provide to the user the list of extensions ready to be activated for the viewer. 

The list of available extensions is configured by the administrator in backoffice from configuration (using the Extension manager): they have been configured by the administrator in #22. This extension must provide the following: 

- The list of extensions will be available in a right side panel corresponding to a specific menu option.
- This extension will be available inside the viewer if at least one extension has been configured for this in the step n° 2 of the context wizard (see #22). 
- A list of extensions identified by name, description and a proper symbology (i.e. an icon)
- The user can activate an extension with a simple click on a list element, more than one extension in the provided list can be activated by the user
- The status of an extension (loaded/activated) must be included within the application state and so persisted when the map context is saved

The mockup is available [here](https://demo.geo-solutions.it/mockups/mapstore2/georchestra-templates-extensions/#/), open the Ms option menu and click on **Extensions**:

![image](https://user-images.githubusercontent.com/1280027/70797583-16599380-1da5-11ea-9099-e0234b234347.png)

Follow work on epic https://github.com/geosolutions-it/MapStore2/issues/4722

**Comment by offtherailz** [comment]
Inspecting the current work on #20 and #22 we decided to include in this task the following changes: 
 -Create `AddLayer`, `FilterLayer` (for query panel), `Metadata` plugins as well as the others and modify `TOC` to be also a `PluginContainer` that receives the buttons for that functionalities. The existing `AddGroup`, `FeatureGrid` and `LayerSettings` should render a button as well **3pt**
 - Add a flag to allow `userSelection` in the context-editor that make the button "make user selection..." visible.(Also make sure that sub-plugins  For `TOC` and `Widget` has` userSelection = false`) **1pt**
- Query Panel becomes hidden dependency of `TOC`, `FeatureEditor` and `WidgetBuilder`
- Drawer Menu add/remove together with `TOC` **2pt**
- `MapFooter` enable|disable do not  update immediately **2pt**
- Background Selector add should appear only if catalog is present **1pt**

**Comment by offtherailz** [comment]
Note: To speed up, for the moment, AddLayer and FilterLayer are dummy plugins, they don't render anything, simply enable/disable the button in the TOC.

**Comment by francoperversi** [comment]
@offtherailz @tdipisa I noticed the following:
* Save plugin, once added, it'is always enabled (also if I unselect it from the User Extension panel)
* Widget plugin, once added, it'is always enabled (also if I unselect it from the User Extension panel)
* When timeline is added but disabled in User Extension panel, it overlap TOC button in top-left

![timeline](https://user-images.githubusercontent.com/54808782/74226187-6af19000-4cbc-11ea-9835-0cef489cee49.jpg)

All those issue were found both in mapstore DEV and geOrchestra

**Comment by offtherailz** [comment]
@francoperversi it's solved by [this](https://github.com/geosolutions-it/MapStore2/pull/4890). Going to update revision

**Comment by tdipisa** [comment]
@offtherailz, it can be moved to test right ? :)

**Comment by francoperversi** [comment]
@offtherailz @tdipisa the first 2 poits reported in my comment are still there

**Comment by offtherailz** [comment]
Sorry, my fault. Only point 3 is solved by the PR.

**Comment by tdipisa** [comment]
closed in favor of #165
