### ISSUE TITLE
Plugins & DateTimePicker works only with nativ mapstore2

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#390]
Hi,

**Describe**
I get some troubles when i try to use the DateTimePicker component (react-widgets) available with mapstore2 in a plugin.

When i try to use the SampleExtension plugin with the DateTimePicker in a mapstore2-georchestra context, the app is broken (see screenshot below).
In dev mode from MapStoreExtension and MapStore2 without georchestra (npm start), all works perfectly (see below).

**Steps**
1. Clone MapStoreExtension
2. Add simple DateTimePicker component
3. Start webpack (npm start)
4. Test plugin and change date ==> OK
5. Build plugin (get ZIP)
6. Open context and test calendar
5. App crash as below

**Screenshot**

* First part : webpack dev server ==> OK
* Second part : Rennes Métropole mapstore2-georchestra ==> KO

![issue113_2](https://user-images.githubusercontent.com/16317988/120352176-cf48c080-c300-11eb-93a6-e02b04f12fbc.gif)

**Versions**
Mapstore2-geochestra 1.2.x (Rennes Métropole test env).

**Logs**

```
TypeError: Cannot read property 'time' of undefined
    at Object.getFormat (99.7a608ef7.js:2)
    at p (99.7a608ef7.js:2)
    at t._dates (99.7a608ef7.js:2)
    at t.getInitialState (99.7a608ef7.js:2)
    at new t (99.7a608ef7.js:2)
    at bi (geOrchestra.js?a15da53b940d7f0e4793:2)
    at Ia (geOrchestra.js?a15da53b940d7f0e4793:2)

TypeError: Cannot read property 'header' of undefined
    at Object.getFormat (99.7a608ef7.js:2)
    at z (99.7a608ef7.js:2)
    at t._label (99.7a608ef7.js:2)
    at t.render (99.7a608ef7.js:2)
    at La (geOrchestra.js?a15da53b940d7f0e4793:2)
```

**Code to reproduce**
In SampleExtension plugin, Replace component.jsx content by this code : 

```
import React from "react";
import Message from "@mapstore/components/I18N/Message";
import src from "../assets/markers_default.png";
import { DateTimePicker } from 'react-widgets';
const Extension = ({ value = 0, onIncrease, changeZoomLevel }) => {
    return (<div id="SAMPLE_EXTENSION" >
        <h2>Extension Sample</h2>
        <div>This is a sample extension plugin. The following tools demonstrate the correct binding inside MapStore</div>
        <h3>State and epics</h3>
        <div>A button like this should be visualized also in the toolbar: <br /><button onClick={onIncrease} className="btn-primary square-button btn">INC</button><br /> </div>
        <div>Clicking on that button (or on the button above) should increase this counter value: <b>{value}</b>. <br />The counter value updates should be logged in console by an epic</div>
        <i>note: the button in the toolbar can be hidden, in this case click on the "..." button</i>
        <h3>Localization</h3>
        The following text should be localized: <b><Message msgId="extension.message" /></b><br /> (you should see something like "Message!" if your language is set to en-US)
        <h3>Core action</h3>
        This button should change the zoom level to "1"
        <button onClick={() => { changeZoomLevel(1); }}>zoom to level 1</button>
        Here a sample image with several markers:
        <DateTimePicker
            type="date"
            dropUp
            calendar={true}
            time={false}
            culture="fr"
            format="DD/MM/YYYY"
        />
        <img src={src}/>
    </div>);
};
```

**Comment by Gaetanbrl** [comment]
Seems happend only with builded version (zip).
Try with master mapstore2-georchestra with web dev server and this component works.

**Comment by catmorales** [comment]
Hello @tdipisa , we are impacted by this bug with an application that we need to deploy as soon as possible.
Could you please take a look at this issue ?
Thank you very much.

**Comment by tdipisa** [comment]
@catmorales we will probably be able to look at this in the second half of July.

**Comment by Gaetanbrl** [comment]
After try in dev mode describe in #398, i now get this more readable error :

>Uncaught Error: [React Widgets] You are attempting to use a widget that requires localization (Calendar, DateTimePicker, NumberPicker). However there is no localizer set. Please configure a localizer. 

So, we need to use a localizer with DateTimepicker component.

Juste add these lines seems fix the error : 

```
import moment from 'moment';
import momentLocalizer from 'react-widgets/lib/localizers/moment';
momentLocalizer(moment);
```

More infos about localizer and react-widgets : 
https://github.com/jquense/react-widgets/blob/v4/packages/docs/components/pages/i18n.md


Will test totally and close issue if this solution fix this issue.

**Comment by Gaetanbrl** [comment]
Above comment fix this issue. I close.
