### ISSUE TITLE
Adherence to tomcat / JRE8 as a servlet container / Java version ?

### ISSUE THREAD

**Issue by pmauduit** [georchestra/mapstore2-georchestra#393]
The provided dockerfile is making use of an official tomcat docker image from docker-hub:
https://github.com/georchestra/mapstore2-georchestra/blob/master/Dockerfile#L1

The docker images provided in the georchestra organization on docker-hub are generally deriving from jetty images instead:
https://github.com/georchestra/georchestra/blob/master/mapfishapp/src/docker/Dockerfile#L1

Are there any adherence to tomcat ? should it work with another servlet containers ?

Same question with the Java version: currently a java8 jre is used, can we assume that a newer version of java can be used with Mapstore ?

**Comment by jusabatier** [comment]
Don't know for jetty compatibility, but JRE11 is upported : https://github.com/georchestra/mapstore2-georchestra/issues/61
