### ISSUE TITLE
Debug or Develop front part

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#398]
Hi,

I search to investigate mapstore2-georchestra front part to fix #390 mapstore2-georchestra.

So, i follow [this short instruction](https://docs.georchestra.geo-solutions.it/en/latest/developer/index.html#developing-the-frontend) and just clone / install and start web dev server (`npm start`).

Server start well but i get this error on /mapstore path : 

`Error occured while trying to proxy to: localhost:8081/header.html: `

... And this web dev server error : 

`[HPM] Error occurred while trying to proxy request /rest/config/load/localConfig.json from localhost:8081 to http://localhost:8080/mapstore (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

All georchestra was installed in a local Virtual Machine. So, MapStore2-georchestra war file is deploy in tomcat container with the default port 8280 (default config).  So default mapstore war was deployed on 8280.

What part i missing (need to change DEV_HOST?) ? Could i use the deploy default Tomcat instance to use the backend part with the npm started mapstore ?

Maybe this doc is to follow too @offtherailz ?
https://mapstore.readthedocs.io/en/latest/developer-guide/developing/

Thanks.

**Comment by Gaetanbrl** [comment]
I(h change DEV_HOST to localhost:8280 and could see MapStore with the header on localhost:8081.

But the header, extension or login requests use localhost:8081 and logically return a 404 error. My georchestra backend seems not use.

- http://localhost:8081/rest/geostore/session/login
- http://localhost:8081/rest/config/load/extensions.json
- http://localhost:8081/header.html

I dunno but maybe i need to change the MapStore2/build/buildConfig.js file to set correct service ?

**Comment by Gaetanbrl** [comment]
I confirm the localConfig.json is not use by default `npm start`, so DEV_HOST seems not really use to call the correct service or header.

Steps:  

* clone
* npm install
* change localConfig.json (e.g insert SampleExtension plugin for test)
* change webpack.config.js > change DEV_HOST
* npm start
* Access to localhost:8081
* SampleExtension is not loaded
* in network console tab, inspect localConfig.json > It's not the localConfig expected

**Comment by offtherailz** [comment]
To use the local  `localConfig.json` for local development you have to edit `app.jsx` 

https://github.com/georchestra/mapstore2-georchestra/blob/c4d5e107bd0c414191851897b56b5d91f3b00c45/js/app.jsx#L40

Otherwise it will use the ones from the server (proxied). Make sure also that "SampleExtension" is in `plugins.js`

https://github.com/georchestra/mapstore2-georchestra/blob/master/js/plugins.js

**Comment by Gaetanbrl** [comment]
thanks @offtherailz , this concerns a fix around #390 and not 39 (a mistake in my first comment).

I will try this now.

**Comment by Gaetanbrl** [comment]
@offtherailz 

This is my test : 

1.  in app.jsx

Replace this : 

```
ConfigUtils.setLocalConfigurationFile("rest/config/load/localConfig.json");
ConfigUtils.setConfigProp("extensionsRegistry", "rest/config/load/extensions.json");
ConfigUtils.setConfigProp("contextPluginsConfiguration", "rest/config/load/pluginsConfig.json");
ConfigUtils.setConfigProp("configurationFolder", "rest/config/load/");
```

By

```
ConfigUtils.setLocalConfigurationFile('localConfig.json');
ConfigUtils.setConfigProp("extensionsRegistry", "extensions.json");
ConfigUtils.setConfigProp("contextPluginsConfiguration", "pluginsConfig.json");
ConfigUtils.setConfigProp("configurationFolder", "");  // ==> to use a custom config.json map file
```

I could use a custom config.json file, remove a plugin now and control localConfig from git folder.

Try to use SampleExtension plugin now...

2. in plugins.js add 

```
SampleExtension: require('./plugins/Extension').default
```

3. in localConfig.json add the plugin

```
    "desktop": [
      "Details","SampleExtension",
```


But plugin is not available from localhost:8081 / not visible, but he is correctly visible inside appPugins  object (app.jsx) :

```
const appPlugins = {
    plugins: {
        ...plugins.plugins,
```

**Comment by Gaetanbrl** [comment]
For a second test, i have re create a MapStoreExtension env inside mapstore2-georchestra folder from :

1. in /js folder, create same extension folder

2. Inside this /js/extension folder i insert Tabou2 custom plugin

3. in /js folder, create same enxtensions.js file with exactly same content
https://github.com/geosolutions-it/MapStoreExtension/blob/master/js/extensions.js

4. in js/app.jsx file, replace 
```
const appPlugins = {
    plugins: {
        ...plugins.plugins,
```

...by 

```
const extensions = require('./extensions').default;
plugins.plugins = { ...plugins.plugins, ...extensions };
const appPlugins = {
    plugins: {
        ...plugins.plugins,
```

5. In root folder mapstore2-extension, add config.js

So, i have the same content with "Tabou2" name in my case.

https://github.com/geosolutions-it/MapStoreExtension/blob/master/config.js


6. Keep empty `{}` Extensions.json file

Now, i can see my custom plugin inside mapstore2-georchestra. But i need to config translations assets not founds...

**Comment by offtherailz** [comment]
Doing what you are trying to do is not so simple.

Just for information, did you tried to replicate the issue with the "Test Module" procedure? It should allow to test the module as it was installed:

https://github.com/geosolutions-it/MapStoreExtension#test-module

This allows to investigate compatibility problems for extensions in a easier way. I strongly suggest to try this first, to do an attempt to replicate the issue locally.

The procedure you followed is smart, but I think that you may not be able to replicate the issue in that way, because you may reach a compilation unit similar to the local test environment, where you did not have the issue. 
Instead using the `test-module` procedure, you have a build similar to the one on the server, but with the code not uglified.

**Comment by Gaetanbrl** [comment]
> did you tried to replicate the issue with the "Test Module" procedure?

Nothing about test module. But this way seems better... and most easier btw.

I will test it and return a comment :) Thanks again ;)

**Comment by Gaetanbrl** [comment]
@offtherailz i confirm i was able to reproduce a plugin error with test-module.

Thank you, in my case this is enought.
I close.
