### ISSUE TITLE
.gitignore package-lock.json ? make sure it's not modified by the build ?

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#4]
running `build.sh` modifies `package-lock.json`, which is tracked in the git repo. 

Running a build shouldn't leave modified files in the working directory...

**Comment by mbarto** [comment]
@landryb in my opinion we can remove package-lock.json from the repo. We already use fixed versions off all libraries in package.json and from my experience package-lock.json changes too frequently for unpredictable reasons. Any other opinion @offtherailz @tdipisa ?

**Comment by offtherailz** [comment]
I agree @mbarto. [Here](https://nodejs.dev/the-package-lock-json-file ) a good documentation. We should re-start to commit package-lock.json if we want again to use **semver** notation.
We could even add to .gitignore, to prevent future commits

**Comment by tdipisa** [comment]
@mbarto @offtherailz I agree too. @mbarto please, can you proceed with this?
