### ISSUE TITLE
Plugin's version upgrade

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#406]
What is the correct way to upgrade an installed plugin to newer version ?

Actually I do this : 

1. Delete the installed plugin from a context's plugin management page
2. Install the new version of the plugin from the ZIP file
3. Activate the plugin
4. Check the configuration is good
5. Save the context

But with this method, when I load the context, the plugin is not activated and I have to refresh via Ctrl+Shift+R to have it.

**Comment by landryb** [comment]
to upgrade cadastrapp, i go to the datadir (eg for me `/etc/georchestra/mapstore/dist/extensions/Cadastrapp`, i dont use a distinct directory for extensions), rm all the files there, unzip the new version of the plugin (dropping some useless files), and touch the webapps' `web.xml` file to force a reload. That's transparent for contexts.. and the user will always need to refresh the page anyway.

**Comment by jusabatier** [comment]
Ok I did some more tests, si it look like this behavior is only for the user who edit the context (to upgrade plugin) and the load it from admin page after.

When I use another browser to simulate another anonymous user, it's good.

Then I close the issue.

@tdipisa Can you just confirm that the proposed method for upgrade plugins is good ?

**Comment by MaelREBOUX** [comment]
Here I have a personal test context.

I enter in update mode on it.
On the third step I delete the plugin then load the new version directly.

Whithout closing I open a new tab then go to the context whicih contains the plugin to test.

**Comment by offtherailz** [comment]
It is sufficient to uninstall and re-install the extension ( or edit the data dir as suggested by @landryb). 
Even re-saving a context is not strictly required, you can exit without saving, if you don't want to touch the context configuration. 

Then refresh (or open a new tab) to see the changes.
