### ISSUE TITLE
Error 431 Too Large GetMap GET request - POST request not supported

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#412]
Hi,

# Behavior

After some tests, we generate a 431 error with for each complexe polygone intersection. Same issue if we use a lot of attribute to filter a layer (more than 180 to filter a layer with many objectid).

![image](https://user-images.githubusercontent.com/16317988/129051490-0f8ec290-a105-47b0-9af3-931d5d1f6fce.png)

Indeed, the request seems to be Too Large.

You can try [with this request (geoserver URl to adapt)](https://portail-test.sig.rennesmetropole.fr/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng8&TRANSPARENT=true&LAYERS=app%3Atabou_v_oa_programme&STYLES=&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=false&CQL_FILTER=(INTERSECTS(%22shape%22%2CSRID%3D3857%3BPolygon((-193997.17778777733%206126332.27077152%2C%20-193538.55561806628%206127173.078082657%2C%20-193347.46304735332%206128281.4149927925%2C%20-193882.52224534957%206129160.440818072%2C%20-194685.11104234392%206130421.651784778%2C%20-195029.0776696272%206131415.333152485%2C%20-194952.64064134203%206132485.451548478%2C%20-194417.58144334579%206133440.914402042%2C%20-193653.21116049404%206133861.318057611%2C%20-192850.6223634997%206134090.629142466%2C%20-191016.13368465545%206134128.847656609%2C%20-190442.85597251664%206133937.755085896%2C%20-189869.5782603778%206133670.225486898%2C%20-189105.20797752604%206133288.040345471%2C%20-188531.93026538723%206132829.418175761%2C%20-187767.55998253546%206132370.79600605%2C%20-186238.81941683195%206131682.862751483%2C%20-184939.38993598393%206131606.425723198%2C%20-183831.05302584887%206131797.518293911%2C%20-181805.47177629173%206132103.266407051%2C%20-180467.82378130112%206132600.107090905%2C%20-178251.149961031%206133211.603317186%2C%20-175996.25762661832%206133249.821831329%2C%20-172480.15432550022%206132867.636689903%2C%20-170607.4471325134%206131988.610864623%2C%20-169651.9842789487%206130727.399897918%2C%20-169231.58062338023%206129351.533388785%2C%20-169002.26953852468%206127899.229851367%2C%20-168925.8325102395%206126867.329969517%2C%20-169040.4880526673%206125262.152375529%2C%20-169651.9842789487%206123160.134097686%2C%20-169957.73239208938%206122472.200843119%2C%20-170607.4471325134%206121172.771362271%2C%20-170798.53970322633%206119032.534570286%2C%20-170760.32118908374%206117847.760631866%2C%20-170072.38793451714%206113949.472189322%2C%20-170454.57307594304%206113108.664878185%2C%20-171218.9433587948%206111656.361340767%2C%20-171486.47295779292%206110395.150374061%2C%20-171562.9099860781%206108981.065350786%2C%20-171754.00255679103%206107261.232214369%2C%20-172059.75066993173%206105273.869478954%2C%20-172174.4062123595%206103783.347427393%2C%20-172824.1209527835%206101757.766177836%2C%20-173359.18015077972%206100878.740352557%2C%20-174620.39111748512%206100152.5885838475%2C%20-177639.6537347496%206097783.040707006%2C%20-177524.99819232186%206095451.711344308%2C%20-177524.99819232186%206093540.785637178%2C%20-177983.6203620329%206090292.211935059%2C%20-179244.8313287383%206088037.319600646%2C%20-181385.06812072324%206086661.453091513%2C%20-183716.3974834211%206086623.234577371%2C%20-185436.2306198376%206086776.108633941%2C%20-188417.27472295947%206087158.293775367%2C%20-189946.01528866298%206086890.764176369%2C%20-190519.29300080182%206086432.142006657%2C%20-191245.44476951097%206085400.242124807%2C%20-192124.4705947905%206084024.375615674%2C%20-193423.9000756385%206083795.06453082%2C%20-195487.69983933825%206084253.68670053%2C%20-196748.91080604366%206084941.619955097%2C%20-200685.41776273024%206087005.419718796%2C%20-203054.96563957073%206087846.227029933%2C%20-204660.1432335594%206087960.88257236%2C%20-207029.69111039987%206087502.26040265%2C%20-207908.7169356794%206087425.8233743645%2C%20-210125.3907559495%206087999.101086504%2C%20-210507.5758973754%206088457.7232562145%2C%20-211539.4757792253%206089451.404623922%2C%20-211807.0053782234%206090215.774906773%2C%20-212074.5349772215%206091553.4229017645%2C%20-213565.05702878244%206092776.415354327%2C%20-215781.7308490526%206093196.819009897%2C%20-217998.4046693227%206092241.356156332%2C%20-219641.800777454%206091094.800732055%2C%20-221094.10431487235%206090597.960048201%2C%20-222546.4078522907%206090597.960048201%2C%20-223348.99664928505%206090941.9266754845%2C%20-224151.58544627938%206091553.422901765%2C%20-224533.77058770528%206092317.7931846175%2C%20-224686.64464427563%206093387.91158061%2C%20-224686.64464427563%206094190.500377604%2C%20-224686.64464427563%206095031.307688741%2C%20-224839.51870084598%206095681.022429165%2C%20-225259.92235641443%206096407.174197874%2C%20-225794.98155441068%206097209.762994869%2C%20-226138.94818169397%206098050.570306006%2C%20-226100.72966755138%206099349.999786854%2C%20-226674.0073796902%206100649.429267702%2C%20-227170.84806354385%206103439.38080011%2C%20-225336.3593846996%206105847.147191092%2C%20-224419.1150452775%206104662.373252672%2C%20-224839.51870084595%206102751.447545543%2C%20-225068.82978570147%206100114.370069704%2C%20-224304.45950284973%206098509.192475716%2C%20-222469.9708240055%206097821.259221149%2C%20-220979.44877244454%206097859.477735291%2C%20-219756.45631988172%206098012.351791862%2C%20-217578.0010137542%206098662.066532286%2C%20-215323.1086793415%206099426.436815138%2C%20-214138.33474092127%206099502.873843423%2C%20-212953.56080250104%206099273.562758568%2C%20-211157.2906377994%206098814.940588856%2C%20-208214.46504882013%206098432.755447431%2C%20-207564.75030839612%206098585.629504001%2C%20-206838.59853968694%206099349.999786853%2C%20-206571.06894068883%206100114.370069704%2C%20-206494.63191240365%206101031.614409126%2C%20-206915.0355679721%206101413.799550553%2C%20-207450.0947659684%206101413.799550553%2C%20-208138.02802053496%206100916.9588667%2C%20-208443.77613367568%206100305.462640419%2C%20-208673.08721853117%206099846.840470706%2C%20-209361.02047309774%206099885.05898485%2C%20-210584.01292566056%206100764.084810129%2C%20-211119.07212365678%206101452.018064696%2C%20-212074.53497722148%206101910.640234407%2C%20-212762.46823178808%206102139.951319262%2C%20-214444.08285406197%206102216.3883475475%2C%20-215208.4531369137%206102025.295776835%2C%20-216049.26044805066%206101375.58103641%2C%20-216813.63073090243%206100534.773725274%2C%20-218304.15278246335%206099885.05898485%2C%20-221170.54134315747%206099770.403442422%2C%20-221667.3820270111%206099808.6219565645%2C%20-222126.00419672218%206100381.899668704%2C%20-222584.62636643322%206101795.984691979%2C%20-222546.40785229063%206103018.977144542%2C%20-222317.0967674351%206104203.751082962%2C%20-221629.16351286852%206106152.895304234%2C%20-221858.47459772404%206107643.417355795%2C%20-222431.75230986287%206109248.594949784%2C%20-223884.0558472812%206111618.142826624%2C%20-225068.82978570147%206112917.572307472%2C%20-226482.91480897722%206114484.531387319%2C%20-227094.4110352586%206115210.683156027%2C%20-227094.4110352586%206116548.331151018%2C%20-226291.82223826429%206117121.608863157%2C%20-225680.32601198286%206117159.8273773%2C%20-225107.04829984403%206116854.079264159%2C%20-224763.08167256074%206116127.92749545%2C%20-224648.42613013298%206115401.775726739%2C%20-224342.6780169923%206114752.060986317%2C%20-223807.61881899604%206114178.783274177%2C%20-223119.68556442947%206113643.724076181%2C%20-222622.8448805758%206113299.757448897%2C%20-221820.25608358148%206112497.168651903%2C%20-221361.63391387044%206111847.453911479%2C%20-220673.70065930384%206110242.27631749%2C%20-220520.8266027335%206109401.469006353%2C%20-220406.17106030573%206108293.132096219%2C%20-220291.51551787797%206106993.702615371%2C%20-220711.91917344643%206105082.77690824%2C%20-220864.79323001677%206104050.87702639%2C%20-220941.23025830195%206103248.288229397%2C%20-220903.01174415933%206102369.262404117%2C%20-220597.26363101864%206101681.32914955%2C%20-219527.14523502617%206101184.488465697%2C%20-218648.11940974667%206101222.706979839%2C%20-217463.3454713264%206102063.514290975%2C%20-216546.1011319043%206102751.447545542%2C%20-215628.8567924822%206103133.632686968%2C%20-214138.33474092124%206103324.725257681%2C%20-211959.87943479372%206103171.8512011105%2C%20-211080.8536095142%206102751.447545542%2C%20-210660.44995394573%206102216.388347546%2C%20-209246.36493066995%206101566.673607122%2C%20-208176.2465346775%206101566.673607122%2C%20-207564.7503083961%206102483.9179465445%2C%20-207564.7503083961%206103859.784455678%2C%20-208443.77613367562%206104777.0287951%2C%20-193997.17778777733%206126332.27077152))))&WIDTH=512&HEIGHT=512&BBOX=-78271.51696402207%2C6026906.8062295765%2C-1.5861587598919868e-9%2C6105178.323193597).

# Screenshot

![image](https://user-images.githubusercontent.com/16317988/129051407-ca658ad3-c3fe-4151-bd20-bc0d846b209c.png)

# Resolve

Do you think it's possible to use a POST request instead ?

**Comment by catmorales** [comment]
@tdipisa , could you please answer to @Gaetanbrl  because we are blocked on this functionnality (filter) and we need it to deploy in production some plugins using it.

**Comment by tdipisa** [comment]
@Gaetanbrl @catmorales all GetMap requests are GET requests in MS. Filters configured with the Filter Layer tool are applied to WMS requests through the CQL_FILTER query parameter, therefore there is the normal limitation in the number of characters allowed for URLs strings by browsers. 

MapStore doesn't support yet [GetMap requests via POST](https://docs.geoserver.org/latest/en/user/services/wms/reference.html#getmap)

**Comment by Gaetanbrl** [comment]
Thanks for your comment.

>  therefore there is the normal limitation in the number of characters allowed for URLs strings by browsers.

Indeed  this is what i found and written in a previous MS2 google group message : 
https://groups.google.com/g/mapstore-developers/c/YgyMn68Gcvk

> MapStore doesn't support yet GetMap requests via POST

It's unfortunate that GeoServer and OGC Specification let use POST request and MS2 don't offer this possibility...

But to go further, do you think MS2 community could be intereset by use GET or POST (not only GET request) ? What do you advise as MS2 dev ?

As written previously, we could try to realize a pull request.

**Comment by tdipisa** [comment]
@Gaetanbrl 

>But to go further, do you think MS2 community could be intereset by use GetMap with GET or POST (not only GET request) ? 

Yes, I think. In certain use cases it can be useful.

>What do you advise as MS2 dev?

In my opinion MS should be able to switch between GET to POST if requested (e.g. configured) in all cases where the URL exceeds a certain size. Let me check it quickly with other colleagues of the MS dev team so that I can provide you more precise info.

**Comment by Gaetanbrl** [comment]
@catmorales we wait @offtherailz review / merge. Need this PR for Tabou.

**Comment by Gaetanbrl** [comment]
I close. `miscSettings.maxURLLEngth` param works and fix this issue.
Thanks @tdipisa @offtherailz for help.
