### ISSUE TITLE
[Identify Tool] GetFeatureInfo request - increase the default value of feature_count

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#413]
I'd like to increase by default the value of feature_count. in the GetFeatureInfo request generated by the Identify tool.
**How to do it ?**
In mapfishapp the value is 1000, in mapstore it's 10.
Example of request on the same layer:
* In mapstore:
https://portail-test.sig.rennesmetropole.fr/geoserver/ows?service=WMS&version=1.1.1&request=GetFeatureInfo&exceptions=application%2Fjson&id=espub_esv:gev_bois__9&layers=espub_esv:gev_bois&query_layers=espub_esv:gev_bois&x=51&y=51&height=101&width=101&srs=EPSG:3857&bbox=-183261.614226961,6128262.782045326,-182805.67218742697,6128718.724084861&feature_count=10&info_format=application%2Fjson&ENV=
* In mapfishapp:
*https://portail-test.sig.rennesmetropole.fr/geoserver/ows?SERVICE=WMS&LAYERS=espub_esv%3Agev_bois&QUERY_LAYERS=espub_esv%3Agev_bois&STYLES=&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&EXCEPTIONS=XML&BBOX=-184078.166952%2C6128149.300027%2C-183411.731612%2C6129047.43511&FEATURE_COUNT=1000&HEIGHT=752&WIDTH=558&FORMAT=image%2Fpng&INFO_FORMAT=application%2Fvnd.ogc.gml&CRS=EPSG%3A3857&I=317&J=296

@tdipisa Can you answer me on this point?

**Comment by Gaetanbrl** [comment]
@catmorales have you try something like that ? 

https://github.com/geosolutions-it/MapStore2/issues/4238#issuecomment-536013484

--> localConfig default state
```
"mapInfo": {
    "enabled": true, // enabled by default
    "disabledAlwaysOn": false, // if true, disable always on setup
    "configuration": {
      "showEmptyMessageGFI": false // allow or deny the visiibility of message when you have no results from identify request
      "infoFormat": "text/plain" // default infoformat value, other values are "text/html" for text only or "application/json" for properties,
      "maxItems": 50
    }
  }
```

**Comment by catmorales** [comment]
@Gaetanbrl  Merci je vais essayer dans le config.json.

**Comment by Gaetanbrl** [comment]
After a test, `maxItems` inside localConfig default state (as explain above) doesn't work for me....

**Comment by catmorales** [comment]
bq.After a test, maxItems inside localConfig default state (as explain above) doesn't work for me..

Same thing for me with the parameter infoFormat . It doesn'nt work in localConfig.json but it works in config.json.
Thank you for feature_count it's ok in config.json !!

**Comment by Gaetanbrl** [comment]
> Same thing for me with the parameter infoFormat

Maybe not catched by MapStore and seems undefined in the store if you just set `maxItems` inside localConfig.json file.

**Comment by tdipisa** [comment]
@catmorales @Gaetanbrl 

>After a test, maxItems inside localConfig default state (as explain above) doesn't work for me....

**mapInfo** in localConfig establish only the initial state for new created maps. Therefore, setting maxItems there for exsting maps doesn't work because the saved map state (mapInfoConfiguration) is not overridden in that case. 

>Same thing for me with the parameter infoFormat . It doesn'nt work in localConfig.json but it works in config.json.

Yes, in geOrchestra the default map uses config.json for the map configuration (the same for the default map in app context).

We will improve anyway that configuration tier for the identify by centralizing the default config at plugin level in https://github.com/geosolutions-it/MapStore2/issues/5504
