### ISSUE TITLE
Feature editor doesn't handle geOrchestra's roles

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#414]
When configuring the attribute table with "editingAllowedRoles" options, we only have choice between "ADMIN" or "USER".

If we add some geOrchestra's defined roles, it not restrict the edit tools display.
As all connected user have the mapstore's "USER" role, add it to allowed roles means every connected user have edit tools displayed.

**Comment by landryb** [comment]
as seen in the call today, none of the mapstore plugins provide integration with georchestra roles for now..... upcoming improvement.

**Comment by catmorales** [comment]
yes it's not very friendly :/

**Comment by jusabatier** [comment]
I tried to use the current available configuration with the "Can view" and "Can edit" functions to find a solution.

I supposed that "Can view" activate the "USER" role and "Can edit" activate the "ADMIN" one.
But when testing it, it appears that not work.

@tdipisa Are the "Can edit" and "Can view" mapstore's permissions activating some mapstore's role that we can use in plugins configuration ?

**Comment by catmorales** [comment]
On my side I found that "can edit" applied on an application context allows the users of this context to modify the plans (delete, add,...)

**Comment by Gaetanbrl** [comment]
Hi,
some news about this issue ?

**Comment by jusabatier** [comment]
Fixed in : https://github.com/geosolutions-it/MapStore2/issues/9179
