### ISSUE TITLE
Better handle of context access restriction

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#415]
This is quite like https://github.com/georchestra/mapstore2-georchestra/issues/274 but aim to be more explicit.

Here is a list of usecases which are problematics because the users can't understand what happen :  

-> A user want to load a Context but forget to connect before
=> Mapstore display "Resource not found" and say that the context doesn't exists

It should redirect to login form if the user is anonymous and try access protected context

-> A user want to load a Context but doesn't have permission to access it
=> Mapstore display "Error loading context" and say that an unknown error occured

It should just say that the user is not allowed to access this context

### Note
Related MS issue - https://github.com/geosolutions-it/MapStore2/issues/9251

**Comment by jusabatier** [comment]
Any news about this ?

It still very uncomfortable for beginning users

**Comment by jusabatier** [comment]
When a user try to access a protected context and isn't already logged in,
he should be redirected to the Georchestra's CAS authentication page. 

You generally achieve it by add '?login' to the URL, but I don't know if it will work with the # in MS2 URLs

**Comment by pmauduit** [comment]
> but I don't know if it will work well with the # in MS2 URLs

I don't think it works with the GN urls either, which also use a '#'.

**Comment by landryb** [comment]
the 'error page' is properly displayed if a logged in `testuser` tries to access a map/context that is restricted to `MAPSTORE_ADMIN` role.

but as expected the **redirect to login if not logged in** feature isn't fully satisfying as the user will never come back to the page which he tried to access, which is the behaviour any normal sane user would expect.

**Comment by tdipisa** [comment]
@landryb thank you for the feedback

>but as expected the redirect to login if not logged in feature isn't fully satisfying as the user will never come back to the page which he tried to access, which is the behaviour any normal sane user would expect.

Do you mean due to [#261](https://github.com/georchestra/mapstore2-georchestra/issues/261)?

**Comment by landryb** [comment]
> @landryb thank you for the feedback
> 
> > but as expected the redirect to login if not logged in feature isn't fully satisfying as the user will never come back to the page which he tried to access, which is the behaviour any normal sane user would expect.
> 
> Do you mean due to [#261](https://github.com/georchestra/mapstore2-georchestra/issues/261)?

well that for what's after the anchor getting lost, yes - but besides that there's another annoying behaviour.

In a regular situation:
- you're on mapstore as anonymous
- you hit the login button in the georchestra header
- you get to the cas login page
- after logging in you get redirect to mapstore

here:
- you're on mapstore as anonymous
- you try to access a resource that is restricted
- you get redirected to the cas login page
- after logging in you get redirected to.. something else, whatever is configured as the 'georchestra homepage', be it `/header/` or `/geonetwork/` or even plain https://FQDN/ - you don't get redirected back to mapstore where you were
