### ISSUE TITLE
Set the visibility limits active by default on layers

### ISSUE THREAD

**Issue by offtherailz** [georchestra/mapstore2-georchestra#424]
At the moment when you add a layer on the map, if you want to set the **visibility limits** using the data from the server you have to manually open the layer settings and click on **refresh** button. 

https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/#display

With this changes you can configure the catalog to automatically get from capabilities these information and set it on the layer on layer add. (check if possible together with same operation done when setting available formats (png/jpg ...) or if need to create a custom side effect).

Configuration is "cfg.autoSetVisibilityLimits"

I suggest to create a custom side effect that does this operation on layer add under the conditions of:
- The layer is supported (WMS only)
- The URL to query is know
- Catalog is configured to do so. 

## Acceptance Criteria AC

- If I configured the option `autoSetVisibilityLimits` in `Catalog` services to true, and if I add a WMS layer wich has some visiiblity hints on capabilities for its default style, this values have to be automatically applied to the layer, in the same way I do when I explicitly click on refesh button in Display tab of layer settings
- If `autoSetVisibilityLimits` is false or not configured, the catalog should have the same current behavior. 
- The `autoSetVisibilityLimits` can also be configured from the Catalog UI for WMS service
- This is an enhancement for official MapStore

**Comment by catmorales** [comment]
Hello,
I installed this morning the latest version of mapstore on our test instance (latest tagged image) and I'm trying to set up this feature. 
So, I added in the "desktop" section of the localConfig.json :
```
{
				"name": "MetadataExplorer",
				"cfg": {
					"zoomToLayer": false,
					"autoSetVisibilityLimits": true,
					"wrap": true
				}
			},
```

But when loading layers that have a range of visibility scales, I still don't see the (i) indicator next to the layer in the TOC. Is there something more to do?

**Comment by catmorales** [comment]
Documentation is not updated on this functionnality : https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.MetadataExplorer

**Comment by dsuren1** [comment]
Hi @catmorales 

Please try this. I have updated issue description to avoid confusion.
```
catalog: {
     services: {
        "service_wms": {
            "url": "some_wms_url",
            "type": "wms",
            "title": "WMS",
            "autoSetVisibilityLimits": true
        }
    }
}
```
Configuration is done on the catalog services. It's a default configuration, as the visibility limits can be configured directly from the Catalog UI as shown in the image below for WMS service

![2021-12-21 10_09_54-MapStore HomePage](https://user-images.githubusercontent.com/26929983/146872005-84fa9c35-da1f-4a27-93ef-bfe7f56dc001.jpg)

Configuration documentation:
https://mapstore.readthedocs.io/en/latest/developer-guide/local-config/#catalog-tool-configuration

**Comment by landryb** [comment]
hmmm.. maybe my recollection is fuzzy, but i thought (from the previous discussions we had) it was also supposed to be a **global** setting/default settable, eg "*i want all loaded catalogs to have this flag set*" instead of having it to set it catalog per catalog.

**Comment by catmorales** [comment]
I agree with Landry and I do not have this option on a CSW catalogue.
![image](https://user-images.githubusercontent.com/4659829/146896087-4e5eba4d-0448-4c05-b23b-25cd08be0831.png)

**Comment by catmorales** [comment]
hi @dsuren1,  i configured WMS catalog as:

```
                                                "localgs": {
                                                        "url": "/geoserver/ows",
                                                        "type": "wms",
                                                        "title": "Géoservices",
                                                        "autoload": true,
                                                        "layerOptions": {
                                                        "tileSize": 512,
                                                                "format": "image/png8"
                                                        },
                                                        "format": "image/png8",
                                                        "autoSetVisibilityLimits": true
                                                }
                                        },

```

It doesn't work in our environment of portail-test.

**Comment by catmorales** [comment]
I will try ton configure it in config.json

**Comment by catmorales** [comment]
Yes, it works with WMS catalog but i agree with @landryb , it should be a global configuration.

**Comment by tdipisa** [comment]
@catmorales thank you for the feedbacks. Only two points:

1. Ok, what we can do is to add a config property at Catalog plugin level to have the autoSetVisibilityLimits option active by default when a new WMS catalog source is created (both from localConfig and app context wizard)
2. To be honest, the support for also CSW catalog sources (WMS layers added to MapStore from a CSW source) was not specified in the original requirements. We will provide also this one anway

**Comment by catmorales** [comment]
@tdipisa Thank you very much !
The new version of mapstore is very good. The test I did there were very good. There were a lot of evolutions/corrections. 
Thanks for all the work!

**Comment by tdipisa** [comment]
> @tdipisa Thank you very much !
> The new version of mapstore is very good. The test I did there were very good. There were a lot of evolutions/corrections.
> Thanks for all the work!

Thank you so much @catmorales! ;)

**Comment by tdipisa** [comment]
@catmorales, @dsuren1 is workign on it. We will deliver the updates after the Christmas break.

**Comment by catmorales** [comment]
Hello Tobia, Do you have news about [the two points above](https://github.com/georchestra/mapstore2-georchestra/issues/424#issuecomment-998668124)] ?

**Comment by catmorales** [comment]
Can you tell us how to apply this setting to all our pre-existing contexts ?

**Comment by landryb** [comment]
to me, if there's a global flag set in `localConfig.json` it should retroactively apply to all pre-existing contexts/maps.

**Comment by tdipisa** [comment]
@catmorales the work has been merged last days in our DEV and it is under testing. The reference MS issue is https://github.com/geosolutions-it/MapStore2/pull/7691. The description is self-explanatory, I think :)

**Comment by catmorales** [comment]
I have udated mapstore to 2021.02.xx on portail-test and the csw support is not working.

**Comment by catmorales** [comment]
Why did you close it ?  Did you backported the las corrections on 2021.02.xx ? I will deploy it newly on portail-test to morrow morning.

**Comment by tdipisa** [comment]
> @tdipisa Why did you close this issue ? Did you backported the lastcorrections on 2021.02.xx ? I will deploy it newly on portail-test to morrow morning.

I'm sorry, my fault. I'm going to reopen since we still have to check what you have reported [above](https://github.com/georchestra/mapstore2-georchestra/issues/424#issuecomment-1086073791).

**Comment by tdipisa** [comment]
@catmorales a fix has been merged on MS master today. Next week we will manage for the related backports also here.

**Comment by catmorales** [comment]
I just deployed it on portail-test and it works. Thank you

**Comment by tdipisa** [comment]
Ok @catmorales I'm going to close then.
