### ISSUE TITLE
Browse Contexts

### ISSUE THREAD

**Issue by offtherailz** [georchestra/mapstore2-georchestra#437]
Ability to also browse Application Contexts from Home plugin and edit them through the wizard according to the user permissions. Only admins will be able to create new contexts from the existing _/admin_ endpoint eg. https://portail-test.sig.rennesmetropole.fr/mapstore/#/admin.

![2021_12_20_12_24_23_Window](https://user-images.githubusercontent.com/1280027/146765100-34d90c38-5ebc-481e-8be9-f9bdb4f59791.png)

**Comment by tdipisa** [comment]
> Will it be possible, if the application context is public, that all users can consult it without being able to modify it?

@catmorales of course, as for the other resources in MapStore also app contexts follow the same permissions rules Can View/Can Edit
