### ISSUE TITLE
Make home page and editing for dashboard and geostories available for geOrchstra

### ISSUE THREAD

**Issue by offtherailz** [georchestra/mapstore2-georchestra#438]
## Requirements

New page integrated into geOrchestra listing the application contexts<sup>1</sup>, maps, dashboards and
geostories authorised to the current user or his group.
This page corresponds to an evolution of the mapstore2 home page.
Functional requests :
- accessible from /mapstore/#/maps already present in mapstore2geOrchestra
e.g. https://portail.sig.rennesmetropole.fr/mapstore/#/home/, 

- 4 tabs : Contexts (application contexts<sup>1</sup>), Thematic applications  (maps), Dashboards,
Geostories,
- the activation of the 4 tabs must be configurable by the administrator, allowing only
the desired tabs to be displayed,
- as in https://mapstore.geosolutionsgroup.com/mapstore/#/maps, there must be a
management of favourites,
- the geOrchestra banner must be present and usable on this page,
- the "Home" plugin must be added to mapstore2georchestra (configurable by the
administrator) to allow access to this page from the standard viewer and from
application contexts<sup>1</sup>.

Each instance of geOrchestra may or may not add a new link in the header to access this page
(this is up to the individual, not required in the developments).

> **note**   the original requirement asked for  https://portail.sig.rennesmetropole.fr/mapstore/#/maps/, but using the path "home" is more clear. 

## Implementation
There is already a page /maps where the home page is mounted. It is binded to the localConfig.json --> plugins --> maps

We have to : 
- [ ] Change entry in `localConfig.json` from "maps" to "home", and the same for the path in `appConfig`
- [ ] Remap almost the main plugins of the home page of MapStore in this context, 
    - Featured
    - CreateMap
    - Maps
    - Dashboards
    - Stories
- [ ] Taking care of issues with different layout
   - [ ] MapStore's header plugin should not be included, while geOrchstra has it's own header with the link to all the application. We have to properly manage the css to present it in the right way.     
   - [ ]  The search bar should appear in the right place (while the current `maps` entry presents the search plugin at the end).
- [ ]  <sup>1</sup> **Contexts** list is a separate plugin  in a this separate issue:  #437
- [ ] Support plugin home that the admins can include or not.

**Comment by offtherailz** [comment]
Note @tdipisa I renamed path #/maps with #/home/, that is easier to understand.

**Comment by tdipisa** [comment]
@offtherailz ok for me. Let's hear also from @catmorales

**Comment by catmorales** [comment]
It will be an address like https://portail.sig.rennesmetropole.fr/mapstore/#/home ?

For me it's ok and indeed more explicit.
I check with my colleagues to see if it doesn't have an impact on their infra setup.
 @landryb , @MaelREBOUX , your opinion ?

**Comment by landryb** [comment]
`mapstore#/home` is fine with me, no reason to invent anything else just for the pleasure of being different than mapstore upstream :)

**Comment by MaelREBOUX** [comment]
Let stay mainstream (sometimes but not too often :p) 

`mapstore#/home` is fine for me too

**Comment by tdipisa** [comment]
Ok, thank you @MaelREBOUX, @landryb and @catmorales. Below is what we will definitely provide for the home plugin.

1. Ability to browse existing Maps, Dashboards, GeoStories along with the possibility to create and search/filter them as it is for the standard MapStore and according the give permissions. Below a screenshot

![image](https://user-images.githubusercontent.com/1280027/146763863-41f3a7f9-c76b-41a5-bdb0-5c2f500a0c62.png)

2. Ability to also browse Application Contexts from Home and edit them through the wizard according to the user permissions (see #437)

**Comment by Gaetanbrl** [comment]
Is this /home page available from [last github ms2-geor action](https://github.com/georchestra/mapstore2-georchestra/actions/runs/1619533726) ?

**Comment by tdipisa** [comment]
@Gaetanbrl the work has not been merged yet. The PR (https://github.com/georchestra/mapstore2-georchestra/pull/445) is in pending review

**Comment by Gaetanbrl** [comment]
my bad @tdipisa ! I'm to eager to see the result :)

**Comment by landryb** [comment]
fwiw testing a build from master, i've updated `localConfig.json` (will require a PR for 7279757 and b6dcdf like i did in georchestra/datadir#224), and visiting `/mapstore/#/home/` properly shows the homepage with the 4 maps/dashboards/geostories/contexts tabs, with the georchestra header. Nice stuff ! Will play with it..

Minor nit: while testing i noticed that if there was nothing to display for a tab, the icon/pictogram was huge and thus added an accordion to the page, forcing the user to scrolldown to see the 'Aucune carte disponible' label, same thing for other tabs with no entries.

Something to fix/improve ? Afaict the glyph/icon has a > 680px font-size ...

![image](https://user-images.githubusercontent.com/3421760/151365183-975000c5-c5a2-4317-926e-73ea06400be9.png)

**Comment by tdipisa** [comment]
Thank you @landryb

> Minor nit: while testing i noticed that if there was nothing to display for a tab, the icon/pictogram was huge and thus added an accordion to the page, forcing the user to scrolldown to see the 'Aucune carte disponible' label, same thing for other tabs with no entries.

I will ask devs to check

> Something to fix/improve ? Afaict the glyph/icon has a > 680px font-size

This is the size MS side. Probably for this project, due to the georchestra header, it should be reviewed a bit more. I will ask devs to check this too. Thank you.

**Comment by Gaetanbrl** [comment]
@landryb same for us, icon is very large (font-size 760px for my screen)

**Comment by Gaetanbrl** [comment]
When i click on "new map" button, there is a redirection to https://ifl.francophonelibre.org/mapstore/#/viewer/openlayers/new

But i can't save the map, it seems just read the `new.json` but don't open `contextCreator`. Is it the normal behavior ?

![newmap](https://user-images.githubusercontent.com/16317988/151373242-6853ceca-74d4-497d-8ff7-1e5503b0c339.gif)

**Comment by landryb** [comment]
yes i think its for a new *map*, not a new *context* for which you'd manually go to /admin/ ?

i wonder if the georchestrea header height isnt conflicting with the default layout for the new dashboards/geostory page. scrollbar on all pages..
