### ISSUE TITLE
add complete theme for new context

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#447]
We are able to select and custom default availables themes : 

![image](https://user-images.githubusercontent.com/16317988/147577382-598e6b57-b1ff-487a-82e7-77434bf52299.png)

The question is about add new theme.

To create a new theme named `purple` we have build a new war with a new theme  as  explain by [the doc](https://mapstore.readthedocs.io/en/latest/developer-guide/customize-theme/) (add /purple folder in `mapstore2-georchestra/themes`)

Now, we have new files inside `webapps/mapstore/dist/themes/` like that : 

![image](https://user-images.githubusercontent.com/16317988/147578454-9a9539a4-dc79-4428-8f94-1698744f679e.png)

Next, we add in datadir localConfig.json the contexteCreator config :

```
               "themes":[{
                {"id":"purple","type":"link","href":"dist/themes/purple.css"}
              }]
```

But the purple theme is not display in available themes list.

If we open the console to change the default css file link (in <head>) by the new purple css file link (or whatever) it works and the theme is correctly apply.

So, a config part seems missing to display our purple theme name in available themes list (we juste have `select...` and `dark`).

**Question :** 
What is wrong ? What is the correct process to create a full custom theme from existing default or dark theme ?

Thanks.

**Comment by allyoucanmap** [comment]
> What is wrong ? What is the correct process to create a full custom theme from existing default or dark theme ?

Hi @Gaetanbrl , I noticed that your configuration is using double braces `{{` `}}` and this should not be a valid JSON configuration.
Could you try with the following configuration?
```js
"themes": [ { "id":"purple","type":"link","href":"dist/themes/purple.css" } ]
```

**Comment by Gaetanbrl** [comment]
thanks @allyoucanmap i havn't see double braces... 🙈

After follow migration guide and fix braces, i can see and select custom themes insert in localConfig.

Well, this config display : 

```
"themes": [ 
     { "id":"purple","type":"link","href":"dist/themes/purple.css" },
     { "id":"dark","type":"link","href":"dist/themes/dark.css" } 
]
```

![image](https://user-images.githubusercontent.com/16317988/148531777-97ce13cd-9865-49b5-97f7-e71429e50a89.png)

**Comment by Gaetanbrl** [comment]
I will test now if color are correctly apply and close this issue or return a new comment.

**Comment by Gaetanbrl** [comment]
@allyoucanmap is it possible to create a theme inside datadir instead of webapp folder ?

Could you be more specific about the folder to target if i want to add new custom mapstore theme (is it the good way to push css files into webapp/mapstore/dist/themes) ?

Thanks.

**Comment by tdipisa** [comment]
Hi @Gaetanbrl let me answer to this. At the moment there is no way to externalize custom themes in MS data dir. This is an improvement for the future, we have opened [this issue](https://github.com/geosolutions-it/MapStore2/issues/7709) to keep track of it.

**Comment by Gaetanbrl** [comment]
@tdipisa we have created a project to try to build theme without build mapstore2-georchestra war (more fast).

https://github.com/jdev-org/mapstore2-themes

We can build css file from less and use it as context theme, but mapstore2 seems override css file by `default.css` rules.
This work is in progress and some file seems missing (font files, react-draft-wysiwyg.css file, ...).

**Comment by tdipisa** [comment]
@Gaetanbrl good to know, that's maybe something we will be able to integrate in MS later. The direction is more or less this.

**Comment by Gaetanbrl** [comment]
at this time, only default build create css that works fine... i'm not less / style processor expert :)
