### ISSUE TITLE
Document how to add home to georchestra

### ISSUE THREAD

**Issue by offtherailz** [georchestra/mapstore2-georchestra#459]
We need to document how to enable home page.

We did it by editing header.war `index.jsp` adding this entry ( in our demo is added near MapStore entry.)

```
<!-- MapStore home -->
        <c:choose>
            <c:when test='<%= active.equals("mapstore-home") %>'>
            <li class="active"><a href="/mapstore/#home">MapStore Home</a></li>
            </c:when>
            <c:otherwise>
            <li><a href="/mapstore/#home">MapStore Home</a></li>
            </c:otherwise>
        </c:choose>
```

**Comment by tdipisa** [comment]
@catmorales we have to discuss this during the next meeting. Thank you.

**Comment by landryb** [comment]
or do a PR to solve the above issue ? no need for documentation imo.. just update the upstream header ;)

**Comment by tdipisa** [comment]
@landryb 
> or do a PR to solve the above issue ? no need for documentation imo.. just update the upstream header ;)

@landryb we know that the home page must be an option, not enabled by default, we just need to agree/discuss on this.

**Comment by offtherailz** [comment]
@landryb there is an issue that happens when you refresh the pages in a dashboard or geostory, not in other case. Can you figure out the reason ? Maybe some error when parsing jsp. 

e.g. 
Open this: 
https://georchestra.geo-solutions.it/mapstore/#/dashboard/3613

**Comment by catmorales** [comment]
@pmauduit can you help us on this ?
- the best option to integrate mapstore home page to the header
- the issue with [dashboard and stories](https://github.com/georchestra/mapstore2-georchestra/issues/459#issuecomment-1027017742). I will update mapstore this week on portail-test and we  will be abble to test it into our configuration.

**Comment by landryb** [comment]
> @landryb there is an issue that happens when you refresh the pages in a dashboard or geostory, not in other case. Can you figure out the reason ? Maybe some error when parsing jsp.
> 
> e.g. Open this: https://georchestra.geo-solutions.it/mapstore/#/dashboard/3613

that dashboard isnt available to non-connected users, so im seeing the dashboard tutorial (after a red popup saying it cant load the dashboard) and right now i dont see the georchestra header .. is that the issue you're referring to ?

Either way, im not sure many installations keep the default header, so it's not a 'big deal'. Having `#/home` linked in the default header (with `cartes` for the french translation ?) would just help its discoverability.

**Comment by landryb** [comment]
> @landryb there is an issue that happens when you refresh the pages in a dashboard or geostory, not in other case. Can you figure out the reason ? Maybe some error when parsing jsp.
> 
> e.g. Open this: https://georchestra.geo-solutions.it/mapstore/#/dashboard/3613

i've been able to reproduce the issue on my local instance - it's way outside my expertise area :)

looking quickly in the browser console, it seems when you reload the dashboard (or just the top iframe) it tries to load `/mapstore/header.html` in the top iframe while it should be `/header/` ? this seems to have changed in 52b28bc1 but `index.html` was unused so far ? i totally dont understand how this url routing works.

**Comment by landryb** [comment]
@offtherailz adding `"Header"` plugin to geostory/dashboard configs in `localConfig.json` fixes that issue for me, i have the proper header when reloading a dashboard.

**Comment by catmorales** [comment]
I'll try tomorrow  to appli this on portail-test thanks  @landryb

**Comment by catmorales** [comment]
Cf https://groups.google.com/g/georchestra-dev/c/JchEAPpc0lE/m/KLHq04ScAwAJ?utm_medium=email&utm_source=footer to discussion about the  topic of this Issue : "how to add home to georchestra"

**Comment by tdipisa** [comment]
@catmorales 

>@offtherailz could you please let your dashboard example public , please ?

I'm who created the dashboard. It is now public [here](https://georchestra.geo-solutions.it/mapstore/#/dashboard/3613).

**Comment by Gaetanbrl** [comment]
> adding "Header" plugin to geostory/dashboard configs in localConfig.json fixes that issue for me

@landryb could you share a piece of code as example please ?

**Comment by landryb** [comment]
```
      "dashboard": [{
        "name": "OmniBar",
        "cfg": {
          "containerPosition": "header",
          "className": "navbar shadow navbar-home"
        }
      }, "Login", *****"Header"*****, "Language", "NavMenu", "DashboardSave", "DashboardSaveAs", "Attribution", "Home", {
...
      "geostory": [
       *****"Header"*****,
        {
          "name": "OmniBar",
          "cfg": {
            "containerPosition": "header",
            "className": "navbar shadow navbar-home"
          }
        },
```

**Comment by Gaetanbrl** [comment]
Thanks !
