### ISSUE TITLE
Feature Attribute Popup - Floating Identify tool

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#46]
The basic Identify functionalities required for the [Identify tool](https://github.com/georchestra/mapstore2-georchestra/issues/44) must be allowed also using a floating panel (popup):

- Once the tool is activated, a floating panel appears automatically (after some delay) when the mouse hover over a map object. The floating panel disappears automatically as soon as the mouse moves
- The size of the floating panel should not entirely cover the map so its dimension should significantly less than the size of the map

For this issue we can re-use the Identify popup provided with [this PR](https://github.com/geosolutions-it/MapStore2/pull/4971) in MapStore as it is including additional enhancements for the **mouse hover** functionality. In the same way of #44 the Identify popup tool must be available also for only layers selected in TOC.

**To confirm**
@offtherailz, for the Identify popup component we can consider on having enabled both interactions at the same time but making them mutually exclusive:

1. Click on map: immediatelly perform an Identify request (mouse hover interaction automatically disabled in that case until the popup is closed or something similar)
2. Mouse hover over a map object: performs an Identify request after a certain delay (configurable by plugin configuration)

**Comment by offtherailz** [comment]
We should be able to maintain both the interactions.I suggest to set this tool to work with mouse hover, default behavior can be changed via configuration. We can toggle from active(hover) to explicit(click) from a button in the UI (we should evaluate if it can be placed inside the popup, in settings or in other places)

**Comment by ElenaGallo** [comment]
@gitcontributor 

- [ ] Triggering hover over the map of the Identify tool does not have to be active if the user is using the measurement/annotation tool

*How to reproduce*
- Enable the hover for Identify tool
- Click on Burger Menu
- Click in Annotatotion
- Click on +
- click on Add geometry
- click on Marker
- click on map (wait a few seconds)

*Current Result*
Waiting a few seconds on the clicked point the popup opens and the new marker panel closes

- [ ] If the trigger hover over the map is activated, the identify marker is visible by clickung on the map 

![identify marker](https://user-images.githubusercontent.com/56537133/80380035-42cb0380-889f-11ea-8d54-2a36928469a1.gif)

*How to reproduce*
- Enable the hover for Identify tool
- Click on a map

*Current Result*
The identify marker appears

- [ ] If the mouse point is too close in the menu bar, sidebar, toc, burger menu) the pop-up that opens is not completely visible

![NOVISIBLE](https://user-images.githubusercontent.com/56537133/80380048-478fb780-889f-11ea-9d8e-14eb79ba944b.gif)

*How to reproduce*
- Enable the hover for Identify tool
- Hover over the map near same tool

*Current Result*
The identify popup is not completely visible
