### ISSUE TITLE
Pedestrian view - no shooting date for the photo

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-georchestra#462]
Hello.

While testing the all new pedestrian / streetview plugin I note that the shooting date is not present in the bottom right of the window :

![image](https://user-images.githubusercontent.com/6370443/150953519-9e89dbe3-02d1-4194-9b5e-db150951dd72.png)

while it is present in the Google maps application.

![image](https://user-images.githubusercontent.com/6370443/150953586-f2551ad6-90c1-4c90-83c9-afa390af81e4.png)

Is it a limitation of the API or there is possibility to configure that ?

**Comment by MaelREBOUX** [comment]
Found it : https://developers.google.com/maps/documentation/javascript/reference/street-view#StreetViewPanoramaOptions.imageDateControl

One must add `imageDateControl: true` in the parameters for the panorama.

**Comment by MaelREBOUX** [comment]
It is clear that our customers will ask for us for this feature.

Please @tdipisa could you consider to add this option as default in the configuration ?

**Comment by tdipisa** [comment]
@offtherailz can you please check this. It should be already possible as far as I know.

**Comment by tdipisa** [comment]
@MaelREBOUX 
as reported by @offtherailz it is possible but this requires few more development to allow configuring native properties. Event if it is not part of the requirements for this MS tool, I've asked @offtherailz to develop this and a PR has been raised in MS https://github.com/geosolutions-it/MapStore2/pull/7783 to control the panorama options. Consider that with this you will be able to control only simple native panorama options. I hope this is enough. As soon as tested MS side we will update the georchestra downstream project as well.

**Comment by tdipisa** [comment]
@MaelREBOUX requested changes have been also backported to the stable branch
