### ISSUE TITLE
Layer Editing - Editing tool

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#48]
This extension allows to edit features on the map through the WFST protocol. Different utilities of this extension allow to create, edit and delete features in the map when the corresponding layer in TOC is selected:

- Create: if activated allows to create a new geometry by drawing it on the map (a specific drawer is activated according to the layer geometry type). Once the geometry is drawn, a panel appears to fill the feature attribute values (the available attributes correspond to the feature type schema) and then the user can save the new feature
- Edit: if activated allows to select a geometry on the map. The panel containing the feature attributes appear to edit related values and also the geometry on map can be edited in the same way of the above point
- Delete: if activated allows to select a feature on map to delete it

For this issue we can improve the existing [Attribute Table tool](https://mapstore.readthedocs.io/en/latest/user-guide/attributes-table/) in MapStore. What is currently missing there, is the capability to select a feature (and the corresponding record/s in table) directly clicking on map.

**Comment by offtherailz** [comment]
We should allow to filter data by click, so you can select data from map (in edit mode) and edit (one of the result, if more than one feature were in the same point clicked). 

Evaluate during development if the user has a better experience by auto-selecting features during or not, because the feature of showing filtered data is provided also by the "map sync" functionality already shows only the data filtered (using WMS). 
As an alternative disable mapsync in this context.

**Comment by MaelREBOUX** [comment]
Could you point to a doc for the "map sync" functionality please ? If it exists. Thanks.

**Comment by tdipisa** [comment]
Hi @MaelREBOUX, the "map sync" utility is documented inside the Attribute Table documentation [here ](https://mapstore.readthedocs.io/en/latest/user-guide/attributes-table/#set-filters)

**Comment by MaelREBOUX** [comment]
Thank you : it is more clear. The sync table filter --> map is a powerfull tool.

Another question.
Could you confirm me that if you want to edit an object on the map : you must know its primary key to select (or filter it) in the table ?

I mean : currently you cannot clic on the map to select the object you want to edit. You currently have to select it threw the table.
Right ?

**Comment by tdipisa** [comment]
> Thank you : it is more clear. The sync table filter --> map is a powerfull tool.

Good, thank you.

> Another question.
> Could you confirm me that if you want to edit an object on the map : you must know its primary key to select (or filter it) in the table ?

Yes, I confirm it.

> I mean : currently you cannot clic on the map to select the object you want to edit. You currently have to select it threw the table.
> Right ?

Currently yes, but what we will provide for this issue is exactly to add the possibility to select an object in map too instead of necessarily select the record in table. Take a look at the description for this that reports the following:

>For this issue we can improve the existing Attribute Table tool in MapStore. What is currently missing there, is the capability to select a feature (and the corresponding record/s in table) directly clicking on map.

**Comment by MaelREBOUX** [comment]
>Currently yes, but what we will provide for this issue is exactly to add the possibility to select an object in map too instead of necessarily select the record in table. Take a look at the description for this that reports the following:

>>    For this issue we can improve the existing Attribute Table tool in MapStore. What is currently missing there, is the capability to select a feature (and the corresponding record/s in table) directly clicking on map.

Perfect !

**Comment by tdipisa** [comment]
@vlt1 Moving it back to ready.

If I edit a feature by selecting it in the Attribute Table with a click on the map an error occurs (gray page with reload button) but the feature is properly saved, this happens only if also the geometry is modified: the normal editing with selection in grid works.
		
## How to reproduce

- Open this context: https://georchestra.geo-solutions.it/mapstore/#/context/MapStoreTest49
- Try to edit a feature by moving a point and save
