### ISSUE TITLE
Layer Editing - Attribute Editor

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#49]
In edit mode within the attribute panel, each attribute field must provide the following if configured:

- Support of coded values (i.e. in a form of drop-down lists) 
- Validation of attribute values (format, min / max)

Coded values, validation format and min/max limits can be defined by the administrator inside the plugin configuration during the viewer context creation.

These kind of support is layer dependent, this means that inside the attribute table configuration the administrator must include specific configuration properties for each layer for which he wants to provide the above (coded values and validations).

Issue in MapStore: 
https://github.com/geosolutions-it/MapStore2/issues/5230

**Comment by offtherailz** [comment]
We have custom editor options:
See this dependent project.
https://github.com/geosolutions-it/MapStore2-C040/blob/master/localConfig.json#L368

where you define RULES (regex that apply identify the layer and the attribute to apply)
andeach rule can use a custom editor. 

They have a custom editor called "AddressesEditor" in their installation.
In MapStore we have only DropDownEditor that can be configured with a fixed list of values.
We can add a NumberEditor that can be used to define min and max, and a FormatEditor that checks if the content matches a regex.

**Comment by MaelREBOUX** [comment]
As seen this morning I find that using the configuration of the attribute table plugin is more suitable for my personnal use cases.

> These kind of support is layer dependent, this means that inside the attribute table configuration the administrator must include specific configuration properties for each layer for which he wants to provide the above (coded values and validations).

Need to test ;)

**Comment by offtherailz** [comment]
I report some additional information about the meeting:
 - We will check if it is possible to add also initial default values for new rows, because this task was not foreseen in the original program
 - @MaelREBOUX can you provide us a sample dataset, with write permission and all the data types you need to support, and also the constraints on values for each attribute, so we can ensure that all the use cases are covered? thank you very much

**Comment by MaelREBOUX** [comment]
@offtherailz @tdipisa 

I still cannot correctly set up the permissions for obtain a WFS layer edited by anyone (ie not authentificated).
I wrote a message to the mailing list for support. Could you help ?

**Comment by tdipisa** [comment]
@MaelREBOUX I will check it tomorrow, thank you anyway.

**Comment by tdipisa** [comment]
@MaelREBOUX 

>I still cannot correctly set up the permissions for obtain a WFS layer edited by anyone (ie not authentificated).

I saw that in our DEV instance of geOrchestra there is a specific security rule at WFS service level that prevent other users (also anonymous) to write data through WFS

![image](https://user-images.githubusercontent.com/1280027/79852920-a056e000-83c7-11ea-83c5-aef379a9f95c.png)

I'm quite confident that you have something similar in your public-test instance.
Therefore I don't think that you can provide write access to us on **test:mapstore_test**.

Maybe you can share an export of the dataset in SHP format? If you can do that we can publish it in our DEV instance.

**Comment by MaelREBOUX** [comment]
Sad news but logical for geOrchestra : need to be authentificated for this kind of work.

From our point of view it is important to test in the conditions of production, ie : table with constraints.

So... I think you have a PostGIS database on the demo platform ?
If yes : could you create the layer described above : https://github.com/georchestra/mapstore2-georchestra/issues/49#issuecomment-614747779

**Comment by tdipisa** [comment]
@MaelREBOUX 
>Sad news but logical for geOrchestra : need to be authentificated for this kind of work.
Of course, that's exactly what I supposed in my previous comment.

>From our point of view it is important to test in the conditions of production, ie : table with constraints.

OK

>So... I think you have a PostGIS database on the demo platform ?
If yes : could you create the layer described above : #49 (comment)

OK, let's try with this

**Comment by randomorder** [comment]
@tdipisa 
I created a database and table on our DEV environment. I just had to tweak a little the creation script (we don't have a `bdu` tablespace or a `urba_foncier` schema):
```
geoserver=> CREATE TABLE mapstore_test
(
    id integer NOT NULL DEFAULT nextval('mapstore_test_id_seq'::regclass),
    att_integer integer,
    att_integer_constr integer NOT NULL,
    att_long numeric,
    att_varchar character varying(50) COLLATE pg_catalog."default" DEFAULT ''::character varying,
    att_varchar_constr character varying(50) COLLATE pg_catalog."default" DEFAULT ''::character varying,
    att_text text COLLATE pg_catalog."default",
    att_text_constr text COLLATE pg_catalog."default",
    att_url text COLLATE pg_catalog."default",
    att_boolen boolean,
    att_date_iso date,
    att_date_timestamp timestamp without time zone DEFAULT now(),
    geom geometry(Point,3948),
    CONSTRAINT mapstore_test_pk PRIMARY KEY (id),
    CONSTRAINT att_varchar_constr_dom CHECK (att_varchar_constr::text = ANY (ARRAY['Non renseigné'::text, 'Publicité'::text, 'Pré-enseigne'::text, 'Enseigne'::text])),                                                                                                                                                                           CONSTRAINT att_integer_constr_check CHECK (att_integer_constr < 5),
    CONSTRAINT att_text_constr_dom CHECK (att_text_constr = ANY (ARRAY['non renseigné'::text, 'permanent'::text, 'temporaire'::text]))
);
CREATE TABLE
```

More detail in the doc for the DEV server. The layer is published [here](https://georchestra.geo-solutions.it/geoserver/test/wms?service=WMS&version=1.1.0&request=GetMap&layers=test%3Amapstore_test&bbox=1102438.8273905618%2C7089682.753276674%2C2097494.099859779%2C7340564.439127635&width=768&height=330&srs=EPSG%3A3948&format=application/openlayers)

Any issues let me know

**Comment by tdipisa** [comment]
@randomorder 
Thank you so much for this. You forgot to include this constraint:

`CONSTRAINT att_integer_constr_check CHECK (att_integer_constr < 5),`


@offtherailz @vlt1 
I've pepared[ this context ](https://georchestra.geo-solutions.it/mapstore/#/context/MapStoreTest49) in our DEV where I've populated the layer with some points

**Comment by tdipisa** [comment]
@MaelREBOUX I think we are ready now, thank you.
