### ISSUE TITLE
Show Layer Metadata - Layer metadata

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#50]
As part of the TOC utilities, this tool can be activated for the selected layer. A modal is shown containing the following metadata information retrieved by the CSW catalog configured by the administrator for the layer:

- title
- abstract
- preview
- scope (? to clarify)
- genealogy (lineage)
- creation date
- revision date
- link to the catalog to access the detailed sheet

**Comment by tdipisa** [comment]
@landryb and @catmorales I think that we need some clarifications for this task. MapStore supports Dublin Core for CSW requests. This means that when you select a CSW source type from the catalog tool, MapStore performs a GetRecords request to retrieve the list of metadata records in DC with related metadata properties, then these metadata properties can be used in MS to:

- Show metadata information for each catalog's item directly in the catalog tool list: [here](https://mapstore.readthedocs.io/en/latest/user-guide/catalog/#metadata-templates) the online 
documentation

- If a layer is added to the TOC from a CSW source, MS maintains the URL of the CSW catalog endpoint in the layer configuration so if you select that layer in TOC  a button appears (if the related plugin configured) inside the  TOC's toolbar ready to be clicked: if you click on this button a modal opens reporting the metadata information related to the layer 

As far as I know not all the metadata properties reported in the issue description are available in DC, so I need the have the following clarified as soon as you can:

- Can you please clarify if the purpose of this tool is to support both DC and iso19115-39? Can we simply show in MS what is available in DC by including anyway also a link to the original catalog to access the detailed sheet? If we cannot do that we will probably need to include in [Layer Settings](https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/) a new input field (available only to admin users) containing the metadata URL so it can be user to retrieve the metadata in the desired format: MS will need to be improved then to extrapolate needed metadata properties from the catalog's response using xpath
- Can you please specify the xpath of the metadata properties reported in the description, just to prevent misunderstanding

**Comment by landryb** [comment]
@MaelREBOUX should know, i'm not sure dublin core was a target. In the existing mapfishapp, we're used to get metadata url via the value configured within geoserver for the layer, both in XML and HTML forms..

**Comment by mbarto** [comment]
@landryb @catmorales @tdipisa there is some documentation on how to implement a custom template, using a property of the TOC plugin (metadataTemplate). You can find it here: https://mapstore.geo-solutions.it/mapstore/docs/api/plugins#plugins.TOC

That said, the usage of this functionality is currently available only for dublin core, because the MapStore API and related parser for CSW only supports that.

**Comment by tdipisa** [comment]
@offtherailz waiting for @MaelREBOUX feedback, please enable for now the layer metadata plugin that we already have.

**Comment by catmorales** [comment]
I don't know if it can help you but we'd like to have the same fucntionnality as in mapfishapp :
![image](https://user-images.githubusercontent.com/4659829/77933284-eaf4a900-72ae-11ea-9098-33168f6277c9.png)
https://georchestra.geo-solutions.it/mapfishapp/map/47388bc483069f60104b12903db7a200

**Comment by MaelREBOUX** [comment]
Sorry sorry for my late answer.


I think we have a misunderstanding on what we want to have as 'layer metadata' and where we want to see this infos.

Here I will answer only for CSW that is for me the first user case.


> Show metadata information for each catalog's item directly in the catalog tool list

OK but here we need to muscle the metadatas informations. We need this pattern by default

```
${title}

Description
${abstract}

But
${purpose}

Généalogie
${source}

Dates
création : dd/mm/yyyy  - révision : dd/mm/yyyy
```


> If a layer is added to the TOC from a CSW source, MS maintains the URL of the CSW catalog endpoint in the layer configuration so if you select that layer in TOC a button appears (if the related plugin configured) inside the TOC's toolbar ready to be clicked: if you click on this button a modal opens reporting the metadata information related to the layer

In understand this functionnality is accessible by editing the layer properties. There we can manage a tooltip (I test it).

This is not as simple as we want. User should have a quick and fast access to the metadata.

So I propose to create a new button (with other buttons when you select a layer in the TOC) named "MD".
By clicking this button it opens a new "popup" in the center of the screen. This object will show the metadata content (as ISO-19139) :

* title (/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString)
* abstract (/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:abstract/gco:CharacterString)
* purpose (/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:purpose/gco:CharacterString)
* source (/gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:lineage/gmd:LI_Lineage/gmd:statement/gco:CharacterString)
* created date (/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/gmd:CI_Date/gmd:date/gco:Date + codeListValue="creation" )
* last revision date (/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/gmd:CI_Date/gmd:date/gco:Date + codeListValue="revision" )
* points of contact (severals) (/gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:pointOfContact/gmd:CI_ResponsibleParty)


Maybe we need here a point by telephone ?

**Comment by catmorales** [comment]
we can have a point about it on the next meeting

**Comment by tdipisa** [comment]
> we can have a point about it on the next meeting
@catmorales @MaelREBOUX yes, let's discuss this during the next meeting on Thursday

**Comment by tdipisa** [comment]
Rennes Métropole usually configures Metadata links directly in the GeoServer layer configuration (those links are present inside the GetCapabilities response). GeoSolutions will improve the existing Layer Metadata tool to make it more configurable. The aim is to retrieve the metadata XML (in iso19139 format) by using the metadata URL present in the WMS GetCapabilities response and parse it with a new template that extrapolates the relevant metadata properties to show through xpath: 

| Metadata property | xpath |
|---|---|
title | /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:title/gco:CharacterString
abstract | /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:abstract/gco:CharacterString
purpose | /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:purpose/gco:CharacterString
source | /gmd:MD_Metadata/gmd:dataQualityInfo/gmd:DQ_DataQuality/gmd:lineage/gmd:LI_Lineage/gmd:statement/gco:CharacterString
created date | /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/gmd:CI_Date/gmd:date/gco:Date + codeListValue="creation"
last revision date | /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:citation/gmd:CI_Citation/gmd:date/gmd:CI_Date/gmd:date/gco:Date + codeListValue="revision"
points of contact (all of the available ones inside the medatata) | /gmd:MD_Metadata/gmd:identificationInfo/gmd:MD_DataIdentification/gmd:pointOfContact/gmd:CI_ResponsibleParty

If a layer is added to the map from a CSW source instead, the existing tool’s behaviors are maintained but using the new template to present iso19139 metadata properties instead of the DC one as it currently does.
Also a link to the original metadata catalog page will be included in the Layer Metadata modal.

**Comment by MaelREBOUX** [comment]
https://public.sig.rennesmetropole.fr/geoserver/
espub_mob:gev_ajeu

![image](https://user-images.githubusercontent.com/6370443/80085383-6ec14e80-8558-11ea-999f-c682afc7dffa.png)

**Comment by tdipisa** [comment]
@MaelREBOUX yes I think, thank you.

**Comment by vlt1** [comment]
> If a layer is added to the map from a CSW source instead, the existing tool’s behaviors are maintained but using the new template to present iso19139 metadata properties instead of the DC one as it currently does.

@tdipisa What do you mean by "existing tool's behaviors are maintained"? What behaviors?

**Comment by tdipisa** [comment]
@vlt1 moving it back to in ready. As specified in the original issue description

>Also a link to the original metadata catalog page will be included in the Layer Metadata modal.
