### ISSUE TITLE
Lots of commits not in master but only in stable branch 2021.02.xx

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#502]
@catmorales I've just noticed there are [commits in stable branch 2021.02.xx ](https://github.com/georchestra/mapstore2-georchestra/commits/2021.02.xx) provided by @jmbourdaret during March that are not present in master branch.

This way, when a new stable branch will be created in the future from the master one, these commits will be lost. The usual practice is to commit new updates in master branch first to backport them to a stable branch in a second time, according to the release needs and plans, after these have been tested and verified in master.

I've opened this issue just to point out this and to be sure commits provided by @jmbourdaret are effectively needed ONLY for the stable branch 2021.02.xx.

**Comment by landryb** [comment]
you're 100% right, even if those commits only target `.github/workflows/mapstore.yml` (and were related to https://github.com/georchestra/georchestra/issues/3501) they should also be in master - as i think some of the bits also apply to master. @jmbourdaret ?

**Comment by catmorales** [comment]
Thank you @tdipisa to notice it.

**Comment by pmauduit** [comment]
Every commits from Jean-Marc are indeed targeting the github action workflow file. I guess it should be safe to take the version from the the 2021.02.x branch then create a PR on master out of it. It does not seem necessary to keep the history of these commits in the master branch.
