### ISSUE TITLE
Identify tool not enabled by default

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#505]
## Environment
**Site :** https://portail-test.sig.rennesmetropole.fr
**Version mapstore2-georchestra:**  https://github.com/georchestra/mapstore2-georchestra/commit/373726f89e47cca7e3bac68360d2a9c593545862
**Tag  docker image:** 2021.02.xx on https://hub.docker.com/layers/mapstore2-georchestra/geosolutionsit/mapstore2-georchestra/
**Browser :**  Chrome Version 99.0.4844.82 (Build officiel) (64 bits)

## Problem

Since the last deployments of mapstore2georchestra  the identifier function is not active by default. 
it's not convenient for users .

AS decribed in [the plugin configuration](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.Identify) , i added in the localConfig.json 
```
....
"initialState": {
		"defaultState": {
			"mapInfo": {
				"enabled": true, 
				"disabledAlwaysOn": false,
				"configuration": {
						"showEmptyMessageGFI": false
					}
			},
....

```
But it doesn't work.
Is there anything else to do?

**Comment by Gaetanbrl** [comment]
I currently deploy last mapstore war to try your config @catmorales.
But so far, identifier works without mapInfo localConfig entry.

**Comment by Gaetanbrl** [comment]
@catmorales same for us, we need to configure the identifier tools with the context creator (as a common plugin).
By default, a context only allow a simple map.

As well, i think your config is not correct because mapInfo is not the plugin's name.

The doc give a config for `plugins.Identify` and not `plugins.mapInfo`.

To get the correct plugin config structure, i do something like  : 

1. open the context creator
2. Add the plugin (Identifier in this case)
3. Click in "change config" button
4. See default config structure.

For identifier we have something like : 

```
{
  "cfg": {
    "showHighlightFeatureButton": true,
    "viewerOptions": {
      "container": "{context.ReactSwipe}"
    }
  },
  "override": {}
}
```

**Comment by Gaetanbrl** [comment]
@catmorales after search it's maybe the same... https://github.com/georchestra/mapstore2-georchestra/issues/413#issuecomment-905702023

**Comment by catmorales** [comment]
>For mobile or desktop, the doc give a config for plugins.Identify and not plugins.mapInfo.

Yes sure in the desktop section my configuration is:
```
{
                "name": "Identify",
                "cfg": {
									 
                    "showHighlightFeatureButton": true,
                    "viewerOptions": {
                        "container": "{context.ReactSwipe}"
                    },
                    "showEdit": true
                },
                "override": {
                  "Toolbar": {
                    "position": 11
                  }
                }
            },
```

In the mobile section:

```
{
                "name": "Identify",
                "showIn": ["Settings"],
                "cfg": {
                    "showFullscreen": true,
                    "position": "bottom",
                    "size": 0.5,
                    "fluid": true,
                    "viewerOptions": {
                        "container": "{context.ReactSwipe}"
                    }
											   																  
               }
				   
            },
```
In the embedded section as  recommnded in the releases notes:

```
{
				"name": "Identify",
				"cfg": {
					"showInMapPopup":true,
								   
						  
							
					"viewerOptions": {
						"container": "{context.ReactSwipe}"
					}
				}
			},
```

**Comment by tdipisa** [comment]
Hi @catmorales we have checked with @dsuren1 and we didn't find any reason why the Identify tool is disabled by default in your instance. In our [DEV instance of georchestra](https://georchestra.geo-solutions.it/) (as well as the [official MS](https://mapstore.geosolutionsgroup.com/mapstore/#/)) it is working properly and the source code, at least for the first, is the same. 
The only configuration you have to consider for this is the one in the _initialState_, and it is correct in your instance, as far as we noticed:

![image](https://user-images.githubusercontent.com/1280027/162211680-5a52df76-b1e3-409a-b032-08ff5108d3c2.png)

I know I repeated the same music in other circumstances, but the only differences I can see at the moment between our instances are the custom extensions not present in our installation. Can we at least do a try by removing them at least to exclude the possibility that they are not conflicting some way?

**Comment by catmorales** [comment]
Yes we identified the problem , it was due to another plugin . Thank you so much to take time to see that. !

**Comment by landryb** [comment]
can we figure out what are the bad interactions between the plugins (in your case, which plugin ?) and the core, to avoid reproducing those issues again and again ? it feels as if things were not properly isolated/separated....

**Comment by catmorales** [comment]
Yes @landryb , it concerns a plugin developed by other company which code is [here](https://github.com/sigrennesmetropole/geor_signalement). 
We identified the reason and a fix will be done as soon as possible.

**Comment by Gaetanbrl** [comment]
> can we figure out what are the bad interactions between the plugins

@landryb from my point of view, a plugin is the only responsible of what he do with mapstore the state. So, a dev team have to verify any interactions / control / actions or global state modifications to avoid this conflict.

For this issue, i thnink someone just forgotten to control this point...

Fwiw, i could contribute  to the doc to try to avoid to reproduce again and again this issue.

But i'm sur this will come back with futur constellations of plugins and new contributors.

--
Just to be sur @tdipisa, could you confirm that all plugins are loaded if we just target main /mapstore path even those not inserted in localConfig.json file ? 

This issue is about this behavior because "Signalement" custom plugin don't exists in localConfig but he was loaded with /mapstore root path (and seems to override default identify state).

Thanks.

**Comment by catmorales** [comment]
@Gaetanbrl , i let @tdipisa anwer you but  i can say yes,  all plugins are loaded even if they are not activated in an application context.
This point is one of the work we have  commanded for july at Geosolutions,

> Optimiser le lancement de mapstore et isoler les plugins
> GROUPE 4
> OBJECTIF : Modifier le code pour optimiser le temps de chargement de Mapstore et mieux isoler les plugins (éviter les interactions intempestives).
> CIBLE : Communauté Mapstore
> ISSUE: # 7127 + à créer
> DESCRIPTION : Mapstore est long à se charger au démarrage car il embarque le chargement de tous les plugins y compris ceux qui ne sont pas utilisés par le contexte applicatif courant. Parfois certains plugins présentent des problèmes d'étanchéité entre eux (certains plugins ont des interactions non désirées).
> Il est souhaité que : - le temps de chargement du viewer soit moins long : peut-on éviter le chargement initial de tous les plugins même ceux qui ne sont pas utilisés dans le contexte courant ?
> - le code des plugins soit mieux isolé et la documentation bien renseignée sur ce point pour les développeurs.

**Comment by Gaetanbrl** [comment]
Thanks @catmorales :)
