### ISSUE TITLE
Update to MapStore 2022.01.xx

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#506]
Update of the georchestra MS project master to point to latest MapStore stable 2022.01.xx (migration guidelines available [here](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20210202-to-20220100))

**_This requires also the upgrade of Tomcat to at least version 8.5.x._**

The update will be provided first of all for the master branch. A new stable branch 2022.01.xx will be created then.

**Comment by tdipisa** [comment]
> Update of the georchestra MS project master to point to latest MapStore stable 2022.01.xx (migration guidelines available [here](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20210202-to-20220100))
> 
> **_This requires also the upgrade of Tomcat to at least version 8.5.x._**

@catmorales I would like to point out this for the next updates we have to deliver for Phase 3.

**Comment by landryb** [comment]
wooo with 3d tiles support :heart: \o/

no worries for the tomcat version, most if not all georchestra instances already use tomcat9.

**Comment by catmorales** [comment]
>This requires also the upgrade of Tomcat to at least version 8.5.x.

@pmauduit we are using jetty is this a problem ?

**Comment by pmauduit** [comment]
> @pmauduit we are using jetty is this a problem ?

I don't think we are using jetty, the official docker images for mapstore2 on docker-hub are tomcat-based. The ones deployed into rennes-métropole infra are also based on tomcat.

**Comment by catmorales** [comment]
ok i'm using always the [geosolutions docker image]( https://hub.docker.com/r/geosolutionsit/mapstore2-georchestra/tags), so i imagine they're using the good tomcat version.
