### ISSUE TITLE
Restructure of log4JInitializer bean

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#512]
Due to the Spring update the [Log4jConfigurer is no longer supported](https://github.com/georchestra/mapstore2-georchestra/pull/511/commits/9304c13c3cae04750dbb440ae0b9fe53629a120a) so we have to implement a different way to provide what necessary to properly load the log4j.properties file.

The update PR has been for now merged in a [dedicated branch](https://github.com/georchestra/mapstore2-georchestra/tree/DEV) deployed in [GeoSolutions DEV](https://georchestra.geo-solutions.it/mapstore/#/home).

**Comment by nmco** [comment]
@taba90 although @tdipisa is not blocked by this, they have a deadline next week, hence we should do an initial ASAP to understand if this is going to be a big problem or a picnic.
