### ISSUE TITLE
Legend Tool - Layer legend

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#52]
The Legend extension need to be integrated with the TOC in order to allow the user to visualize the layer legend corresponding to the assigned style:

1. The legend must be available for each WMS layer
2. The legend can be set by the administrator to be static or dynamic (scale dependent)

- Point number 1 is already implemented in MS (for each layer we have a legend in TOC)

- Point number 2 requires to implement the support for the SCALE parameter for GetLegendGraphic (we should also consider to include **hideEmptyRules** and **countMatched** options in LEGEND_OPTIONS param sent by MS). The MS's administrator must has the possibility to configure the above options by plugin configuration properties. [Here](https://docs.geoserver.org/latest/en/user/services/wms/get_legend_graphic/index.html) the related GeoServer documentation.

**Comment by offtherailz** [comment]
To implement this you should allow to customize configuration in localConfig.json this way:

```javascript
 {
                "name": "TOC",
                "cfg": {
                    "activateMetedataTool": false,
                    "layerOptions": {
                      "legendOptions": {
                        "WMSLegendOptions": "forceLabels:on;fontSize:30", <-- overrides defaults
                           "scaleDependent": true| false <-- true by default
                      }
                    }
                }
            }
```

**Note** `legendOptions` already exists, as documented in TOC jsdoc, to provide some style to the container. You should 
 - [ ] add to "WMSlegendOptions" inside this option the override the existing `legendOptions` property inside WMSLegend --> Legend 
- [ ] add `scaleDependent` option activate / deactivate scale dependency with the `scaleDependent` option (now it is active by default).
- [ ] document these 2 options in jsdoc

To do this you should allow to pass
