### ISSUE TITLE
Profil en long

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#521]
It is requested to migrate the **_Profil en long_** plugin to MapStore by creating a new extension for it as it has already been done for [Cadastrapp](https://github.com/georchestra/mapstore2-cadastrapp), [Urbanisme](https://github.com/[sigrennesmetropole/geor_urbanisme_mapstore](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore)) and many other extensions.

The current plugin for the old mapfishapp application is available [here](https://github.com/geobretagne/profile) while the related backend part rely on a WPS plugin [here](https://gitlab.agglo-lepuyenvelay.fr/jusabatier/profil-en-long-wps) to be installed in the geOrchestra GeoServer.

An online instance of the old _Profil an long_ plugin for mapfishapp is available [here](https://geoportail.lepuyenvelay.fr/mapfishapp), so that it is possible to use it as a reference during the development. 

**Requested activities:**

- The WPS backend need to be installed in the [GeoSolutions DEV environment](https://georchestra.geo-solutions.it/geoserver/web/) (GeoServer) to base the MS extension development on it and allow functional testing accordingly. 
The plugin is ready and there is an example of request and response in the [README](https://gitlab.agglo-lepuyenvelay.fr/jusabatier/profil-en-long-wps/-/blob/master/README.md) file along with the needed information to build and deploy it in GeoServer. After the installation it is necessary to grant it in the GeoServer WPS security configuration.

- The old plugin for mapfishapp should be installed in the GeoSolutions DEV environment for testing and reference purposes aimed to reproduce the same functionalities in the new MS extension. To use it once installed:

   - Just go to "Tools" > "Manage Tools" and activate "Profil en long"
   - It appear in "Tools", you can use "Draw Profile" to get curve from selected DTM (defined from Settings)
   - Just trace over Le Puy-en-Velay because our MNT cover only or community

- As far as the existing plugin functionalities are concerned:

   - Draw/import a linear (geojson): be able to draw the profile but also to import a profile in geojson format
![image](https://user-images.githubusercontent.com/1280027/166942451-38b4223d-8f22-4fea-843b-6aceafa19ff7.png)

   - Download the resulting image: for the charts the same library used by MS can be used (PlotlyJS). It should natively provide the ability to download the chart
   ![image](https://user-images.githubusercontent.com/1280027/166943547-2edc2baa-e842-4cc7-8e9c-5362e1e852e6.png)

   - Export the profile: as present in the older plugin it should be possible to export the profile params in CSV format. This functionality should be provided by a dedicated webservice already present in georchestra (eg. https://geoportail.lepuyenvelay.fr/mapfishapp/ws/csv/). **TO BE CLARIFIED**
   ![image](https://user-images.githubusercontent.com/1280027/166944186-bff33bdd-9272-41e8-8ee4-b4a0e5e7e3cb.png)

   - Set up one or more support layers (DTM, DEM,…) in the plugin: this functionality is referring to the existing functionality depicted below. This allows the user to set up the parameters for the WPS request and all of these things are already supported by the WPS backend. It is only needed to reproduce the same and make it possible to configure the desired options for dropdowns
   ![image](https://user-images.githubusercontent.com/1280027/166944542-4e9c9226-4340-4f11-a720-79013250acba.png)

- Last but not the least a new MS extension should be provided for the plugin in the same way of the other existing (eg. [Cadastrapp](https://github.com/georchestra/mapstore2-cadastrapp)). A new Github repo will be provided for this

**Comment by tdipisa** [comment]
@jusabatier (FYI @catmorales) I kindly ask you to check what reported in description for a double check as part of the task preparation.

Since you already have a running instance [here](https://geoportail.lepuyenvelay.fr/mapfishapp) do you think it is possible for us to directly use it for our development instead of installing both back-end and front-end (especially the first) in our [DEV geOrchestra](https://georchestra.geo-solutions.it/header/)? 

If not, can you please let us know the steps to install the addon? The installation guide for the back-end you have provided in the README file seems to be quite clear.

**Comment by landryb** [comment]
fwiw, if you want real DEM data for the WPS backend, https://geoservices.ign.fr/rgealti has download links for 1m and 5m datasets for every region of france.

**Comment by catmorales** [comment]
>@catmorales we need a new repo in Github for the new Extension. Can you please provide it and grant me admin access in the same way of other extension? Thank you.

@landryb , @jusabatier , No problem to add a new repository on https://github.com/sigrennesmetropole but is it the better choice ? Could it be better to add it in https://github.com/georchestra ?

**Comment by jusabatier** [comment]
Personnally I prefer to create it in https://github.com/georchestra

I think also it could be a good thing to repatriate addon urbanisme here also.

**Comment by catmorales** [comment]
@landryb , @MaelREBOUX Who can create  this repository in https://github.com/georchestra ?

**Comment by tdipisa** [comment]
>Just notice that on my platform, the provided addon isn't the original one, but a portage for the WPS service handle.
So it differ from the original one on some points.
Specially, the original addon handle the selection of a linestring feature for generate a profile.
I don't know if this feature is a part of the request ?

@jusabatier @catmorales please provide to us the addon version we have to effectively consider for the migration to MS to install it in our environment

>No, the Mapstore addon must not rely on mapfishapp components, the aim is to replace it.
Isn't it possible to generate a CSV on the fly from the WPS reponse ?

Ok we will check it. 

> Anyway, the installation of the WPS service is as simple as dropping it in the GS WEB-INF/lib.
You just need to check the GS version when compiling.
Actually, master is on 2.20.4, but there is a branch for 2.17.5.

We have this version installed in our DEV. It would be good to have a WPS compatible with this if possible. @jusabatier can you let me know if the WPS service we have to install is compatible with the georchestra version we are using?

![image](https://user-images.githubusercontent.com/1280027/167100609-4105906b-946b-43e2-9d10-0f26aa9f6f36.png)

**Comment by jusabatier** [comment]
Here you have a generated jar for GS 2.16.1 : https://gitlab.agglo-lepuyenvelay.fr/jusabatier/profil-en-long-wps/-/packages/34

Here you have the mapfishapp addon I use : https://gitlab.agglo-lepuyenvelay.fr/jusabatier/profil-en-long-wps/-/tree/geoserver-2.16.1/mapfishapp

You can use the one on https://geoportail.lepuyenvelay.fr/mapfishapp/ (Enable it with "Outils" > "Gerer les outils")
Or install it on your own platform. Don't forget to enable the WPS service in GS, and to correctly set configuration in mfapp addon config.json

As I already said, my mfapp addon doesn't implement the ability to generate a profile from a selected linestring feature, but this ability is a part of the original addon, so it have to be ported in the mapstore one.

Originally it allow to select a feature in the entities table and generate a profil for it.
I think it could be more user friendly to allow to directly click on the map and generate it for intersecting features like for Identifier tool.

**Comment by catmorales** [comment]
>@jusabatier @catmorales please provide to us the addon version we have to effectively consider as a reference for the migration to MS to be installed in our environment.

The addon which must be used as reference and must serve you as guide is that of Puy en velay whose links were provided to you by Julien. The other one is very old and a bit buggy.
However, a functionality which was present on the old one, is absent from the new one and must be developed in complement. It is the function called "profile from a selection" which allows after selection of an entity in a layer of type line, to draw the profile of this entity.

The use case is as follows:
1- selection of a linear entity in a line layer present in the TOC and displayed in the map
2- generate and display the profile

**Comment by tdipisa** [comment]
Thank you @catmorales @jusabatier @landryb

**Comment by tdipisa** [comment]
Hi @jusabatier

We tried to install the WPS [here](https://gitlab.agglo-lepuyenvelay.fr/jusabatier/profil-en-long-wps/-/packages/34) on our [DEV environment](https://georchestra.geo-solutions.it/geoserver/web/) as well as in a local vanilla GeoServer v2.16.1 with WPS plugin but in both cases we have an error, as far as I can see, related to a Java version different from the one used to compile (the full log here).

In our DEV environment we have openjdk "1.8.0_252" while locally we used "1.8.0_191".

Is it possible for you to provide a compatible JAR file?

**Comment by jusabatier** [comment]
Can't you update your JAVA to 11, as this is le current stable version ?

If you can't, as it's an opensource project, you can simply clone the repo and build the one you want with : 

```
mvn clean install
```

**Comment by tdipisa** [comment]
@jusabatier do you know if java 11 is compatible with the georchestra version we are using at the moment?

**Comment by jusabatier** [comment]
Try with this jar, I recompiled it with JAVA8 : https://gitlab.agglo-lepuyenvelay.fr/jusabatier/profil-en-long-wps/-/packages/36

**Comment by tdipisa** [comment]
Thank you so much @jusabatier we are going to try it.

**Comment by landryb** [comment]
sadly i think the geoserver gdal plugin also needs libgdal bindings, and from that point you need to rebuild debian gdal packages with java bindings enabled. I might be wrong though.. @pmauduit ?

**Comment by pmauduit** [comment]
> I might be wrong though.. @pmauduit ?

That is what we are currently doing for a non-geOrchestra project indeed. Mainly reverting this commit: https://salsa.debian.org/debian-gis-team/gdal/-/commit/936e50e1a9e5eb3d1bd10147b5d5c25476845b23 then recompile it.

**Comment by tdipisa** [comment]
>As mentioned in the README.md, yes this WPS service depends on GDAL Bindings, so you'll have to enable them on your geoserver.

Right, I'm sorry for the noise @jusabatier 

>That is what we are currently doing for a non-geOrchestra project indeed. Mainly reverting this commit: https://salsa.debian.org/debian-gis-team/gdal/-/commit/936e50e1a9e5eb3d1bd10147b5d5c25476845b23 then recompile it.

Long story short, I understand we have to do the following too :-) ok
 
> sadly i think the geoserver gdal plugin (which only contains jars) also needs libgdal bindings (libgdal.so, libgdal_jni.so) , and from that point you need to rebuild debian gdal packages with java bindings enabled. I might be wrong though.. @pmauduit ?

**Comment by pmauduit** [comment]
This package should work along with the current libgdal from debian bullseye by the way:
[libgdal-java.zip](https://github.com/georchestra/mapstore2-georchestra/files/8900176/libgdal-java.zip)

**Comment by tdipisa** [comment]
@pmauduit thank you so much. I'm going to let devops know about the above and I will get back to you if needed ;-)

**Comment by landryb** [comment]
*hint* *hint* it would be good to upgrade to 22.0.x & debian 11 ;)

**Comment by tdipisa** [comment]
@pmauduit we managed to have the plugin on our mapfishapp fully working now. Thank you so much.

We are proceeding with a quick design phase aimed to start the development of the plugin @catmorales. I will open a dedicated issue to connect to this epic.

Just a question @catmorales. As far as the design of the plugin is concerned, do you prefer a floating panel to show the profile information or a side panel?

**Comment by landryb** [comment]
fwiw, floating panels are generally bad, from our experience with cadastrapp in mapfishapp.. i'd have a preference for a side panel or make it a large modal window like property details in cadastrapp ?

**Comment by tdipisa** [comment]
@catmorales can you give me the same admin rights on the [new repository ](https://github.com/georchestra/mapstore2-longitudinal-profile) so that I can manage it and add contributors in the same way I can for Urbanisme and Catastrapp repos?

**Comment by landryb** [comment]
> @catmorales can you give me the same admin rights on the [new repository ](https://github.com/georchestra/mapstore2-longitudinal-profile) so that I can manage it and add contributors in the same way I can for Urbanisme and Catastrapp repos?

done

**Comment by tdipisa** [comment]
Thank you @landryb

**Comment by catmorales** [comment]
thank you @landryb  :)
