### ISSUE TITLE
Few issues identified involving drawing actions for Cadastrapp and Urbanisme with the new Sidebar system

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#530]
Few issues have been  identified in [GeoSolutions DEV](https://georchestra.geo-solutions.it/mapstore/#/context/urbanismecadastrapp) while testing the drawing actions of Cadastrapp and Urbanisme with the new Sidebar system recently provided.

Reference context is used during tests: https://georchestra.geo-solutions.it/mapstore/#/context/urbanismecadastrapp

Steps to reproduce:

1. 
Not related to drawing tool be still relevant to be fixed: additional layers in print not visible/working. The option should be active by default in MS2-georchestra and ready to be disabled from plugin configuration in context wizard.

2. 
- The cadastrapp panel is closed when you open the measurement.
- You perform a measurement and then you reopen the cadastrapp panel.
- The measurement tool is still active to allow measurement on map but the floating panel is not visible.
- You can activate a cadstrapp selection tool (like the line selection) and select some parcels.
- The measurement is performed contextually while the measurement panel is not opened and you cannot interact with measurement options.
- As soon as you reopen the measurement panel, the cadastrapp panel is again closed and all measurement cleared.

The cadastrapp panel should remain opened while the measurement panel is open. The measurement panel can be closed only when you activate a cadstrapp selection tool and as soon as you activate the measurement panel the cadastrapp drawing actions should be disabled.

3. 
- Then you open the urbanisme tool when the cadastrapp is open with a selection tool active.
- You activate a selection tool of Urbanisme (like Town Planning Info), then click on the map and:
   - The measurement, if previously activated, is still performed
   - The drawing action button of cadastrapp is not disabled and this is not correct because the button is in a inconsistent state
- You deactivate the Urbanisme button and:
   - The measurement is still active
   - The Urbanisme panel is still present but empty and the urbanisme selection in map still present
- The drawing action button of cadastrapp is still toggled but not effectively active due to the above inconsistent state

4. 
Similar issues are involving also the Street View plugin where other map interaction functionalities are active when the one of the Stree View plugin is activated.

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/23b9f5c4-4b94-46da-b30f-5aa349b0438c)

**It is needed to better manage the activation of map interaction functionalities across different tools in mutual exclusive way.**

**Comment by alexander-fedorenko** [comment]
Applied changes via following PRs:

MapStore upstream:
https://github.com/geosolutions-it/MapStore2/pull/8181 - Update rules of having only one drawing tool active for all upstream drawing plugins: annotations, street view, measure, feature editor, layer filter.

GeOrchestra:
https://github.com/georchestra/mapstore2-georchestra/pull/531 - Activates overlay layers print by default.

Cadastrapp:
https://github.com/georchestra/mapstore2-cadastrapp/pull/159 - Applies toggling logic to the cadastrapp against another drawing tools.

Urbanisme:
https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/pull/54 - Applies toggling logc to the urbanisme against another drawing tools.

Summary of how tools should behave with the applied changes:

Drawing tools: Urbanisme, Annotations, Measure, Street View, Cadastrapp, Feature Editor, Layer filter.

Urbanisme tool active:
- Urbanisme tool toggled off - modal with info properly deactivated.
- Annotation coordinate editor open: urbanisme tool toggled off.
- Measure activated: urbanisme tool toggled off
- Street View activated: urbanisme tool toggled off.
- Cadastrapp selection tool activated: urbanisme tool toggled off.
- Feature editor activated: urbanisme tool toggled off.
- Layer filter - drawing of the area for filter is active, urbanisme tool toggled off.

Street view tool active:
- Urbanisme toolbar is open - no action
- Urbanisme tool is toggled on - street view is closed
- Annotations coordinate editor open - street view is closed
- Measure tool is open - street view is closed.
- Cadastrapp - no action
- Cadastrap measure tool - street view is closed
- Feature editor - street view is closed
- Layer filter - street view is closed

Annotations tool active (coordinate editor):
- Urbanisme toolbar is open - coordinate editor is closed
- Urbanisme tool is toggled on - coordinate editor is closed
- Measure activated - coordinate editor is closed.
- Street view - coordinate editor is closed.
- Cadastrapp dock activated - coordinate editor toggled off
- Feature editor - cannot be activated with annotations open.
- Layer filter - same as previous.

Measure tool active:
- Urbanisme toolbar is open - no action
- Annotations coordinate editor open - measure tool is closed
- SteetView - measure tool is closed
- Cadastrapp selection tool activated - measure tool is closed
- Feature editor activated - Measurement tool is closed.
- Layer filter - Measurement tool is closed.

Cadastrapp dock is active:
- Urbanisme toolbar enabled - no action.
- Urbanisme tool is toggled on - cadastrap selection tool is toggled off.
- Annotations coordinate editor open - cadastrap selection tool is toggled off.
- Measure open - cadastrap selection tool is toggled off.
- Street view open - cadastrap selection tool is toggled off.
- Feature editor activated - cadastrapp is closed
- Layer filter - cadastrap selection tool is toggled off.


Feature editor:
- Closes everything, closed by everything

Layer filter:
- Deactivates cadastrapp, urbanisme, closes measure, street view.

**Comment by catmorales** [comment]
@tdipisa what about other's plugins we have,  developed with others companies ?
Did you do some documentation, communication about it ?
Alert to @pierrejego , @ThomasBruleOpen, @fvanderbiest

**Comment by tdipisa** [comment]
> @tdipisa what about other's plugins we have, developed with others companies ? Did you do some documentation, communication about it ? Alert to @pierrejego , @ThomasBruleOpen, @fvanderbiest
> 
> Perhaps, you will speak about it at the GeoCom's convention.

We will provide some doc including some general indications to follow.

**Comment by ElenaGallo** [comment]
Hi @alexander-fedorenko, 

I found these two inconsistencies on the **logic of the drawing tools**:

1_ Annotations tool active (coordinate editor): Urbanisme toolbar is open
![1](https://user-images.githubusercontent.com/56537133/169253637-b374641c-fa41-4a6b-aeba-5764a2dbc272.gif)

*Current Result*
The coordinate editor is open

2_ Cadastrapp dock is active: Feature editor activated - cadastrapp is closed.
![2](https://user-images.githubusercontent.com/56537133/169253750-b5ce74fe-60e1-4263-a5df-ad0590b21b8b.gif)

*Current Result*
Cadastrapp is closed but the  Feature editor does not open


For the **print tool**:

1_ It is not possible to download the printed pdf, both when cadastrapp & urbanisme are activated and when they are not and, both in context and for the map viewer

*Context with Cadastrapp activated*
![print 1](https://user-images.githubusercontent.com/56537133/169259972-5685d960-018f-4701-9bfa-66690c7c5556.gif)

*Map viewer with no cadastrapp & urbanisme*
![print 2](https://user-images.githubusercontent.com/56537133/169259928-fd059050-6009-4b46-9a31-1e3afb1e106b.gif)

2_ When cadastrapp and urbanisme are open but toggled off, an error appears when printing the map.
![print with cadastrapp open](https://user-images.githubusercontent.com/56537133/169260828-9db8e9f9-71d6-4da2-bd56-e380dd3f955a.gif)

**Comment by alexander-fedorenko** [comment]
Hi @ElenaGallo 
1_ That's ok for annotations. It should only untoggle active Urbanisme tool but toolbar should remain open and available.
2_ Inability to open feature editor while cadastrapp dock is active is fixed by the changes in https://github.com/georchestra/mapstore2-georchestra/pull/535

Error on print dialog is resolved, print with enabled cadastrapp/urbanisme tools and no plot selection should be possible.
In addition I discovered issue when urbanisme print tool did not add image properly to the resulting file. This should be fixed as of now, updated version of urbanisme extension from https://github.com/sigrennesmetropole/geor_urbanisme_mapstore/pull/58 is installed on DEV.

404 error on the resulting file is not related to the changes and will be resolved soon.

**Comment by tdipisa** [comment]
Thank you @alexander-fedorenko I will try to review all things tomorrow.

**Comment by tdipisa** [comment]
@ElenaGallo please let us know, I did a test tour and all seems working as expected for me. The download issue of the printing PDF is not related to this development and it can be solved separately in our DEV environment. Fr the moment it is important that the final result is properly reported in the MS print UI.

**Comment by ElenaGallo** [comment]
@tdipisa @alexander-fedorenko the tests also pass for me and the cadastrapp/urbanisme layers are visible in the MS print UI.
