### ISSUE TITLE
[MS3] Problems with plugins

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#540]
After the release of MS3, I tried to install the last master build : https://github.com/georchestra/mapstore2-georchestra/actions/runs/2369907204

Once deployed to the tomcat and reloaded, I tried to install new pre-release versions of Cadastrapp and Urbanisme.

I managed to uninstall them and reinstall new zips.
But I can't activate them, it result in this type of error in the dev's console : 

> Error in epic "enablePluginsEpic". Original error: TypeError: Cannot read properties of null (reading 'mandatory')
>     [...]
> geOrchestra.js?155e8d8e9ca20d165a1a:2 Uncaught TypeError: Cannot read properties of null (reading 'mandatory')
>     [...]

And they still in unactivated column for the context.

After that, I also figured out by navigate other context's configuration that for all, only the Map plugin still activated.
All other plugins had move to unactivated column.

It's look like there is a problem with plugin's management.

**Comment by jusabatier** [comment]
I just want to specify that we have absolutely no release procedure.

My configs files may not be up to date with the new version as I don't know if new ones are needed.
I assume that there are some to add or update with the new sidebar layout.

Can you for begin provide some changelog for configs files, in order to know how to upgrade them for new MS2-georchestra version ?

**Comment by tdipisa** [comment]
@jusabatier I've assigned the issue to @alexander-fedorenko to provide assistance asap. Thank you for reporting.

**Comment by landryb** [comment]
> Can you for begin provide some changelog for configs files, in order to know how to upgrade them for new MS2-georchestra version ?

fwiw, the git log for https://github.com/georchestra/mapstore2-georchestra/blob/master/configs/localConfig.json & https://github.com/georchestra/mapstore2-georchestra/blob/master/configs/config.json is a start .. i'm trying to get them updated/kept up to date in the georchestra/datadir repo too.

**Comment by jusabatier** [comment]
I don't think assume that users will search each config's commit that have occured since last version is the good way to publish a release.

**Comment by landryb** [comment]
> I don't think assume that users will search each config's commit that have occured since last version is the good way to publish a release.

i never said that - for me users are supposed to use the datadir repository and merge their change on top of the updated configs from upstream.

**Comment by tdipisa** [comment]
> I don't think assume that users will search each config's commit that have occured since last version is the good way to publish a release.

Hi @jusabatier a release has not yet been made. We delivered on master for the moment and a new stable branch will be generated only when acceptance tests of all of you guys are passed on master and things are ready for this. 
We didn't update yet the config files versioned in the georchestra dara dir repo. Probably the problem is only this.
@alexander-fedorenko will check.

**Comment by alexander-fedorenko** [comment]
@jusabatier please check that your pluginsConfig.json file content is in align with the changes requested in migration guidelines: https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#replacing-burgermenu-with-sidebarmenu
Missing "SidebarMenu" entry is causing such behavior.

**Comment by jusabatier** [comment]
I tried to follow your migration guide.

It looks less bugued, but when load a newly created context, I only have the old BurgerMenu and no sidebar.
Is it normal ?
I undestood that with this release we now should have a sidebar with lots of functionalities.

**Comment by alexander-fedorenko** [comment]
Please check that "BurgerMenu" is not in the list of enabled plugins for the context, otherwise it will be rendered instead of "SidebarMenu".

**Comment by jusabatier** [comment]
Ok it does the job ! Thanks !

For others that have the problem, you need to update your existing contexts with this query : 

```
UPDATE mapstore.gs_stored_data SET stored_data = regexp_replace(gs_stored_data.stored_data,'{"name":"BurgerMenu"},','{"name":"SidebarMenu"},')
FROM mapstore.gs_resource 
WHERE gs_stored_data.resource_id = gs_resource.id AND 
  gs_resource.category_id = 8 AND
  gs_stored_data.stored_data ~ '.*{"name":"BurgerMenu"},.*';
```

It will replace the BurgerMenu by the SideBarMenu.

If I understand well, BurgerMenu and SideBarMenu can't be used at same time ?
Is there some documentation for SideBarMenu ? (icon order, ...)

**Comment by landryb** [comment]
> ```
> UPDATE mapstore.gs_stored_data SET stored_data = regexp_replace(gs_stored_data.stored_data,'{"name":"BurgerMenu"},','{"name":"SidebarMenu"},')
> FROM mapstore.gs_resource 
> WHERE gs_stored_data.resource_id = gs_resource.id AND 
>   gs_resource.category_id = 8 AND
>   gs_stored_data.stored_data ~ '.*{"name":"BurgerMenu"},.*';
> ```


thanks a lot for figuring out the query, that should definitely be mentioned in the release notes

**Comment by alexander-fedorenko** [comment]
@jusabatier, yes, SidebarMenu and BurgerMenu cannot be used at the same time, SidebarMenu will be hidden whenever BurgerMenu is on the page.
There is no specific documentation page for SidebarMenu, it will list all active plugins/extensions previously available in BurgerMenu, inheriting their order. In addition, at the first two positions, it has Home button and User menu icons previously available in OmniBar.

**Comment by jusabatier** [comment]
Ok thanks for infos.

As the problem is solved, I close this issue.

**Comment by catmorales** [comment]
It will be difficult to test for us :/

**Comment by landryb** [comment]
If people wonder where the migration notes mentions it, check https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#replacing-burgermenu-with-sidebarmenu
