### ISSUE TITLE
Longitudinal profile MapStore plugin

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#544]
It is requested to migrate the **_Profil en long_** plugin to MapStore by creating a new extension for it as it has already been done for [Cadastrapp](https://github.com/georchestra/mapstore2-cadastrapp), [Urbanisme](https://github.com/[sigrennesmetropole/geor_urbanisme_mapstore](https://github.com/sigrennesmetropole/geor_urbanisme_mapstore)) and many other extensions.

The functionalities of the plugin are based on a backend counterpart that is represented by a WPS process in GeoServer that is responsible of generating the longitudinal profile.

The longitudinal WPS process is ready in [GeoSolutions DEV](https://georchestra.geo-solutions.it/geoserver/web/) and there is an example of request and response in the [README](https://gitlab.agglo-lepuyenvelay.fr/jusabatier/profil-en-long-wps/-/blob/master/README.md) file. The code of the old plugin for mapfishapp is available [here](https://gitlab.agglo-lepuyenvelay.fr/jusabatier/profil-en-long-wps/-/tree/master/mapfishapp) for reference if needed.

As far as the existing plugin functionalities are concerned:

   - Draw/import a linear (geojson): be able to draw the profile but also to import a profile in geojson format
   
![image](https://user-images.githubusercontent.com/1280027/166942451-38b4223d-8f22-4fea-843b-6aceafa19ff7.png)

   - Download the resulting image: for the charts the same library used by MS can be used (PlotlyJS). It should natively provide the ability to download the chart
   
   ![image](https://user-images.githubusercontent.com/1280027/166943547-2edc2baa-e842-4cc7-8e9c-5362e1e852e6.png)

   - Export the profile: as present in the older plugin it should be possible to export the profile params in CSV format. This functionality is provided in the old mapfishapp by a dedicated webservice (eg. https://geoportail.lepuyenvelay.fr/mapfishapp/ws/csv/) but the MS extension must not rely on mapfishapp components, the aim is to replace it, so the CSV should be generated client side possiblyfrom the WPS response

   ![image](https://user-images.githubusercontent.com/1280027/166944186-bff33bdd-9272-41e8-8ee4-b4a0e5e7e3cb.png)

   - Set up one or more support layers (DTM, DEM,…) in the plugin: this functionality is referring to the existing functionality depicted below. This allows the user to set up the parameters for the WPS request and all of these things are already supported by the WPS backend. It is only needed to reproduce the same and make it possible to configure the desired options for dropdowns
   
   ![image](https://user-images.githubusercontent.com/1280027/166944542-4e9c9226-4340-4f11-a720-79013250acba.png)

- A functionality which was present on the old plugin but, but absent in the plugin installed in [GeoSolutions DEV](https://georchestra.geo-solutions.it/mapfishapp/), is the function called "profile from a selection" which allows after a selection of a layer feature of type line, to draw the profile of this entity (see the option "_Selection to profile_" in the image below)

   The use case is as follows:
         - Selection of a linear feature in a line layer present in the TOC and displayed it in the map
         - Generate and display the profile

   For this it would be good to provide an option in the new MS tool to allow the user to select a feature in map of a selected layer in TOC, display that selection and use the related geometry line for the WPS.

![image](https://user-images.githubusercontent.com/1280027/174073993-eb609c77-451b-4436-8bb4-3fd11021a813.png)

- Last but not the least a new MS extension should be provided for the plugin in the same way of the other existing (eg. [Cadastrapp](https://github.com/georchestra/mapstore2-cadastrapp)). A new [Github repo](https://github.com/georchestra/mapstore2-longitudinal-profile) has been created for that purpose

## Other useful information
Additional DEM data for the WPS backend are available if needed. https://geoservices.ign.fr/rgealti has download links for 1m and 5m datasets for every region of france.

**Comment by tdipisa** [comment]
@alexander-fedorenko let's work first on the design using a side panel.

**Comment by landryb** [comment]
great stuff, that all looks awesome and good - minor nit, sure the previous version in mfapp allowed to import a GML file, but in 2022 i think geojson is better :) That's also what is mentioned/specified in comment 1.

**Comment by tdipisa** [comment]
> That's also what is mentioned/specified in comment 1

yes indeed, thank you so much.

**Comment by tdipisa** [comment]
Work in pending review [here](https://github.com/georchestra/mapstore2-longitudinal-profile/pull/2)
