### ISSUE TITLE
Update to 2022.02.xx

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#548]
Update the project (master branch) to 2022.02.xx MS official stable branch. Related migration guidelines are [here](https://mapstore.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20220102-to-20220200).
During the release in mid Sep a new stable branch will be created.

**Comment by landryb** [comment]
@tdipisa i suppose the main driver for the branch update is #523 ?

**Comment by tdipisa** [comment]
yes @landryb. I'm going to restore the milestone for this delivery.

**Comment by landryb** [comment]
interestingly now 2021.02.xx also fails with the same error. something about node-gyp is wrong...

**Comment by Gaetanbrl** [comment]
For me 2022.02.xx (and 2021.02.xx) works with :

![image](https://user-images.githubusercontent.com/16317988/191293695-913a7588-547e-47e3-94af-598d5ed68244.png)

> For me later...
> NEVER forget to update submodule (`git submodule update`) after `git checkout`

**Comment by landryb** [comment]
strange. switching from 14 to 12 via nvm, i can still build 2022.02.xx. and switching back to system node (eg 12 via debian node lts packages) i can also build... definitely strange.

**Comment by landryb** [comment]
oh well. just realized that the maven goo in ms2 installed its own node 12.22 binary in ./node. what a hell..
