### ISSUE TITLE
Travis - Travis build

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#56]
A Travis build must be connected to the MapStore project repository for continuous integration purposes and unit testing at each commit/PR merge

**Comment by tdipisa** [comment]
@MaelREBOUX @catmorales, since I'm an outside collaborator of the geOrchestra Github organization, I cannot setup a Travis integration for this repository. The possible solutions are two in my opinion:

- You setup a Travis build for this repository (this is the preferred/suggested one)
- We fork this repository inside the GeoSolutions organization where I'm able to setup the Travis build, then we do ours devs (PRs) in it keeping the mapstore2-georchestra repo aligned through PRs everytime.

**Comment by fvanderbiest** [comment]
Hi @tdipisa 
I can handle the setup of a travis build for sure.

**Comment by fvanderbiest** [comment]
Just activated https://travis-ci.org/georchestra/mapstore2-georchestra

**Comment by tdipisa** [comment]
@fvanderbiest thank you, we will send a PR soon to fix a build issue present in this project that has already been fixed in the official MS.
