### ISSUE TITLE
Problems with 2022.02.00-RC2-geOrchestra

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#562]
Hello,
I just upgrade our MS2 to last release, and here are some problems we met : 

- https://github.com/geosolutions-it/MapStore2/issues/8692
- https://github.com/geosolutions-it/MapStore2/issues/8693
- https://github.com/geosolutions-it/MapStore2/issues/8695
- https://github.com/geosolutions-it/MapStore2/issues/8697

Can other platform reproduce them ?

@catmorales @MaelREBOUX @landryb

**Comment by tdipisa** [comment]
@jusabatier thank you for reporting your test results. We will check them asap to get back to you directly in MS issues you have opened.

**Comment by tdipisa** [comment]
[2022.02.00-RC3-geOrchestra](https://github.com/georchestra/mapstore2-georchestra/releases/tag/2022.02.00-RC3-geOrchestra) contains some fixes.
