### ISSUE TITLE
Read the Docs - Online documentation

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#57]
A Read the Docs entry point documentation should be provided inside the geOrchestra MapStore project and need to be available online.

**Comment by MaelREBOUX** [comment]
For this : I have started to setup something below  this url  http://docs.georchestra.org 
The webserver is not configured yet for Sphinx (http://www.sphinx-doc.org/en/master/)

The idea is to have entry to the documentation related to geOrchestra. Ex :
- http://docs.georchestra.org/cadastrapp/
- http://docs.georchestra.org/console/
- http://docs.georchestra.org/mapstore2/

If I undertand well we need a specific repo for each documentation project. Isn't it ?

**Comment by tdipisa** [comment]
@MaelREBOUX, let's discuss this in the tomorrow meeting so I can better illustrate what we would like to do.
