### ISSUE TITLE
Follow up update to log4j2 in mapstore2

### ISSUE THREAD

**Issue by taba90** [georchestra/mapstore2-georchestra#580]
## Description

The master branch of MapStore2 has been updated in order to use log4j2. When georchestra will be aligned with the version having this updates some changes will be needed namely:
- the class referenced [here](https://github.com/georchestra/mapstore2-georchestra/blob/17d880fe983fb710ebb27e270b971db0af7436b0/web/src/main/resources/applicationContext.xml#L20) will not be available along with the static method [configure](https://github.com/georchestra/mapstore2-georchestra/blob/17d880fe983fb710ebb27e270b971db0af7436b0/web/src/main/resources/applicationContext.xml#L21). Probably it should be enough to create a java class with a static method configure with same arguments of the one invoked in the applicationContext that reload the configuration. Something like:
```
public static void configure (String log4jPropertiesPath){
LoggerContext context = (org.apache.logging.log4j.core.LoggerContext) LogManager.getContext(false);
context.setConfigLocation(new URI(log4jPropertiesPath));
}
```
or 
```
public static void configure (String log4jPropertiesPath){
Configurator.reconfigure(new URI(log4jPropertiesPath));
}
```
- remove[ this dependency ](https://github.com/georchestra/mapstore2-georchestra/blob/b8e85ed00cb23c8ad64274f50ad46ad4e8522600/web/pom.xml#L111)or introduce the log4j2 to log4j bridge in order to keep it usable (needs to be tested)

- update log4j dependencies and getLogger method in the java code involving it. 

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Mapstore2georchestra improvement 
- [ ] Mapstore2 improvement
- [ ] Other... Please describe:

**Comment by tdipisa** [comment]
[Draft PR](https://github.com/georchestra/mapstore2-georchestra/pull/625) to be completed with the work for this issue to finalize the update to 2023.01.xx

**Comment by offtherailz** [comment]
Watching at the 

> ## Description
> The master branch of MapStore2 has been updated in order to use log4j2. When georchestra will be aligned with the version having this updates some changes will be needed namely:
> 
> * the class referenced [here](https://github.com/georchestra/mapstore2-georchestra/blob/17d880fe983fb710ebb27e270b971db0af7436b0/web/src/main/resources/applicationContext.xml#L20) will not be available along with the static method [configure](https://github.com/georchestra/mapstore2-georchestra/blob/17d880fe983fb710ebb27e270b971db0af7436b0/web/src/main/resources/applicationContext.xml#L21). Probably it should be enough to create a java class with a static method configure with same arguments of the one invoked in the applicationContext that reload the configuration. Something like:
> 
> ```
> public static void configure (String log4jPropertiesPath){
> LoggerContext context = (org.apache.logging.log4j.core.LoggerContext) LogManager.getContext(false);
> context.setConfigLocation(new URI(log4jPropertiesPath));
> }
> ```
> 
> or
> 
> ```
> public static void configure (String log4jPropertiesPath){
> Configurator.reconfigure(new URI(log4jPropertiesPath));
> }
> ```

This is not necessary. The bean that used that configure method was neede to optionally load the file `log4j.properties` from datadir, when defined, or from the standard package.

In log4j2 we can implement this functionality by adding to the classpath the file `log4j2.component.properties`.  This is a property configurer a high priority that can replace the env variable this way:

```
log4j.configurationFile=classpath:log4j2.properties,${sys:georchestra.datadir}mapstore/log4j2.properties
```

`log4j.configurationFile` can accept an `array` of file paths, that can exist or not, and that are applied in override. 

So the logic of "loading from the classpath of from the datadir", can be completely replaced by this file logic (added in the Draft PR](https://github.com/georchestra/mapstore2-georchestra/pull/625) mentioned.


> * remove[ this dependency ](https://github.com/georchestra/mapstore2-georchestra/blob/b8e85ed00cb23c8ad64274f50ad46ad4e8522600/web/pom.xml#L111)or introduce the log4j2 to log4j bridge in order to keep it usable (needs to be tested)

done 

> * update log4j dependencies and getLogger method in the java code involving it.

There is not actually code that use Lof4j logic. This can be added to the guidelines for the upgrade of geOrchestra.

**Comment by tdipisa** [comment]
@offtherailz I'm sorry but, why the following new name?

>The application will log in mapstore_changed.log and not in mapstore.log anymore.

**Comment by offtherailz** [comment]
Maybe I didn't explained this well. This `mapstore_changed.log` is one successful test that explains that if I put one file in the datadir (named `log4j2.properties`) it will be used and override default settings in `WEB-INF/classes`
