### ISSUE TITLE
[Attribute table] Synchronize map/table active by default

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#581]
## Description
Ability to have the function  table/map filter  enabled by default  when we open the attribute table.
Add a parameter at plugin level at true or false to enable/disable this functionality by default.
![image](https://user-images.githubusercontent.com/4659829/208685585-d8306baf-85a9-4cc4-8959-a266a1382591.png)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Mapstore2georchestra improvement 
- [X ] Mapstore2 improvement
- [ ] Other... Please describe:

**Comment by landryb** [comment]
@catmorales correct me if im wrong, but from your sentence here's what i understood - what you expect is:
- being able for a layer to have a filter on a field enabled by default when opening the attribute table, with a given value ?
- where would that given value (in your screenshot, `chantepie` for `nom_commune` field) come from ? saved in the map ? url parameter ? from the featureeditor plugin configuration in the context editor ?
- should that given filter be modifyable by the end-user, or fixed/hardcoded by the map/context creator ?

**Comment by catmorales** [comment]
@landryb No that's not the aim of this functionnality. 
The aim is just have the function active by default when opening and attribute table 
It concerns  all layers in  the context if in the table attribute plugin , the parameter (new parameter)  is on "true" .
If the parameter is on "false", it is the same behaviour as usual.

**Comment by tdipisa** [comment]
@catmorales that configuration option exists for a while. You can look at the plugin documentation [here](https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.FeatureEditor), the property is _enableMapFilterSync_

**Comment by MaelREBOUX** [comment]
@catmorales 

![image](https://user-images.githubusercontent.com/6370443/212963050-cd0c04b3-af01-4b75-b9df-aac62dcff4b9.png)

**Comment by catmorales** [comment]
@tdipisa ok thank you , I will try it

**Comment by catmorales** [comment]
@tdipisa , it's OK for me thank you !
