### ISSUE TITLE
[Print plugin] Ability to rotate the map 

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#582]
## Description

Ability to rotate the map in the printed document (as in mapfishapp) 
It must be visible on the preview.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Mapstore2georchestra improvement 
- [x] Mapstore2 improvement
- [ ] Other... Please describe:

## Other useful information

![image](https://user-images.githubusercontent.com/4659829/216949784-be5c7065-6bbe-4a51-bbad-f88f7d71ff57.png)

![image](https://user-images.githubusercontent.com/4659829/216949749-3efef8ab-32b2-48ba-9980-c49afe66c662.png)

 The compass must be reoriented in the pdf according to the applied rotation angle

**Comment by tdipisa** [comment]
The implementation will provide the support for the rotate option in the print plugin UI. The rotation is already supported by the printing engine used by MS but the UI part is missing.

**Comment by catmorales** [comment]
I added screenshots and information in the first comment

**Comment by dsuren1** [comment]
MS issue ref: https://github.com/geosolutions-it/MapStore2/issues/9318

**Comment by landryb** [comment]
feature tested working fine on 2023.02, printing the default osm map in A4:
- pdf print using 45deg rotation
![image](https://github.com/georchestra/mapstore2-georchestra/assets/3421760/93324a36-e460-49ae-861d-656c939dfcf0)
- png print using 315deg rotation
![image](https://github.com/georchestra/mapstore2-georchestra/assets/3421760/6125da9b-6459-4a2d-b0eb-d5d3c2e7d403)

the 'north arrow'/compass is properly oriented towards the north.
