### ISSUE TITLE
[Context Manager ] Ability to import/export an application context

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#584]
## Description
Ability to import/export an application context **from the context manager UI**
The base URL can be changed in the import and in the export,
Import specific : A control on the layers's,  plugins and roles must be done and a message displayed if some components are missing in the destiny platform.
Customized  configurations of the plugins should be export too.
In fact the entire context configuration which is stored in the database must be exported

Functionnality just for administrators.
 _Use case :_ 
We have a test geOrchestra's instance (portail-test.sig.rennesmetropole.fr) and a production geOrchestra's instance (portail.sig.rennesmetropole.fr). Both have the same components (geoserver, mapstore,...) and the same layers published.
When an application context is Ok in the test platform, we need to deploy it in the production platform, we need a tool to do it from the UI.

### Note
Related MS issue https://github.com/geosolutions-it/MapStore2/issues/9248

**Comment by landryb** [comment]
having a directory in the datadir with maps/contexts made available by mapstore would also allow easily to migrate them from instance to instance, instead of having to export from the db via an api/import in another platform.

But yes, having an import/export button in the context manager saving a json file would be nice.

**Comment by tdipisa** [comment]
The implementation expects to improve the context manager UI to allow an export of each single context from the context card and provide a generic import button (the design aspects will be reviewed again before the implementation if needed). The context will be imported as it was exported.

**Comment by landryb** [comment]
> The context will be imported as it was exported.

i'm not 100% sure that's the intent, to clarify:
- one wants to export a context from dev to production (eg needs to be admin on both)
- this context/map might contain layers from the "local" gs (with its full url ? eg https://dev.fqdn/geoserver/ows) and from other sources external to the platform
- to me the intent is to "remap" the urls from the "local" gs to make sure they exist on the destination gs and are taken from it, first to avoid CORS issues and to make sure the "right" layer is used.

sure, one could enforce relative urls (eg `/geoserver/ows`) in its contexts to make sure this doesnt happen, but:
- i dunno if mapstore "expands" automatically the domain when saving the map/context
- there will be existing contexts with full urls
- an option might be to drop the domain from the url when exporting (if found to be the same as mapstore) ?

@catmorales sounds right ?

**Comment by dsuren1** [comment]
Mock added to [MS issue](https://github.com/geosolutions-it/MapStore2/issues/9248)
