### ISSUE TITLE
Map viewer

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#6]
The map viewer is the main part of the WebGIS application. It needs to be well structured to host different extensions and utilities. According to the required functionalities the viewer must support the possibility manage and configure the layout in order to present data/information to the final user. In terms of capabilities must support the following possibilities:

- Possibility to define resizable zones/panels
- Possibility to reuse sections (defined viewer zones)
- Possibility to collapse sections
- Possibility to set sections position (in pixels) within the viewer
- Possibility to define sections/panels in fixed, dockable or floating position
- Different zones/sections can be part of other sections/zones of the viewer
- The viewer can be integrated in a web page through an iframe and can be easily embedded
- The viewer must fit the responsive design patterns, it must be adaptive to be compatible with diffrent kind of screen (desktop, mobiles devices)

**Comment by catmorales** [comment]
Test "Canevas"
i tested this finctionnality  on https://georchestra.geo-solutions.it/mapstore/#/

* The viewer must fit the responsive design patterns, it must be adaptive to be compatible with different kind of screen (desktop, mobiles devices) 

I zoomed on a specifical bouding box and embedded the iframe on a html page 
* navigation buttons are not responsive 
* bounding box is not used in the iframe

![image](https://user-images.githubusercontent.com/4659829/73354583-5a8dee00-4296-11ea-94c0-b72256490bba.png)
