### ISSUE TITLE
Header disappears on refresh page

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#607]
**Describe the bug**

Sometime, if i refresh (`ctrl + shift + r`   or `ctrl  + R`)  the geor header disapear.
If i try with default map (e.g https://gis.jdev.fr/mapstore/#/) it works fine.

**To Reproduce**

> **You need to be authentified**

1. Create a very simple context (e.g just map with print tool) 

> Also, You can try [this context](https://gis.jdev.fr/mapstore/#/context/print_gb)

2. Open this context (header is visible)
3. Refresh (`ctrl + R`)
4. Header is not visible anymore
5. log off
6. Got to /mapstore/# 

> Or [try here](https://gis.jdev.fr/mapstore/#/)

7. Refresh (`ctrl + R`)
8. Header is always visible

**Expected behavior**

Header stay visible

**Screenshots**

![image](https://user-images.githubusercontent.com/16317988/225247808-1654217e-e402-45e1-ade5-40829d6e3486.png)

![image](https://user-images.githubusercontent.com/16317988/225247912-dcb6e86d-fa66-48b8-ac02-52cdd288809a.png)

**Desktop (please complete the following information):**
 - OS: 

**Additional context**

**Comment by catmorales** [comment]
Hello @Gaetanbrl , perhaps you didn't add at the end of localConfig.json the lines:
```
...],
		 "context": [
          		"Header"
        	]
...
```

**Comment by catmorales** [comment]
same as https://github.com/georchestra/mapstore2-georchestra/issues/573 , I think

**Comment by Gaetanbrl** [comment]
Thanks @catmorales !
Next Llines missing in localConfig.json : 

https://github.com/georchestra/datadir/blob/5a16d090bbb77150d91095113cad6b0a0bb77b7b/mapstore/configs/localConfig.json#L1080-L1082
