### ISSUE TITLE
Build failed - need maven compiler property

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#608]
**Describe the bug**

If i follow the README, and just trigger the build, i get a build failure.

If we add maven compiler, it works.

1. Open pom.xml
2. change `<properties>` by :

```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>
```
3. trigger build `./build.sh`

![image](https://user-images.githubusercontent.com/16317988/225355648-1a448b24-36f3-493e-a4ee-b2bca0676cf4.png)

**To Reproduce**

1. git clone
2. `sh ./build.sh`

**Expected behavior**

Build success.

**Screenshots**

![image](https://user-images.githubusercontent.com/16317988/225355784-dac455fc-2137-4ca9-80e4-6e87425ae06d.png)

**Comment by landryb** [comment]
fixed by #609
