### ISSUE TITLE
[ Maven ] Spelling mistake in artifact group name

### ISSUE THREAD

**Issue by pierrejego** [georchestra/mapstore2-georchestra#610]
**Describe the bug**
 parent is
<parent>
    <groupId>og.georchestra.mapstore</groupId>
    <artifactId>mapstore-georchestra-root</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

And should be
<parent>
    <groupId>**org**.georchestra.mapstore</groupId>
    <artifactId>mapstore-georchestra-root</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

**Comment by landryb** [comment]
fixed by #611
