### ISSUE TITLE
[StreetView Plugin] ability to set parameters for the size of the default window (e.g. to display the date of recording).

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#644]
## Description
Now:

![image](https://github.com/georchestra/mapstore2-georchestra/assets/4659829/42533824-2d0f-4f25-a5b6-d8465b2cf21e)

 We need:

![image](https://github.com/georchestra/mapstore2-georchestra/assets/4659829/97d540ff-6bca-43ca-b252-8bc3fc21baf4)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Mapstore2georchestra improvement 
- [ ] Mapstore2 improvement
- [ ] Other... Please describe:

**Comment by dsuren1** [comment]
@catmorales  
Kindly correct me if I'm wrong. 
This issue asks for the ability to 
- visualize the _imagery acquisition date_ on the street view panorama panel along with other info already present 
- **OR** to visualize the _date_ along with other info while increasing the default size of the panel to fit the date in it, so the user doesn't need to resize every time to see the date.

**Comment by tdipisa** [comment]
@dsuren1 
> OR to visualize the date along with other info while increasing the default size of the panel to fit the date in it, so the user doesn't need to resize every time to see the date.

this one, I think. The default size of the panel should be configurable by plugin config.

**Comment by catmorales** [comment]
Yes I agree the answer of @tdipisa
