### ISSUE TITLE
[Annotations] Circle object - Mapstore crash entering a value in Radius field before drawing the circle 

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#645]
**Describe the bug**

I want to draw a circle (Annotation plugin). 
When I type  first (before drawing the circle or entr coordinates) the radius of the circle in the field "Rayon", Mapstore crash without any explications. 

**To Reproduce**

![annotation_circle_radius](https://github.com/georchestra/mapstore2-georchestra/assets/4659829/cef7ddda-691a-4ad9-868c-7c2536d876b1)

**Expected behavior**
UI/UX management- not be able to enter the radius before enter coordinates or clicking on the map

**Desktop (please complete the following information):**

Mapstore2-georchestra 2022.02.02 : https://github.com/georchestra/mapstore2-georchestra/commit/015b0c30b89e5c0562839b519b9b29a77beeb78d
Mapstore2 : https://github.com/geosolutions-it/MapStore2/commit/25aeef423d7a1213f7a7971c68c5a3db768dd02d
https://portail.sig.rennesmetropole.fr
Mozilla Firefox 

Same behaviour with recent release..

**Additional context**
Context by default

**Comment by dsuren1** [comment]
Fix is required only on `2023.02.xx` stable
