### ISSUE TITLE
[Annotations] Geometry title not easy to modify

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#647]
**Describe the bug**
Modify the title of one geometry is not easy : the first letter is always present

**Expected behavior**
Easier to change the title

**Screenshots**
This video has been done with the 2022 release but it has been tested also with the 2023.02.00-rc2 release with the same behaviour.

![annotation_geometrie](https://github.com/georchestra/mapstore2-georchestra/assets/4659829/8fbd629f-3473-4bff-a8e7-96deff4a4604)

**Desktop (please complete the following information):**

 - Browser Firefox

**Comment by dsuren1** [comment]
Fix is required only on MS 2023.02.xx stable

**Comment by dsuren1** [comment]
Upstream [issue](https://github.com/geosolutions-it/MapStore2/issues/9822)
