### ISSUE TITLE
Personal plugins  broken  since 2023.02.00-RC*-geOrchestra deployments

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#648]
**Describe the bug**
Since the deployment of 2023.02.00-RC1-geOrchestra and 2023.02.00-RC2-geOrchestra releases , personal plugins are broken.
* https://github.com/sigrennesmetropole/geor_signalement
* https://github.com/sigrennesmetropole/geor_tabou2_front
* https://github.com/sigrennesmetropole/geor_urbanisme_mapstore

**Description of issues**
(TODO waiting for issues)

For geor_signalement :
*  conflict between cadastrapp and signalement : https://github.com/sigrennesmetropole/geor_signalement/issues/39
*  no more action clicking on the map  : https://github.com/sigrennesmetropole/geor_signalement/issues/38

**Expected behavior**
Is there a documentation on improvments modification of components ?

**Additional context**

**Comment by Gaetanbrl** [comment]
hi @catmorales 
wich plugins are affected in your env ?

Thanks :)

**Comment by landryb** [comment]
try updating the ms2 submodule to at least a version matching the ms2 version in each of the extensions before rebuilding them..

**Comment by Gaetanbrl** [comment]
> try updating the ms2 submodule to at least 

I don't think MS2 code source is usefull. because i guess webpack build extension source only.

However, it's required to test an extension with same MS2 submodule version (same as targeted env at least). Indeed, this could break a plugin because actions / loading /etc... can changes in a recent MS2 submodule version.

**Comment by catmorales** [comment]
cf https://github.com/georchestra/mapstore2-cadastrapp/issues/182 for trying to resolve issue

**Comment by Gaetanbrl** [comment]
@catmorales after some tests, https://github.com/sigrennesmetropole/geor_tabou2_front seems working fine (testedwith https://portail-test.sig.rennesmetropole.fr/ version).

You need more tests ?

**Comment by catmorales** [comment]
I think we can close this issue
