### ISSUE TITLE
Dashboard's Tables not working since 2023.02.00-RC1-geOrchestra and 2023.02.00-RC2-geOrchestra deployments

### ISSUE THREAD

**Issue by rgoffinet** [georchestra/mapstore2-georchestra#652]
**Describe the bug**
Since the deployment of 2023.02.00-RC1-geOrchestra and 2023.02.00-RC2-geOrchestra releases, tables in dashboards shows error message : the querry sent to data seems wrong.

**To Reproduce**
1. Create a new dashboard
2. Add a new table
3. Select a layer
4. Select more than one field
5. Add the table to the dashboard
6. The table shows an error message

The same behavior happens while openning existing dashboard using Tables.
When only one field is selected the Table works correctly. It seems that when multiple fields are selected, the querry sent to data aggregate all field's names (no space after comas).

**Screenshots**
![image](https://github.com/georchestra/mapstore2-georchestra/assets/136472866/2772e3bf-a734-4a74-8844-d254f6bd5009)

**Desktop (please complete the following information):**
Browser : firefox 102.14 (32bits) ; chrome 116.0.5845 (64 bits) ; Edge 115.0.1901 (64 bits)
Version MapStore : 2023.02 RC1 & 2023.02 RC2

**Comment by tdipisa** [comment]
@catmorales @rgoffinet it doesn't seem a problem related to the table widget but with the data you are trying to load.  Looking at the error notified by the application it seems quite clear a problem like this.

- Are you maybe trying to open an existing dashboard with a table widget for which the schema of the layer on the DB side has been changed in the meantime? In that case you have to recreate the table widget
- Do you have maybe updated the schema of the DB table without reloading the feature type on the GS layer configuration

**Comment by rgoffinet** [comment]
Hello @tdipisa 
- the problem happens with existing dashboards AND new dashboards
- the table widget fails to load with all our layers when more than one field is selected while configuring the table
- No changes has been made to the schema of our layers so no reloading was made on GS
The same layers still works with table widget in 2022.02.02.

**Comment by tdipisa** [comment]
That's strange @rgoffinet we are not experiencing any issue like this in our MS environments. Can you please provide us a way to reproduce the problem? It would be good to have a GS URL we can access where the problem has been identified as well as a layer name to load.

**Comment by rgoffinet** [comment]
Hi @tdipisa,

You can reproduce it on our test environnement https://portail-test.sig.rennesmetropole.fr/mapstore/# and create a new dashboard or using an existing one such as "Dashboard Test FC" (https://portail-test.sig.rennesmetropole.fr/mapstore/#/dashboard/7444)
And you can create (or edit) a table with any layer from our "géoservices" catalog like "Arbres dans la ville de Rennes" or use any public WMS such as "Communes de Bretagne concernées par au moins un site d'intérêt pour les chiroptères - Bretagne" from GeoBretagne "https://ows.region-bretagne.fr/geoserver/rb/wms?service=wms"

If you select more than one field in the table configuration you'll get the same error as above.

**Comment by tdipisa** [comment]
@rgoffinet please try with [RC3](https://github.com/georchestra/mapstore2-georchestra/releases/tag/2023.02.00-RC3-geOrchestra) where we have provided a fix for https://github.com/geosolutions-it/MapStore2/issues/9326 and let me know

**Comment by rgoffinet** [comment]
we have deployed mapstore RC3 and this problem has been solved. Thanks for your help!
