### ISSUE TITLE
Problem with permalink generated from an old context

### ISSUE THREAD

**Issue by PLaot** [georchestra/mapstore2-georchestra#656]
When the permalink plugin is activated on a former / old context and when we click the generate permalink button from the  permalink tab an error message is displayed "Error saving permalink"

The permalink functionnality should work on existing contexts (not only new ones)

![screenshot-portail-test sig rennesmetropole fr-2023 10 03-16_29_19](https://github.com/georchestra/mapstore2-georchestra/assets/136690961/93333456-82bf-4028-ae03-96043df0d9b0)

**Comment by dsuren1** [comment]
@PLaot 
I tried with an [old context](https://georchestra.geo-solutions.it/mapstore/#/context/6053test) and was able to generate a permalink without any issue.

<img width="1247" alt="image" src="https://github.com/georchestra/mapstore2-georchestra/assets/26929983/3f6d840e-c1a8-4b43-b3ed-90c50cf2ee31">


Kindly provide us with more info to investigate further. Thanks!

**Comment by tdipisa** [comment]
@catmorales @PLaot 
did you see the comment above? Can you please provide more info in the form on specific steps to let us reproduce the issue?

**Comment by PLaot** [comment]
@tdipisa 
I have made several tests and I can not reproduce the error anymore so it seems to be fixed since the release of RC3. Thanks !

**Comment by tdipisa** [comment]
> @tdipisa I have made several tests and I can not reproduce the error anymore so it seems to be fixed since the release of RC3. Thanks !

you are welcome @PLaot
