### ISSUE TITLE
Node.js - wich version to use ?

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#672]
## Description
Many alerts shows nodejs v12 as deprecated.

![image](https://github.com/georchestra/mapstore2-georchestra/assets/16317988/30cd6904-37eb-4a63-b714-a1c36c6f9859)

I read here that nodejs v16 is the compliant verison to use with mapstore v2023.02 : 

https://github.com/geosolutions-it/MapStore2/pull/9289

But this version v16 is no longer maintained.

https://github.com/nodejs/release#release-schedule
![image](https://github.com/georchestra/mapstore2-georchestra/assets/16317988/da824e56-e3b3-46f2-bf9e-92f118ec75ee)

**So 2 questions :**

- Is v16 the right / correct version to use with 2023.02.xx branch ?
- What is the correct nodejs version to use with the latest mapstore2-geor release ?

I could update the README according to the response

**Comment by Gaetanbrl** [comment]
Here requirements for JAVA / TOMCAT / JS : 

https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/requirements/

... and some interesting information :

![image](https://github.com/georchestra/mapstore2-georchestra/assets/16317988/5c444669-172f-42ed-82c3-d042ced54c46)

**Comment by Gaetanbrl** [comment]
So, @offtherailz i guess mapstore2-geor requried same versions ?

**Comment by offtherailz** [comment]
Hi, 
geOrchestra have to use the same version used by maspstore, that is developed, deployed and tested on node 16. 

The note in the requirements documentation about "Node 18" as a typo, it is shifted one point above, it should be referenced on note ² .
This webpack issue is a blocker to pass to node 18, that has not been tested yet to be working on MapStore.

**Comment by Gaetanbrl** [comment]
Thanks @tdipisa .

**Comment by Gaetanbrl** [comment]
I reopen to update README.

**Comment by Gaetanbrl** [comment]
I close thanks.
