### ISSUE TITLE
Is 2023.02.xx stable ?

### ISSUE THREAD

**Issue by Gaetanbrl** [georchestra/mapstore2-georchestra#674]
Hi,

Mapstore2 latest release is 2023.02.00 and contain many usefull features (as fields).

So, how stable is `2023.02.xx mapstore2-georchestra` branch ? Could we use it ?

I can read 4cd959f9fbf6ae7f52bcd7b27855b2690baeb2e2 commit about "stable version" [here](https://github.com/georchestra/mapstore2-georchestra/commits/2023.02.xx).

Thanks :)

**Comment by tdipisa** [comment]
The 2023.02.xx branch is a stable branch from which all RCs have been created so far. Consider anyway that no final release has been delivered for this series for mapstore2-georchestra, only RCs for the moment and the last one is [RC3](https://github.com/georchestra/mapstore2-georchestra/releases/tag/2023.02.00-RC3-geOrchestra)
