### ISSUE TITLE
[Context Export] Unabble to export map configuration in context manager since 2023.02.RCx

### ISSUE THREAD

**Issue by rgoffinet** [georchestra/mapstore2-georchestra#679]
**Describe the bug**
Since the deployment of 2023.02.00-RC*-geOrchestra releases, we can no longer save map configuration in context manager, only the 'export context' option is now available.

**To Reproduce**
1. As administrator, create a new context or edit the configuration of an old context
2. Access page 2 of context configuration
3. Click on the options icon and select export
4. The 'export map' options is overlayed by the 'export context' option and we can't save our map configuration in a json or wmc file.

**Expected behavior**
Beeing able to export map configuration while configuring a context as it was possible in previous versions of MS2-geOrchestra.

**Screenshots**
![MapExport_202302RC_issue](https://github.com/georchestra/mapstore2-georchestra/assets/136472866/1b0a2ea5-0f89-4ae1-a03a-4bfa7c0c48ba)

**Desktop :**
- Browser : firefox 102.14 (32bits) ; chrome 116.0.5845 (64 bits) ; Edge 115.0.1901 (64 bits)
- MapStore : 2023.02 RC1, RC2 & RC3

**Additional context**
- Tested on https://portail-test.sig.rennesmetropole.fr/header/

**Comment by Gaetanbrl** [comment]
I complete this issue.
After some test, too many export-panel are loaded : 

1. Create a new contexte
https://portail-test.sig.rennesmetropole.fr/mapstore/#/context-creator/new

2. open browser web console and search export-panel class to find 3 panels :

![image](https://github.com/georchestra/mapstore2-georchestra/assets/16317988/087fb963-ca19-4a63-ae5b-962a0083a623)

This behavior is only reported from contexte editor map.

**Comment by dsuren1** [comment]
The issue happens because the control keys on both toggle operations are identical. The fix will be provided on MS and backported to stable
