### ISSUE TITLE
[Annotation] Circle radius is modified when saving the annotation 

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#681]
**Describe the bug**

**To Reproduce**
1. Go to '.https://portail-test.sig.rennesmetropole.fr..'
2. Create an annotation  with a circle geometry with a defined radius (eg. 5000m)
3. Save the geometry, save the annotation
4. The size of the circle has been modified

**Expected behavior**
conservation of the circle size 

**Screenshots**
![circle](https://github.com/georchestra/mapstore2-georchestra/assets/4659829/e8caa51f-f2ae-4a28-8128-83c8f608d500)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser Chrome
 - Version [2023.02.00-RC3]

**Comment by dsuren1** [comment]
Fix is required only on MS `2023.02.xx` stable

**Comment by tdipisa** [comment]
yes, I suppose to. That's the version we are using for ms2-georchestra @dsuren1

**Comment by tdipisa** [comment]
@ElenaGallo please retest [this fix](https://github.com/geosolutions-it/MapStore2/pull/9938) also in georchestra DEV.
