### ISSUE TITLE
[Print] Ability to print image legend with an appropriate scale

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#682]
**Describe the bug**
When printing an image legend with the map, the size of the legend doesn't match with the size configured in the layer properties

**To Reproduce**
1. Go to 'https://portail-test.sig.rennesmetropole.fr'
2. Add the map template "PLUi : plans thématiques"
3. Make visible the layer   "Orientations d'aménagement et de programmation (OAP)" (zoom in and activate it) 
4. Look at the legend and its size in the property of the layer (Largeur 300, hauteur 12)
5. Print the map with the legend in other sheet
6. Legend is not visible 

**Expected behavior**
Legend be visible like in the layer properties

**Screenshots**

![legende_light](https://github.com/georchestra/mapstore2-georchestra/assets/4659829/1ef2c028-21a4-49b2-9a98-b78f3870e148)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version [2023.02.00-RC3-geOrchestra](https://github.com/georchestra/mapstore2-georchestra/commits/2023.02.00-RC3-geOrchestra)[(fc017e19)](https://github.com/georchestra/mapstore2-georchestra/commit/fc017e19d7b2b5b4fe3ab1581a87809223221aea)

**Smartphone (please complete the following information):**

**Additional context**

[mapstore-print (11).pdf](https://github.com/georchestra/mapstore2-georchestra/files/13590708/mapstore-print.11.pdf)

**Comment by dsuren1** [comment]
@catmorales 
The legend is visible but very small. 

Currently the mapfish uses the `iconSize` of the legend options in print tool to set `width` and `height` of the legend
<img width="300" alt="Screenshot 2023-12-14 at 12 16 26 PM" src="https://github.com/georchestra/mapstore2-georchestra/assets/26929983/739c0f6a-42f7-4523-92aa-7e236f286f52">

Example: with internal layer 
| iconSize: 20                                                                                                                                                                 | iconSize: 40                                                                                                                                                                 |  
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="200" alt="Screenshot 2023-12-14 at 12 15 10 PM" src="https://github.com/georchestra/mapstore2-georchestra/assets/26929983/d1b00437-9cfa-4824-b270-961d6f3612cb"> | <img width="200" alt="Screenshot 2023-12-14 at 12 14 05 PM" src="https://github.com/georchestra/mapstore2-georchestra/assets/26929983/196829c7-4951-4abc-be93-f08f26909764"> |   |   |   |                                                                                                                                                                

@tdipisa 
To use the configured scale (i.e width and height) of the legend in layer settings, we can replace the `Icon Size` with `Width` and `Height` fields in the _Legend Options_ of the print tool and use legend sizes configured in the layer settings as these field values respectively

<img width="391" alt="image" src="https://github.com/georchestra/mapstore2-georchestra/assets/26929983/e15d0f5e-1107-4c72-8843-e08143375d1e">

Kindly let me know your thoughts. Thanks!

**Comment by landryb** [comment]
and to avoid strange results, if the user changes one of width or height, automatically adjust the other so that the aspect ratio is kept ? i doubt anyone would want to resize a legend in a stretched/compressed way....

**Comment by dsuren1** [comment]
No, we won't adjust the size automatically. 
The user can visualize this change when modifying the width/height in the **layer settings,** so the user can know if the image is stretched/compressed and enter a value that appears to fit best

**Comment by dsuren1** [comment]
**Updated behavior**

The print tool's `Legend Options` will be modified to have two fields called `Width` and `Height` replacing the `Icon Size` field  along with a new checkbox field called `Override icon size`. These new fields will hold the current default size of `24px`.
This override option will allow user to override legend's configured scale (width and height) set for the layer in the layer options and when more than one layer is present, this option will be applied for the all the applicable layers. 

By default, this option will be _unchecked_, meaning the legend's width and height configured in layer will be used per layer

**Reason**: Print tool has a common option for all the layers selected for printing and cannot be made available per layer, hence a common option will be used for all layer when user prefer to override the icon size

<img width="380" alt="image" src="https://github.com/geosolutions-it/MapStore2/assets/26929983/a94a64c7-93be-442c-b4be-32ffac2e707b">
