### ISSUE TITLE
[Attribute table] Edit the filter field is difficult

### ISSUE THREAD

**Issue by catmorales** [georchestra/mapstore2-georchestra#695]
**Describe the bug**
Filter field value in attribute table difficult to edit

** Version of Mapstore2-georchestra 

https://hub.docker.com/layers/geosolutionsit/mapstore2-georchestra/2023.02.xx/images/sha256-60e48d17f5721c2dc4094db0e79f287a4bd19bbccb29f1404a3706b54fe9232b?context=explore

**To Reproduce**
1. Go to 'https://portail-test.sig.rennesmetropole.fr/mapstore/'
2. Click on 'the attribute table of a layer.'
3. filter the results by editing a value eg : "Rennes"
4. A WFS post request is sended for each caracter edited by the user and the user must click on the field after each caracter edited --> very difficult to use

**Expected behavior**
As before the 2023.02.xx 

**Screenshots**

![attribute_table](https://github.com/georchestra/mapstore2-georchestra/assets/4659829/3c93ffad-709f-4aa5-978a-a0d04229ac8a)

**Desktop (please complete the following information):**

 - Browser Chrome

**Additional context**

**Comment by catmorales** [comment]
@tdipisa, @offtherailz  Is this a bug or a new parameter of feature editor plugin to add ?

**Comment by tdipisa** [comment]
@catmorales I think this issue was already captured by https://github.com/geosolutions-it/MapStore2/issues/9575 that has already been fixed in MS 2023.02.01. That fix is already on master here and it will be included in the stable one with https://github.com/georchestra/mapstore2-georchestra/pull/694

**Comment by catmorales** [comment]
It's OK for me.
