### ISSUE TITLE
Cadastrapp printing crash in 2023.02.00 release

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-georchestra#699]
**Describe the bug**
Installing https://github.com/georchestra/mapstore2-georchestra/releases/tag/2023.02.00-geOrchestra
I can't print plots with cadastrapp.

**To Reproduce**
1. Try to search a plot in cadastrapp, select it and the print it highligthed.
2. Check the "Print overlays" checbox
3. In the print overview, the plot isn't highlighted
4. Try to print generate an error

**Expected behavior**
Print should highlight selected plot without error

@catmorales @landryb @pierrejego

**Comment by landryb** [comment]
for a reason i don't understand, i don't have the 'Include overlays' checkbox anymore in the print dialog, but i'm on https://github.com/georchestra/mapstore2-georchestra/commit/8f3fe529ee16a045773e14848b37adc8d6ce2e2a and need to test the latest.

But printing works (without overlays)

you say 'try to print generate an error', it'd help if you provide the error message ;)

**Comment by landryb** [comment]
maybe fallout from #646 ?

**Comment by landryb** [comment]
i can reproduce, for some reason 'include overlays' is not available in a context with fewer plugins (eg cadastrapp+print only, more or less) but 'include overlays' is here on my default context, and when a plot is selected and one tries to print:
- its not shown in the preview
- trying to print fails with `Error in printing:e.features[0] is undefined`
- no query is sent to the printing backend

@tdipisa that's a regression... not sure if the regression is in ms2-cadastrapp (which maybe should be built against the same 2023.02.xx version as ms2) or in ms2-georchestra.

**Comment by landryb** [comment]
the error message is printed by https://github.com/geosolutions-it/MapStore2/blob/2023.02.xx/web/client/plugins/Print.jsx#L618 but since the selected plot is not displayed in the preview, that's probably why `e.features[0] is undefined` is triggered.

**Comment by landryb** [comment]
on 2022.01.xx, when i tick/untick the 'include overlays' box, the selected plot is shown/hidden from the preview

**Comment by MaelREBOUX** [comment]
Hello.

Here in Rennes we pointed exactly the same behaviour. Sounds like a regression.
We had many calls from our customers since monday because we upgraded MS last thursday.


![Capture d’écran 2024-02-22 à 12 28 49](https://github.com/georchestra/mapstore2-georchestra/assets/6370443/c1e64bfe-46c1-4629-b4cd-249cded11e46)

**Comment by jusabatier** [comment]
> @tdipisa that's a regression... not sure if the regression is in ms2-cadastrapp (which maybe should be built against the same 2023.02.xx version as ms2) or in ms2-georchestra.

I tried to build ms2-cadastrapp against the same MS version as ms2-georchestra uses and it doesn't solve the problem.

**Comment by landryb** [comment]
i'd try locally reverting the fix for #646

**Comment by landryb** [comment]
no luck after locally reverting geosolutions-it/MapStore2@15186518 from #646, issue still present, ticking 'include overlays' adds the cadastre layer to the preview but not the selected plot.

**Comment by landryb** [comment]
https://ids.craig.fr/mapstore/#/context/cadastre has the 'print selected plot' feature in the regular print dialog working again.

**Comment by tdipisa** [comment]
@catmorales hi 
@dsuren1 will do a check asap. thank you.

**Comment by dsuren1** [comment]
@catmorales @tdipisa 
In #646, the annotation features are filtered by `visibility` property in the features added, however in this case the features don't have the property which is causing the filter to exclude these features and eventually the layer is not printed. I will provide a fix factoring in this case

**Comment by jusabatier** [comment]
@dsuren1 Maybe you can solve https://github.com/geosolutions-it/MapStore2/issues/9791 at same time by excluding from print the features without geometry ?

**Comment by tdipisa** [comment]
@catmorales we have just updated the [image for stable branch 2023.02.xx ](https://hub.docker.com/layers/geosolutionsit/mapstore2-georchestra/2023.02.xx/images/sha256-3d9cf806dc3434a79b502f48c72153a44c2e0c28467b5ab0dd6d031f964fa177?context=explore). Can you please test also on your side and let us know if it works for you? If yes, we will provide a patch release soon.

**Comment by catmorales** [comment]
@tdipisa OK thank you I will test it

**Comment by catmorales** [comment]
I've just tested it and it seems fine. Thank you very much!

![image](https://github.com/georchestra/mapstore2-georchestra/assets/4659829/2b26a6b3-f196-4d95-9295-e2e02b504644)

Will you backport this fix in the 2023.02.00-georchestra image docker ?

**Comment by tdipisa** [comment]
@catmorales
>Will you backport this fix in the 2023.02.00-georchestra image docker ?

No, we will do a patch release 2023.02.01-geOrchestra

**Comment by tdipisa** [comment]
> @catmorales
> 
> > Will you backport this fix in the 2023.02.00-georchestra image docker ?
> 
> No, we will do a patch release 2023.02.01-geOrchestra

@catmorales done with https://github.com/georchestra/mapstore2-georchestra/releases/tag/2023.02.01-geOrchestra

**Comment by MaelREBOUX** [comment]
Good job !  Thanks for the fix.
