### ISSUE TITLE
missing unsupportedBrowser.html

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#702]
**Describe the bug**
a user visiting mapstore with an unsupported browser gets a 404 from georchestra

**Expected behavior**
A proper web page explaining the issue should be displayed to the user

https://github.com/geosolutions-it/MapStore2/blob/master/web/client/unsupportedBrowser.html should probably be added to the root of the ms2-georchestra project/repo ?

**Comment by tdipisa** [comment]
Yes @landryb the support is already there it seems to me but effectively that HTML seems missing. That's probably due tu a typo. It should be enough to add it to the root of the project.

**Comment by landryb** [comment]
tested locally by adding it to the docroot, there's no images/logo - eg https://ids.craig.fr/mapstore/unsupportedBrowser.html is a bit bland :)

**Comment by tdipisa** [comment]
yes assets can be found here https://github.com/geosolutions-it/MapStore2/tree/master/web/client/product/assets/img

**Comment by landryb** [comment]
only those images are shipped in the product subdir:
```
dist/MapStore2/web/client/product/assets/img/mapstore-header.jpg
dist/MapStore2/web/client/product/assets/img/mapstore2_logo.png
dist/MapStore2/web/client/product/assets/img/mapstorelogo.png
dist/MapStore2/web/client/product/assets/img/manager-header.jpg
dist/MapStore2/web/client/product/assets/img/mapstore-logo-0.20.png
dist/MapStore2/web/client/product/assets/img/made-in-italy-logo.png
```
and i havent found what decides which files are shipped in the resulting war from the list in https://github.com/geosolutions-it/MapStore2/tree/master/web/client/product/assets/img.

**Comment by landryb** [comment]
@catmorales i know you already have a whitelist of supported browsers, but maybe you have external users so that might affect you too.

something which is strange - before 2023.02 we were on 2022.01 and the browser check didnt trigger (eg 0 hits in my logs for `unsupportedBrowser.html`), eg we had users on opera which didn't get rejected. 


that's puzzling because the browser check support is supposed to be there since 2020 via [geosolutions-it/MapStore2/issues/4809](https://github.com/geosolutions-it/MapStore2/issues/4809)
