### ISSUE TITLE
geOrchestra's header not displaying in context

### ISSUE THREAD

**Issue by f-necas** [georchestra/mapstore2-georchestra#704]
**Version**

2023.02.00-georchestra
https://dev.geo2france.fr/mapstore/#/

**Describe the bug**
When hitting directly a mapstore context URL (e.g. `/mapstore/#/context/mycontext`),  The

**To Reproduce**
1. Go to `/mapstore/#/context/<mycontext>`

**Expected behavior**
Header's displaying

**Screenshots**
![image](https://github.com/georchestra/mapstore2-georchestra/assets/39771412/95f9f2a0-72de-42d5-90f9-f9e2cdef7fc1)

**Comment by Gaetanbrl** [comment]
To complete steps to reproduce : 

1. Go to <domain>/mapstore/#/admin or /home (as logged role)
2. Clic on a context => OK => Header is display
3. Copy this contexte URI
4. Open a new tab and past this URL to open the context directly ==> **KO => Header is hide**

**Comment by Gaetanbrl** [comment]
@f-necas, the context header (Iframe) source param seems wrong :

- Here `/mapstore/#` iframe header src : 

`<iframe id="georchestra-header" src="/portail/banner?active=mapstore" scrolling="no" frameborder="0" style="display: block; height: 90px;"></iframe>
`
- Here contexte iframe header src : 

`<iframe frameborder="0" scrolling="no" src="header.html" id="georchestra-header"></iframe>
`

For a contexte, `src="/portail/banner?active=mapstore"` works and show the correct header.

**Maybe this have to be provided by localConfig.json ?**

In addition, @catmorales response that `localConfig.json` needs this config to works :  

In the `localConfig.json`, we have to add :

```
"context": [
     "Header"
]
```

**Comment by Gaetanbrl** [comment]
See here : 

https://github.com/georchestra/mapstore2-georchestra/issues/607#issuecomment-1469764926

**Comment by f-necas** [comment]
Fixed on dev.geo2france. Indeed it was missing the context part.

@Gaetanbrl You can confirm it's working on dev ?

**Comment by Gaetanbrl** [comment]
@vfabry @f-necas 
> You can confirm it's working on dev ?

Seems works better \0/

**Comment by vfabry** [comment]
yes, it works fine !

**Comment by f-necas** [comment]
Fixed in prod too !
