### ISSUE TITLE
Update the Admin menu with Context UI

### ISSUE THREAD

**Issue by offtherailz** [georchestra/mapstore2-georchestra#76]
The app context admin UI must appears in the admin section of georchestar SDI.

Find out if possible to support the integration of menu items officially.

**Comment by mbarto** [comment]
links to https://georchestra.geo-solutions.it/mapstore/#/admin

**Comment by tdipisa** [comment]
As soon as #21 will be merged we need to map the Admin UI to be visible at the #/admin path
