### ISSUE TITLE
Map Zone - Multiple CRS support

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-georchestra#9]
The Map must work with the following Coordinates Reference Systems:

EPSG:3857 (Web Mercator)
EPSG:4326 (WGS84)
EPSG:2154 (Lambert 93)
EPSG:39XX (RGF93 / Conique Conforme XX)

**Comment by tdipisa** [comment]
@MaelREBOUX please, about **EPSG:39XX (RGF93 / Conique Conforme XX)** can you specify the exact list of CRSs for which we need to provide support.

**Comment by landryb** [comment]
France has 9 CC projections.. from EPSG:3942 to EPSG:3950. But in most usecases, not all are needed, for example in our region only 3945 & 3946 are used, and i wouldnt want the others displayed.

Personally, i wouldnt bother with those CC projections (which, imo, are pointless) but i'm not the one making decisions ;)

**Comment by catmorales** [comment]
In our region, we use the EPSG 3948 projection as native projection of all our data. We use the geoserver's capacity to reproject data to present  the viewer map with EPSG 3857. But in geoserver we restrict the WMS with 2154, 3857, 3948, 4326,
