### ISSUE TITLE
Wrong translation on application context searchbar

### ISSUE THREAD

**Issue by francoperversi** [georchestra/mapstore2-georchestra#95]
Inside the empty application context searchbar, in italian, there's: CONTESTI DI RICERCA (wrong translation of RESEARCH CONTEXT). Maybe is better only the word CERCA (SEARCH) like for the searchbar of Mapstore Homepage. 

![contesti](https://user-images.githubusercontent.com/54808782/69326357-ef97b980-0c4b-11ea-8f5c-76d64005c50d.jpg)

**Other useful information**: In Mapstore Account manager the serachbars of Users and Groups sections have the written SEARCH FOR USERS and SEARCH GROUPS. Maybe could be better decide to put only SEARCH in all situations

**Comment by offtherailz** [comment]
This PR fixes this issue: 
https://github.com/geosolutions-it/MapStore2/pull/4541
