### ISSUE TITLE
Impossible to close import session

### ISSUE THREAD

**Issue by francoperversi** [georchestra/mapstore2-georchestra#97]
It's impossible to close the import session, probably because the topbar hide the (X) button

![close](https://user-images.githubusercontent.com/54808782/69261433-d4806780-0bc1-11ea-9ac7-81dd861d8ebd.jpg)

**Comment by landryb** [comment]
can confirm this bug, stumbled upon it too :)

**Comment by tdipisa** [comment]
We are working on it @landryb, we are under testing and few issues have been opened, we are working on them.
